# GoReleaser configuration
# Documentation: https://goreleaser.com

version: 2

# Hooks to run before building
before:
  hooks:
    # Generate version information
    - go generate ./...
    # Tidy dependencies
    - go mod tidy
    # Verify dependencies
    - go mod verify

# Build configuration
builds:
  - id: application
    no_unique_dist_dir: true
    binary: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}amd64_v1
      {{- else if eq .Arch "arm64" }}arm64_v8.0
      {{- else if eq .Arch "arm" }}arm_{{ .Arm }}
      {{- else }}{{ .Arch }}{{ end }}
    main: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
    # Ignore combinations
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    # Build flags
    flags:
      - -trimpath
    ldflags:
      - -s -w
    # Mod timestamp for reproducible builds
    mod_timestamp: "{{ .CommitTimestamp }}"

# Archive configuration
archives:
  - id: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    formats: [ tar.gz, zip ]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}amd64_v1
      {{- else if eq .Arch "arm64" }}arm64_v8.0
      {{- else if eq .Arch "arm" }}arm_{{ .Arm }}
      {{- else }}{{ .Arch }}{{ end }}_
      {{- .Version }}
    files:
      - LICENSE*
      - README*
      - CHANGELOG*
      - config*.yaml

# Checksum configuration
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

# Snapshot configuration (for unreleased builds)
snapshot:
  version_template: "{{ incpatch .Version }}-next"

# Changelog configuration
changelog:
  use: github
  sort: asc
  abbrev: 7
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Performance Improvements
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Refactors
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: Documentation
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 4
    - title: Build System
      regexp: '^.*?build(\([[:word:]]+\))??!?:.+$'
      order: 5
    - title: Other Changes
      order: 999
  filters:
    exclude:
      - '^test:'
      - '^chore:'
      - '^ci:'
      - '^style:'
      - Merge pull request
      - Merge branch

# Release configuration
release:
  github:
    owner: inovacc
    name: clonr
  draft: false
  prerelease: auto
  mode: append
  header: |
    ## {{ .ProjectName }} {{ .Version }}

    **Release Date:** {{ .Date }}

    ### Installation

    Download the appropriate archive for your platform from the assets below, extract, and move to your PATH.

    #### Linux (amd64)
    ```bash
    curl -sfL https://github.com/inovacc/{{ .ProjectName }}/releases/download/{{ .Tag }}/{{ .ProjectName }}_linux_amd64_v1_{{ .Version }}.tar.gz | tar xz
    sudo mv {{ .ProjectName }}_linux_amd64_v1 /usr/local/bin/{{ .ProjectName }}
    ```

    #### Windows (amd64)
    Download the `.zip` file from assets, extract, and add to your PATH.

  footer: |
    ---

    **Full Changelog**: https://github.com/inovacc/{{ .ProjectName }}/compare/{{ .PreviousTag }}...{{ .Tag }}

    **Docker Images**: https://github.com/inovacc/{{ .ProjectName }}/pkgs/container/{{ .ProjectName }}

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

# Announce configuration (optional)
announce:
  skip: "{{gt .Patch 0}}" # Skip patch releases

# Metadata
metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

sboms:
  - id: binaries-sbom
    artifacts: binary
    cmd: syft
    args:
      - "$artifact"
      - "--output"
      - "cyclonedx-json=$document"
    documents:
      - "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}.sbom.json"
