version: '3'

vars:
  MAIN_PACKAGE: .
  BIN_DIR: bin
  BIN_NAME: clonr
  COVERAGE_FILE: coverage.out
  GITHUB_OWNER:
    sh: echo "${GITHUB_OWNER:-dyammarcano}"

tasks:
  # === INFORMATION ===
  default:
    desc: List all available tasks
    cmds:
      - task --list

  # === CODE GENERATION ===
  generate:
    desc: Generate version information and other generated code
    cmds:
      - go generate ./...

  proto:
    desc: Generate protobuf code
    cmds:
      - echo "Generating protobuf code..."
      - go run scripts/proto/generate.go

  # === BUILD TASKS ===
  install:
    desc: Install clonr binary to GOPATH/bin
    deps: [ generate ]
    cmds:
      - echo "Installing clonr..."
      - go install {{.MAIN_PACKAGE}}
      - echo "Installation complete!"

  build:dev:
    desc: Build development snapshot with goreleaser
    env:
      GITHUB_OWNER: "{{.GITHUB_OWNER}}"
    cmds:
      - goreleaser build --snapshot --clean

  build:prod:
    desc: Build production snapshot with goreleaser
    env:
      GITHUB_OWNER: "{{.GITHUB_OWNER}}"
    cmds:
      - goreleaser --snapshot --skip-publish,announce --rm-dist

  # === TEST TASKS ===
  test:
    desc: Run all tests with coverage
    cmds:
      - go test -v -race -coverprofile={{.COVERAGE_FILE}} ./...

  test:coverage:
    desc: Generate HTML coverage report
    deps: [ test ]
    cmds:
      - go tool cover -html={{.COVERAGE_FILE}} -o coverage.html
      - echo "Coverage report generated at coverage.html"

  test:cover:
    desc: Run tests and show coverage percentage
    cmds:
      - go test -coverprofile={{.COVERAGE_FILE}} ./...
      - cmd: go tool cover -func={{.COVERAGE_FILE}} | findstr "total:"
        platforms: [ windows ]
      - cmd: go tool cover -func={{.COVERAGE_FILE}} | grep "total:"
        platforms: [ linux, darwin ]

  test:unit:
    desc: Run unit tests only (skip integration)
    cmds:
      - go test -v -short ./...

  # === CODE QUALITY ===
  fmt:
    desc: Format all Go code
    cmds:
      - go fmt ./...
      - goimports -w .

  vet:
    desc: Run go vet static analysis
    cmds:
      - go vet ./...

  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run ./...

  lint:fix:
    desc: Run linter and auto-fix issues
    cmds:
      - golangci-lint run --fix ./...

  check:
    desc: Run all quality checks (fmt, vet, lint, test)
    cmds:
      - task: fmt
      - task: vet
      - task: lint
      - task: test

  # === RUN TASKS ===
  run:
    desc: Run the application
    deps: [ generate ]
    cmds:
      - go run {{.MAIN_PACKAGE}}

  # === DEPENDENCY MANAGEMENT ===
  deps:
    desc: Download and tidy dependencies
    cmds:
      - go mod download
      - go mod tidy
      - go mod verify

  # === CLEANUP ===
  clean:
    desc: Clean build artifacts and generated files
    cmds:
      - cmd: rm -rf {{.BIN_DIR}} dist
        platforms: [linux, darwin]
      - cmd: if exist {{.BIN_DIR}} rmdir /s /q {{.BIN_DIR}}
        platforms: [windows]
      - cmd: if exist dist rmdir /s /q dist
        platforms: [windows]
      - rm -f {{.COVERAGE_FILE}} coverage.html
      - rm -f .go-version cmd/version.go

  clean:proto:
    desc: Clean generated protobuf files
    cmds:
      - cmd: rm -f pkg/api/v1/*.pb.go
        platforms: [linux, darwin]
      - cmd: if exist pkg\api\v1\*.pb.go del /q pkg\api\v1\*.pb.go
        platforms: [windows]

  clean:all:
    desc: Clean everything (build artifacts, proto, coverage)
    cmds:
      - task: clean
      - task: clean:proto

  # === RELEASE TASKS ===
  release:
    desc: Create a production release with goreleaser (requires git tag)
    deps: [ generate ]
    env:
      GITHUB_OWNER: "{{.GITHUB_OWNER}}"
    cmds:
      - goreleaser release --clean

  release:snapshot:
    desc: Create a snapshot release (no git tag required)
    deps: [ generate ]
    env:
      GITHUB_OWNER: "{{.GITHUB_OWNER}}"
    cmds:
      - goreleaser release --snapshot --clean

  release:check:
    desc: Validate goreleaser configuration
    env:
      GITHUB_OWNER: "{{.GITHUB_OWNER}}"
    cmds:
      - goreleaser check
