// Code generated by go generate; DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"
)

// Version information embedded at build time
const (
	// Version is the application version (from git tag or VERSION env)
	Version = "v0.1.0"

	// GitHash is the git commit hash
	GitHash = "e6d7bd99a35e55dca678d011fa62fb33ae993c75"

	// BuildTime is when the binary was built
	BuildTime = "2025-12-29T13:27:44Z"

	// BuildHash is a unique hash for this build
	BuildHash = "795f7e17747992eaff5c56283708f2d6ac48c6c6689e85fb315fa99770cc8ec2"

	// GoVersion is the Go version used to build
	GoVersion = "go1.25.5"

	// GOOS is the target operating system
	GOOS = "windows"

	// GOARCH is the target architecture
	GOARCH = "amd64"
)

// VersionInfo contains all version metadata.
type VersionInfo struct {
	GoVersion string `json:"go_version"`
	GoOS      string `json:"goos"`
	GoArch    string `json:"goarch"`
	Version   string `json:"version"`
	GitHash   string `json:"git_hash"`
	BuildTime string `json:"build_time"`
	BuildHash string `json:"build_hash"`
}

// GetVersionInfo returns the version information.
func GetVersionInfo() *VersionInfo {
	return &VersionInfo{
		GoVersion: GoVersion,
		GoOS:      GOOS,
		GoArch:    GOARCH,
		Version:   Version,
		GitHash:   GitHash,
		BuildTime: BuildTime,
		BuildHash: BuildHash,
	}
}

// GetVersionJSON returns the version information as a JSON string.
func GetVersionJSON() string {
	data, err := json.MarshalIndent(GetVersionInfo(), "", "  ")
	if err != nil {
		return "{}"
	}

	return string(data)
}

func printVersion() {
	fmt.Printf("Version:    %s\n", Version)
	fmt.Printf("Git Hash:   %s\n", GitHash)
	fmt.Printf("Build Time: %s\n", BuildTime)
	fmt.Printf("Build Hash: %s\n", BuildHash)
	fmt.Printf("Go Version: %s\n", GoVersion)
	fmt.Printf("OS/Arch:    %s/%s\n", GOOS, GOARCH)
}
