// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: v1/clonr.proto

package clonrv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClonrService_Ping_FullMethodName                  = "/clonr.v1.ClonrService/Ping"
	ClonrService_SaveRepo_FullMethodName              = "/clonr.v1.ClonrService/SaveRepo"
	ClonrService_RepoExistsByURL_FullMethodName       = "/clonr.v1.ClonrService/RepoExistsByURL"
	ClonrService_RepoExistsByPath_FullMethodName      = "/clonr.v1.ClonrService/RepoExistsByPath"
	ClonrService_InsertRepoIfNotExists_FullMethodName = "/clonr.v1.ClonrService/InsertRepoIfNotExists"
	ClonrService_GetAllRepos_FullMethodName           = "/clonr.v1.ClonrService/GetAllRepos"
	ClonrService_GetRepos_FullMethodName              = "/clonr.v1.ClonrService/GetRepos"
	ClonrService_SetFavoriteByURL_FullMethodName      = "/clonr.v1.ClonrService/SetFavoriteByURL"
	ClonrService_UpdateRepoTimestamp_FullMethodName   = "/clonr.v1.ClonrService/UpdateRepoTimestamp"
	ClonrService_RemoveRepoByURL_FullMethodName       = "/clonr.v1.ClonrService/RemoveRepoByURL"
	ClonrService_GetConfig_FullMethodName             = "/clonr.v1.ClonrService/GetConfig"
	ClonrService_SaveConfig_FullMethodName            = "/clonr.v1.ClonrService/SaveConfig"
	ClonrService_SaveProfile_FullMethodName           = "/clonr.v1.ClonrService/SaveProfile"
	ClonrService_GetProfile_FullMethodName            = "/clonr.v1.ClonrService/GetProfile"
	ClonrService_GetActiveProfile_FullMethodName      = "/clonr.v1.ClonrService/GetActiveProfile"
	ClonrService_SetActiveProfile_FullMethodName      = "/clonr.v1.ClonrService/SetActiveProfile"
	ClonrService_ListProfiles_FullMethodName          = "/clonr.v1.ClonrService/ListProfiles"
	ClonrService_DeleteProfile_FullMethodName         = "/clonr.v1.ClonrService/DeleteProfile"
	ClonrService_ProfileExists_FullMethodName         = "/clonr.v1.ClonrService/ProfileExists"
	ClonrService_SaveDockerProfile_FullMethodName     = "/clonr.v1.ClonrService/SaveDockerProfile"
	ClonrService_GetDockerProfile_FullMethodName      = "/clonr.v1.ClonrService/GetDockerProfile"
	ClonrService_ListDockerProfiles_FullMethodName    = "/clonr.v1.ClonrService/ListDockerProfiles"
	ClonrService_DeleteDockerProfile_FullMethodName   = "/clonr.v1.ClonrService/DeleteDockerProfile"
	ClonrService_DockerProfileExists_FullMethodName   = "/clonr.v1.ClonrService/DockerProfileExists"
	ClonrService_SaveWorkspace_FullMethodName         = "/clonr.v1.ClonrService/SaveWorkspace"
	ClonrService_GetWorkspace_FullMethodName          = "/clonr.v1.ClonrService/GetWorkspace"
	ClonrService_GetActiveWorkspace_FullMethodName    = "/clonr.v1.ClonrService/GetActiveWorkspace"
	ClonrService_SetActiveWorkspace_FullMethodName    = "/clonr.v1.ClonrService/SetActiveWorkspace"
	ClonrService_ListWorkspaces_FullMethodName        = "/clonr.v1.ClonrService/ListWorkspaces"
	ClonrService_DeleteWorkspace_FullMethodName       = "/clonr.v1.ClonrService/DeleteWorkspace"
	ClonrService_WorkspaceExists_FullMethodName       = "/clonr.v1.ClonrService/WorkspaceExists"
	ClonrService_GetReposByWorkspace_FullMethodName   = "/clonr.v1.ClonrService/GetReposByWorkspace"
	ClonrService_UpdateRepoWorkspace_FullMethodName   = "/clonr.v1.ClonrService/UpdateRepoWorkspace"
)

// ClonrServiceClient is the client API for ClonrService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ClonrService defines all database operations for Clonr
type ClonrServiceClient interface {
	// Health check - corresponds to Ping()
	Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	// Repository operations
	SaveRepo(ctx context.Context, in *SaveRepoRequest, opts ...grpc.CallOption) (*SaveRepoResponse, error)
	RepoExistsByURL(ctx context.Context, in *RepoExistsByURLRequest, opts ...grpc.CallOption) (*RepoExistsByURLResponse, error)
	RepoExistsByPath(ctx context.Context, in *RepoExistsByPathRequest, opts ...grpc.CallOption) (*RepoExistsByPathResponse, error)
	InsertRepoIfNotExists(ctx context.Context, in *InsertRepoIfNotExistsRequest, opts ...grpc.CallOption) (*InsertRepoIfNotExistsResponse, error)
	GetAllRepos(ctx context.Context, in *GetAllReposRequest, opts ...grpc.CallOption) (*GetAllReposResponse, error)
	GetRepos(ctx context.Context, in *GetReposRequest, opts ...grpc.CallOption) (*GetReposResponse, error)
	SetFavoriteByURL(ctx context.Context, in *SetFavoriteRequest, opts ...grpc.CallOption) (*SetFavoriteResponse, error)
	UpdateRepoTimestamp(ctx context.Context, in *UpdateRepoTimestampRequest, opts ...grpc.CallOption) (*UpdateRepoTimestampResponse, error)
	RemoveRepoByURL(ctx context.Context, in *RemoveRepoByURLRequest, opts ...grpc.CallOption) (*RemoveRepoByURLResponse, error)
	// Configuration operations
	GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error)
	SaveConfig(ctx context.Context, in *SaveConfigRequest, opts ...grpc.CallOption) (*SaveConfigResponse, error)
	// Profile operations
	SaveProfile(ctx context.Context, in *SaveProfileRequest, opts ...grpc.CallOption) (*SaveProfileResponse, error)
	GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*GetProfileResponse, error)
	GetActiveProfile(ctx context.Context, in *GetActiveProfileRequest, opts ...grpc.CallOption) (*GetActiveProfileResponse, error)
	SetActiveProfile(ctx context.Context, in *SetActiveProfileRequest, opts ...grpc.CallOption) (*SetActiveProfileResponse, error)
	ListProfiles(ctx context.Context, in *ListProfilesRequest, opts ...grpc.CallOption) (*ListProfilesResponse, error)
	DeleteProfile(ctx context.Context, in *DeleteProfileRequest, opts ...grpc.CallOption) (*DeleteProfileResponse, error)
	ProfileExists(ctx context.Context, in *ProfileExistsRequest, opts ...grpc.CallOption) (*ProfileExistsResponse, error)
	// Docker profile operations
	SaveDockerProfile(ctx context.Context, in *SaveDockerProfileRequest, opts ...grpc.CallOption) (*SaveDockerProfileResponse, error)
	GetDockerProfile(ctx context.Context, in *GetDockerProfileRequest, opts ...grpc.CallOption) (*GetDockerProfileResponse, error)
	ListDockerProfiles(ctx context.Context, in *ListDockerProfilesRequest, opts ...grpc.CallOption) (*ListDockerProfilesResponse, error)
	DeleteDockerProfile(ctx context.Context, in *DeleteDockerProfileRequest, opts ...grpc.CallOption) (*DeleteDockerProfileResponse, error)
	DockerProfileExists(ctx context.Context, in *DockerProfileExistsRequest, opts ...grpc.CallOption) (*DockerProfileExistsResponse, error)
	// Workspace operations
	SaveWorkspace(ctx context.Context, in *SaveWorkspaceRequest, opts ...grpc.CallOption) (*SaveWorkspaceResponse, error)
	GetWorkspace(ctx context.Context, in *GetWorkspaceRequest, opts ...grpc.CallOption) (*GetWorkspaceResponse, error)
	GetActiveWorkspace(ctx context.Context, in *GetActiveWorkspaceRequest, opts ...grpc.CallOption) (*GetActiveWorkspaceResponse, error)
	SetActiveWorkspace(ctx context.Context, in *SetActiveWorkspaceRequest, opts ...grpc.CallOption) (*SetActiveWorkspaceResponse, error)
	ListWorkspaces(ctx context.Context, in *ListWorkspacesRequest, opts ...grpc.CallOption) (*ListWorkspacesResponse, error)
	DeleteWorkspace(ctx context.Context, in *DeleteWorkspaceRequest, opts ...grpc.CallOption) (*DeleteWorkspaceResponse, error)
	WorkspaceExists(ctx context.Context, in *WorkspaceExistsRequest, opts ...grpc.CallOption) (*WorkspaceExistsResponse, error)
	GetReposByWorkspace(ctx context.Context, in *GetReposByWorkspaceRequest, opts ...grpc.CallOption) (*GetReposByWorkspaceResponse, error)
	UpdateRepoWorkspace(ctx context.Context, in *UpdateRepoWorkspaceRequest, opts ...grpc.CallOption) (*UpdateRepoWorkspaceResponse, error)
}

type clonrServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClonrServiceClient(cc grpc.ClientConnInterface) ClonrServiceClient {
	return &clonrServiceClient{cc}
}

func (c *clonrServiceClient) Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ClonrService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clonrServiceClient) SaveRepo(ctx context.Context, in *SaveRepoRequest, opts ...grpc.CallOption) (*SaveRepoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveRepoResponse)
	err := c.cc.Invoke(ctx, ClonrService_SaveRepo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clonrServiceClient) RepoExistsByURL(ctx context.Context, in *RepoExistsByURLRequest, opts ...grpc.CallOption) (*RepoExistsByURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepoExistsByURLResponse)
	err := c.cc.Invoke(ctx, ClonrService_RepoExistsByURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clonrServiceClient) RepoExistsByPath(ctx context.Context, in *RepoExistsByPathRequest, opts ...grpc.CallOption) (*RepoExistsByPathResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepoExistsByPathResponse)
	err := c.cc.Invoke(ctx, ClonrService_RepoExistsByPath_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clonrServiceClient) InsertRepoIfNotExists(ctx context.Context, in *InsertRepoIfNotExistsRequest, opts ...grpc.CallOption) (*InsertRepoIfNotExistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InsertRepoIfNotExistsResponse)
	err := c.cc.Invoke(ctx, ClonrService_InsertRepoIfNotExists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clonrServiceClient) GetAllRepos(ctx context.Context, in *GetAllReposRequest, opts ...grpc.CallOption) (*GetAllReposResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllReposResponse)
	err := c.cc.Invoke(ctx, ClonrService_GetAllRepos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clonrServiceClient) GetRepos(ctx context.Context, in *GetReposRequest, opts ...grpc.CallOption) (*GetReposResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReposResponse)
	err := c.cc.Invoke(ctx, ClonrService_GetRepos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clonrServiceClient) SetFavoriteByURL(ctx context.Context, in *SetFavoriteRequest, opts ...grpc.CallOption) (*SetFavoriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetFavoriteResponse)
	err := c.cc.Invoke(ctx, ClonrService_SetFavoriteByURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clonrServiceClient) UpdateRepoTimestamp(ctx context.Context, in *UpdateRepoTimestampRequest, opts ...grpc.CallOption) (*UpdateRepoTimestampResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRepoTimestampResponse)
	err := c.cc.Invoke(ctx, ClonrService_UpdateRepoTimestamp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clonrServiceClient) RemoveRepoByURL(ctx context.Context, in *RemoveRepoByURLRequest, opts ...grpc.CallOption) (*RemoveRepoByURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveRepoByURLResponse)
	err := c.cc.Invoke(ctx, ClonrService_RemoveRepoByURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clonrServiceClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConfigResponse)
	err := c.cc.Invoke(ctx, ClonrService_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clonrServiceClient) SaveConfig(ctx context.Context, in *SaveConfigRequest, opts ...grpc.CallOption) (*SaveConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveConfigResponse)
	err := c.cc.Invoke(ctx, ClonrService_SaveConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clonrServiceClient) SaveProfile(ctx context.Context, in *SaveProfileRequest, opts ...grpc.CallOption) (*SaveProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveProfileResponse)
	err := c.cc.Invoke(ctx, ClonrService_SaveProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clonrServiceClient) GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*GetProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProfileResponse)
	err := c.cc.Invoke(ctx, ClonrService_GetProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clonrServiceClient) GetActiveProfile(ctx context.Context, in *GetActiveProfileRequest, opts ...grpc.CallOption) (*GetActiveProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetActiveProfileResponse)
	err := c.cc.Invoke(ctx, ClonrService_GetActiveProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clonrServiceClient) SetActiveProfile(ctx context.Context, in *SetActiveProfileRequest, opts ...grpc.CallOption) (*SetActiveProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetActiveProfileResponse)
	err := c.cc.Invoke(ctx, ClonrService_SetActiveProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clonrServiceClient) ListProfiles(ctx context.Context, in *ListProfilesRequest, opts ...grpc.CallOption) (*ListProfilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProfilesResponse)
	err := c.cc.Invoke(ctx, ClonrService_ListProfiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clonrServiceClient) DeleteProfile(ctx context.Context, in *DeleteProfileRequest, opts ...grpc.CallOption) (*DeleteProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteProfileResponse)
	err := c.cc.Invoke(ctx, ClonrService_DeleteProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clonrServiceClient) ProfileExists(ctx context.Context, in *ProfileExistsRequest, opts ...grpc.CallOption) (*ProfileExistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProfileExistsResponse)
	err := c.cc.Invoke(ctx, ClonrService_ProfileExists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clonrServiceClient) SaveDockerProfile(ctx context.Context, in *SaveDockerProfileRequest, opts ...grpc.CallOption) (*SaveDockerProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveDockerProfileResponse)
	err := c.cc.Invoke(ctx, ClonrService_SaveDockerProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clonrServiceClient) GetDockerProfile(ctx context.Context, in *GetDockerProfileRequest, opts ...grpc.CallOption) (*GetDockerProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDockerProfileResponse)
	err := c.cc.Invoke(ctx, ClonrService_GetDockerProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clonrServiceClient) ListDockerProfiles(ctx context.Context, in *ListDockerProfilesRequest, opts ...grpc.CallOption) (*ListDockerProfilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDockerProfilesResponse)
	err := c.cc.Invoke(ctx, ClonrService_ListDockerProfiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clonrServiceClient) DeleteDockerProfile(ctx context.Context, in *DeleteDockerProfileRequest, opts ...grpc.CallOption) (*DeleteDockerProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDockerProfileResponse)
	err := c.cc.Invoke(ctx, ClonrService_DeleteDockerProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clonrServiceClient) DockerProfileExists(ctx context.Context, in *DockerProfileExistsRequest, opts ...grpc.CallOption) (*DockerProfileExistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DockerProfileExistsResponse)
	err := c.cc.Invoke(ctx, ClonrService_DockerProfileExists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clonrServiceClient) SaveWorkspace(ctx context.Context, in *SaveWorkspaceRequest, opts ...grpc.CallOption) (*SaveWorkspaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveWorkspaceResponse)
	err := c.cc.Invoke(ctx, ClonrService_SaveWorkspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clonrServiceClient) GetWorkspace(ctx context.Context, in *GetWorkspaceRequest, opts ...grpc.CallOption) (*GetWorkspaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWorkspaceResponse)
	err := c.cc.Invoke(ctx, ClonrService_GetWorkspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clonrServiceClient) GetActiveWorkspace(ctx context.Context, in *GetActiveWorkspaceRequest, opts ...grpc.CallOption) (*GetActiveWorkspaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetActiveWorkspaceResponse)
	err := c.cc.Invoke(ctx, ClonrService_GetActiveWorkspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clonrServiceClient) SetActiveWorkspace(ctx context.Context, in *SetActiveWorkspaceRequest, opts ...grpc.CallOption) (*SetActiveWorkspaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetActiveWorkspaceResponse)
	err := c.cc.Invoke(ctx, ClonrService_SetActiveWorkspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clonrServiceClient) ListWorkspaces(ctx context.Context, in *ListWorkspacesRequest, opts ...grpc.CallOption) (*ListWorkspacesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWorkspacesResponse)
	err := c.cc.Invoke(ctx, ClonrService_ListWorkspaces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clonrServiceClient) DeleteWorkspace(ctx context.Context, in *DeleteWorkspaceRequest, opts ...grpc.CallOption) (*DeleteWorkspaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteWorkspaceResponse)
	err := c.cc.Invoke(ctx, ClonrService_DeleteWorkspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clonrServiceClient) WorkspaceExists(ctx context.Context, in *WorkspaceExistsRequest, opts ...grpc.CallOption) (*WorkspaceExistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkspaceExistsResponse)
	err := c.cc.Invoke(ctx, ClonrService_WorkspaceExists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clonrServiceClient) GetReposByWorkspace(ctx context.Context, in *GetReposByWorkspaceRequest, opts ...grpc.CallOption) (*GetReposByWorkspaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReposByWorkspaceResponse)
	err := c.cc.Invoke(ctx, ClonrService_GetReposByWorkspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clonrServiceClient) UpdateRepoWorkspace(ctx context.Context, in *UpdateRepoWorkspaceRequest, opts ...grpc.CallOption) (*UpdateRepoWorkspaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRepoWorkspaceResponse)
	err := c.cc.Invoke(ctx, ClonrService_UpdateRepoWorkspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClonrServiceServer is the server API for ClonrService service.
// All implementations must embed UnimplementedClonrServiceServer
// for forward compatibility.
//
// ClonrService defines all database operations for Clonr
type ClonrServiceServer interface {
	// Health check - corresponds to Ping()
	Ping(context.Context, *Empty) (*Empty, error)
	// Repository operations
	SaveRepo(context.Context, *SaveRepoRequest) (*SaveRepoResponse, error)
	RepoExistsByURL(context.Context, *RepoExistsByURLRequest) (*RepoExistsByURLResponse, error)
	RepoExistsByPath(context.Context, *RepoExistsByPathRequest) (*RepoExistsByPathResponse, error)
	InsertRepoIfNotExists(context.Context, *InsertRepoIfNotExistsRequest) (*InsertRepoIfNotExistsResponse, error)
	GetAllRepos(context.Context, *GetAllReposRequest) (*GetAllReposResponse, error)
	GetRepos(context.Context, *GetReposRequest) (*GetReposResponse, error)
	SetFavoriteByURL(context.Context, *SetFavoriteRequest) (*SetFavoriteResponse, error)
	UpdateRepoTimestamp(context.Context, *UpdateRepoTimestampRequest) (*UpdateRepoTimestampResponse, error)
	RemoveRepoByURL(context.Context, *RemoveRepoByURLRequest) (*RemoveRepoByURLResponse, error)
	// Configuration operations
	GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error)
	SaveConfig(context.Context, *SaveConfigRequest) (*SaveConfigResponse, error)
	// Profile operations
	SaveProfile(context.Context, *SaveProfileRequest) (*SaveProfileResponse, error)
	GetProfile(context.Context, *GetProfileRequest) (*GetProfileResponse, error)
	GetActiveProfile(context.Context, *GetActiveProfileRequest) (*GetActiveProfileResponse, error)
	SetActiveProfile(context.Context, *SetActiveProfileRequest) (*SetActiveProfileResponse, error)
	ListProfiles(context.Context, *ListProfilesRequest) (*ListProfilesResponse, error)
	DeleteProfile(context.Context, *DeleteProfileRequest) (*DeleteProfileResponse, error)
	ProfileExists(context.Context, *ProfileExistsRequest) (*ProfileExistsResponse, error)
	// Docker profile operations
	SaveDockerProfile(context.Context, *SaveDockerProfileRequest) (*SaveDockerProfileResponse, error)
	GetDockerProfile(context.Context, *GetDockerProfileRequest) (*GetDockerProfileResponse, error)
	ListDockerProfiles(context.Context, *ListDockerProfilesRequest) (*ListDockerProfilesResponse, error)
	DeleteDockerProfile(context.Context, *DeleteDockerProfileRequest) (*DeleteDockerProfileResponse, error)
	DockerProfileExists(context.Context, *DockerProfileExistsRequest) (*DockerProfileExistsResponse, error)
	// Workspace operations
	SaveWorkspace(context.Context, *SaveWorkspaceRequest) (*SaveWorkspaceResponse, error)
	GetWorkspace(context.Context, *GetWorkspaceRequest) (*GetWorkspaceResponse, error)
	GetActiveWorkspace(context.Context, *GetActiveWorkspaceRequest) (*GetActiveWorkspaceResponse, error)
	SetActiveWorkspace(context.Context, *SetActiveWorkspaceRequest) (*SetActiveWorkspaceResponse, error)
	ListWorkspaces(context.Context, *ListWorkspacesRequest) (*ListWorkspacesResponse, error)
	DeleteWorkspace(context.Context, *DeleteWorkspaceRequest) (*DeleteWorkspaceResponse, error)
	WorkspaceExists(context.Context, *WorkspaceExistsRequest) (*WorkspaceExistsResponse, error)
	GetReposByWorkspace(context.Context, *GetReposByWorkspaceRequest) (*GetReposByWorkspaceResponse, error)
	UpdateRepoWorkspace(context.Context, *UpdateRepoWorkspaceRequest) (*UpdateRepoWorkspaceResponse, error)
	mustEmbedUnimplementedClonrServiceServer()
}

// UnimplementedClonrServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClonrServiceServer struct{}

func (UnimplementedClonrServiceServer) Ping(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedClonrServiceServer) SaveRepo(context.Context, *SaveRepoRequest) (*SaveRepoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveRepo not implemented")
}
func (UnimplementedClonrServiceServer) RepoExistsByURL(context.Context, *RepoExistsByURLRequest) (*RepoExistsByURLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RepoExistsByURL not implemented")
}
func (UnimplementedClonrServiceServer) RepoExistsByPath(context.Context, *RepoExistsByPathRequest) (*RepoExistsByPathResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RepoExistsByPath not implemented")
}
func (UnimplementedClonrServiceServer) InsertRepoIfNotExists(context.Context, *InsertRepoIfNotExistsRequest) (*InsertRepoIfNotExistsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InsertRepoIfNotExists not implemented")
}
func (UnimplementedClonrServiceServer) GetAllRepos(context.Context, *GetAllReposRequest) (*GetAllReposResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllRepos not implemented")
}
func (UnimplementedClonrServiceServer) GetRepos(context.Context, *GetReposRequest) (*GetReposResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRepos not implemented")
}
func (UnimplementedClonrServiceServer) SetFavoriteByURL(context.Context, *SetFavoriteRequest) (*SetFavoriteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetFavoriteByURL not implemented")
}
func (UnimplementedClonrServiceServer) UpdateRepoTimestamp(context.Context, *UpdateRepoTimestampRequest) (*UpdateRepoTimestampResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRepoTimestamp not implemented")
}
func (UnimplementedClonrServiceServer) RemoveRepoByURL(context.Context, *RemoveRepoByURLRequest) (*RemoveRepoByURLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveRepoByURL not implemented")
}
func (UnimplementedClonrServiceServer) GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedClonrServiceServer) SaveConfig(context.Context, *SaveConfigRequest) (*SaveConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveConfig not implemented")
}
func (UnimplementedClonrServiceServer) SaveProfile(context.Context, *SaveProfileRequest) (*SaveProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveProfile not implemented")
}
func (UnimplementedClonrServiceServer) GetProfile(context.Context, *GetProfileRequest) (*GetProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProfile not implemented")
}
func (UnimplementedClonrServiceServer) GetActiveProfile(context.Context, *GetActiveProfileRequest) (*GetActiveProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActiveProfile not implemented")
}
func (UnimplementedClonrServiceServer) SetActiveProfile(context.Context, *SetActiveProfileRequest) (*SetActiveProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetActiveProfile not implemented")
}
func (UnimplementedClonrServiceServer) ListProfiles(context.Context, *ListProfilesRequest) (*ListProfilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProfiles not implemented")
}
func (UnimplementedClonrServiceServer) DeleteProfile(context.Context, *DeleteProfileRequest) (*DeleteProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteProfile not implemented")
}
func (UnimplementedClonrServiceServer) ProfileExists(context.Context, *ProfileExistsRequest) (*ProfileExistsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProfileExists not implemented")
}
func (UnimplementedClonrServiceServer) SaveDockerProfile(context.Context, *SaveDockerProfileRequest) (*SaveDockerProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveDockerProfile not implemented")
}
func (UnimplementedClonrServiceServer) GetDockerProfile(context.Context, *GetDockerProfileRequest) (*GetDockerProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDockerProfile not implemented")
}
func (UnimplementedClonrServiceServer) ListDockerProfiles(context.Context, *ListDockerProfilesRequest) (*ListDockerProfilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDockerProfiles not implemented")
}
func (UnimplementedClonrServiceServer) DeleteDockerProfile(context.Context, *DeleteDockerProfileRequest) (*DeleteDockerProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDockerProfile not implemented")
}
func (UnimplementedClonrServiceServer) DockerProfileExists(context.Context, *DockerProfileExistsRequest) (*DockerProfileExistsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DockerProfileExists not implemented")
}
func (UnimplementedClonrServiceServer) SaveWorkspace(context.Context, *SaveWorkspaceRequest) (*SaveWorkspaceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveWorkspace not implemented")
}
func (UnimplementedClonrServiceServer) GetWorkspace(context.Context, *GetWorkspaceRequest) (*GetWorkspaceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkspace not implemented")
}
func (UnimplementedClonrServiceServer) GetActiveWorkspace(context.Context, *GetActiveWorkspaceRequest) (*GetActiveWorkspaceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActiveWorkspace not implemented")
}
func (UnimplementedClonrServiceServer) SetActiveWorkspace(context.Context, *SetActiveWorkspaceRequest) (*SetActiveWorkspaceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetActiveWorkspace not implemented")
}
func (UnimplementedClonrServiceServer) ListWorkspaces(context.Context, *ListWorkspacesRequest) (*ListWorkspacesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWorkspaces not implemented")
}
func (UnimplementedClonrServiceServer) DeleteWorkspace(context.Context, *DeleteWorkspaceRequest) (*DeleteWorkspaceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteWorkspace not implemented")
}
func (UnimplementedClonrServiceServer) WorkspaceExists(context.Context, *WorkspaceExistsRequest) (*WorkspaceExistsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WorkspaceExists not implemented")
}
func (UnimplementedClonrServiceServer) GetReposByWorkspace(context.Context, *GetReposByWorkspaceRequest) (*GetReposByWorkspaceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetReposByWorkspace not implemented")
}
func (UnimplementedClonrServiceServer) UpdateRepoWorkspace(context.Context, *UpdateRepoWorkspaceRequest) (*UpdateRepoWorkspaceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRepoWorkspace not implemented")
}
func (UnimplementedClonrServiceServer) mustEmbedUnimplementedClonrServiceServer() {}
func (UnimplementedClonrServiceServer) testEmbeddedByValue()                      {}

// UnsafeClonrServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClonrServiceServer will
// result in compilation errors.
type UnsafeClonrServiceServer interface {
	mustEmbedUnimplementedClonrServiceServer()
}

func RegisterClonrServiceServer(s grpc.ServiceRegistrar, srv ClonrServiceServer) {
	// If the following call panics, it indicates UnimplementedClonrServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClonrService_ServiceDesc, srv)
}

func _ClonrService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClonrServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClonrService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClonrServiceServer).Ping(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClonrService_SaveRepo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveRepoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClonrServiceServer).SaveRepo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClonrService_SaveRepo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClonrServiceServer).SaveRepo(ctx, req.(*SaveRepoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClonrService_RepoExistsByURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepoExistsByURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClonrServiceServer).RepoExistsByURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClonrService_RepoExistsByURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClonrServiceServer).RepoExistsByURL(ctx, req.(*RepoExistsByURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClonrService_RepoExistsByPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepoExistsByPathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClonrServiceServer).RepoExistsByPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClonrService_RepoExistsByPath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClonrServiceServer).RepoExistsByPath(ctx, req.(*RepoExistsByPathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClonrService_InsertRepoIfNotExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertRepoIfNotExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClonrServiceServer).InsertRepoIfNotExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClonrService_InsertRepoIfNotExists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClonrServiceServer).InsertRepoIfNotExists(ctx, req.(*InsertRepoIfNotExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClonrService_GetAllRepos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllReposRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClonrServiceServer).GetAllRepos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClonrService_GetAllRepos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClonrServiceServer).GetAllRepos(ctx, req.(*GetAllReposRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClonrService_GetRepos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReposRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClonrServiceServer).GetRepos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClonrService_GetRepos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClonrServiceServer).GetRepos(ctx, req.(*GetReposRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClonrService_SetFavoriteByURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetFavoriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClonrServiceServer).SetFavoriteByURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClonrService_SetFavoriteByURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClonrServiceServer).SetFavoriteByURL(ctx, req.(*SetFavoriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClonrService_UpdateRepoTimestamp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRepoTimestampRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClonrServiceServer).UpdateRepoTimestamp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClonrService_UpdateRepoTimestamp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClonrServiceServer).UpdateRepoTimestamp(ctx, req.(*UpdateRepoTimestampRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClonrService_RemoveRepoByURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRepoByURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClonrServiceServer).RemoveRepoByURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClonrService_RemoveRepoByURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClonrServiceServer).RemoveRepoByURL(ctx, req.(*RemoveRepoByURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClonrService_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClonrServiceServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClonrService_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClonrServiceServer).GetConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClonrService_SaveConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClonrServiceServer).SaveConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClonrService_SaveConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClonrServiceServer).SaveConfig(ctx, req.(*SaveConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClonrService_SaveProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClonrServiceServer).SaveProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClonrService_SaveProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClonrServiceServer).SaveProfile(ctx, req.(*SaveProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClonrService_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClonrServiceServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClonrService_GetProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClonrServiceServer).GetProfile(ctx, req.(*GetProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClonrService_GetActiveProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActiveProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClonrServiceServer).GetActiveProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClonrService_GetActiveProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClonrServiceServer).GetActiveProfile(ctx, req.(*GetActiveProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClonrService_SetActiveProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetActiveProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClonrServiceServer).SetActiveProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClonrService_SetActiveProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClonrServiceServer).SetActiveProfile(ctx, req.(*SetActiveProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClonrService_ListProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProfilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClonrServiceServer).ListProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClonrService_ListProfiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClonrServiceServer).ListProfiles(ctx, req.(*ListProfilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClonrService_DeleteProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClonrServiceServer).DeleteProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClonrService_DeleteProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClonrServiceServer).DeleteProfile(ctx, req.(*DeleteProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClonrService_ProfileExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClonrServiceServer).ProfileExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClonrService_ProfileExists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClonrServiceServer).ProfileExists(ctx, req.(*ProfileExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClonrService_SaveDockerProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveDockerProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClonrServiceServer).SaveDockerProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClonrService_SaveDockerProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClonrServiceServer).SaveDockerProfile(ctx, req.(*SaveDockerProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClonrService_GetDockerProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDockerProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClonrServiceServer).GetDockerProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClonrService_GetDockerProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClonrServiceServer).GetDockerProfile(ctx, req.(*GetDockerProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClonrService_ListDockerProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDockerProfilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClonrServiceServer).ListDockerProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClonrService_ListDockerProfiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClonrServiceServer).ListDockerProfiles(ctx, req.(*ListDockerProfilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClonrService_DeleteDockerProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDockerProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClonrServiceServer).DeleteDockerProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClonrService_DeleteDockerProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClonrServiceServer).DeleteDockerProfile(ctx, req.(*DeleteDockerProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClonrService_DockerProfileExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DockerProfileExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClonrServiceServer).DockerProfileExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClonrService_DockerProfileExists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClonrServiceServer).DockerProfileExists(ctx, req.(*DockerProfileExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClonrService_SaveWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveWorkspaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClonrServiceServer).SaveWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClonrService_SaveWorkspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClonrServiceServer).SaveWorkspace(ctx, req.(*SaveWorkspaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClonrService_GetWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkspaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClonrServiceServer).GetWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClonrService_GetWorkspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClonrServiceServer).GetWorkspace(ctx, req.(*GetWorkspaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClonrService_GetActiveWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActiveWorkspaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClonrServiceServer).GetActiveWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClonrService_GetActiveWorkspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClonrServiceServer).GetActiveWorkspace(ctx, req.(*GetActiveWorkspaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClonrService_SetActiveWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetActiveWorkspaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClonrServiceServer).SetActiveWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClonrService_SetActiveWorkspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClonrServiceServer).SetActiveWorkspace(ctx, req.(*SetActiveWorkspaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClonrService_ListWorkspaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorkspacesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClonrServiceServer).ListWorkspaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClonrService_ListWorkspaces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClonrServiceServer).ListWorkspaces(ctx, req.(*ListWorkspacesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClonrService_DeleteWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWorkspaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClonrServiceServer).DeleteWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClonrService_DeleteWorkspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClonrServiceServer).DeleteWorkspace(ctx, req.(*DeleteWorkspaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClonrService_WorkspaceExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkspaceExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClonrServiceServer).WorkspaceExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClonrService_WorkspaceExists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClonrServiceServer).WorkspaceExists(ctx, req.(*WorkspaceExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClonrService_GetReposByWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReposByWorkspaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClonrServiceServer).GetReposByWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClonrService_GetReposByWorkspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClonrServiceServer).GetReposByWorkspace(ctx, req.(*GetReposByWorkspaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClonrService_UpdateRepoWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRepoWorkspaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClonrServiceServer).UpdateRepoWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClonrService_UpdateRepoWorkspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClonrServiceServer).UpdateRepoWorkspace(ctx, req.(*UpdateRepoWorkspaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClonrService_ServiceDesc is the grpc.ServiceDesc for ClonrService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClonrService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clonr.v1.ClonrService",
	HandlerType: (*ClonrServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _ClonrService_Ping_Handler,
		},
		{
			MethodName: "SaveRepo",
			Handler:    _ClonrService_SaveRepo_Handler,
		},
		{
			MethodName: "RepoExistsByURL",
			Handler:    _ClonrService_RepoExistsByURL_Handler,
		},
		{
			MethodName: "RepoExistsByPath",
			Handler:    _ClonrService_RepoExistsByPath_Handler,
		},
		{
			MethodName: "InsertRepoIfNotExists",
			Handler:    _ClonrService_InsertRepoIfNotExists_Handler,
		},
		{
			MethodName: "GetAllRepos",
			Handler:    _ClonrService_GetAllRepos_Handler,
		},
		{
			MethodName: "GetRepos",
			Handler:    _ClonrService_GetRepos_Handler,
		},
		{
			MethodName: "SetFavoriteByURL",
			Handler:    _ClonrService_SetFavoriteByURL_Handler,
		},
		{
			MethodName: "UpdateRepoTimestamp",
			Handler:    _ClonrService_UpdateRepoTimestamp_Handler,
		},
		{
			MethodName: "RemoveRepoByURL",
			Handler:    _ClonrService_RemoveRepoByURL_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _ClonrService_GetConfig_Handler,
		},
		{
			MethodName: "SaveConfig",
			Handler:    _ClonrService_SaveConfig_Handler,
		},
		{
			MethodName: "SaveProfile",
			Handler:    _ClonrService_SaveProfile_Handler,
		},
		{
			MethodName: "GetProfile",
			Handler:    _ClonrService_GetProfile_Handler,
		},
		{
			MethodName: "GetActiveProfile",
			Handler:    _ClonrService_GetActiveProfile_Handler,
		},
		{
			MethodName: "SetActiveProfile",
			Handler:    _ClonrService_SetActiveProfile_Handler,
		},
		{
			MethodName: "ListProfiles",
			Handler:    _ClonrService_ListProfiles_Handler,
		},
		{
			MethodName: "DeleteProfile",
			Handler:    _ClonrService_DeleteProfile_Handler,
		},
		{
			MethodName: "ProfileExists",
			Handler:    _ClonrService_ProfileExists_Handler,
		},
		{
			MethodName: "SaveDockerProfile",
			Handler:    _ClonrService_SaveDockerProfile_Handler,
		},
		{
			MethodName: "GetDockerProfile",
			Handler:    _ClonrService_GetDockerProfile_Handler,
		},
		{
			MethodName: "ListDockerProfiles",
			Handler:    _ClonrService_ListDockerProfiles_Handler,
		},
		{
			MethodName: "DeleteDockerProfile",
			Handler:    _ClonrService_DeleteDockerProfile_Handler,
		},
		{
			MethodName: "DockerProfileExists",
			Handler:    _ClonrService_DockerProfileExists_Handler,
		},
		{
			MethodName: "SaveWorkspace",
			Handler:    _ClonrService_SaveWorkspace_Handler,
		},
		{
			MethodName: "GetWorkspace",
			Handler:    _ClonrService_GetWorkspace_Handler,
		},
		{
			MethodName: "GetActiveWorkspace",
			Handler:    _ClonrService_GetActiveWorkspace_Handler,
		},
		{
			MethodName: "SetActiveWorkspace",
			Handler:    _ClonrService_SetActiveWorkspace_Handler,
		},
		{
			MethodName: "ListWorkspaces",
			Handler:    _ClonrService_ListWorkspaces_Handler,
		},
		{
			MethodName: "DeleteWorkspace",
			Handler:    _ClonrService_DeleteWorkspace_Handler,
		},
		{
			MethodName: "WorkspaceExists",
			Handler:    _ClonrService_WorkspaceExists_Handler,
		},
		{
			MethodName: "GetReposByWorkspace",
			Handler:    _ClonrService_GetReposByWorkspace_Handler,
		},
		{
			MethodName: "UpdateRepoWorkspace",
			Handler:    _ClonrService_UpdateRepoWorkspace_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/clonr.proto",
}
