// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/docker_profile.proto

package clonrv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DockerProfile represents container registry credentials
type DockerProfile struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Registry       string                 `protobuf:"bytes,2,opt,name=registry,proto3" json:"registry,omitempty"`
	Username       string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	EncryptedToken []byte                 `protobuf:"bytes,4,opt,name=encrypted_token,json=encryptedToken,proto3" json:"encrypted_token,omitempty"`
	TokenStorage   string                 `protobuf:"bytes,5,opt,name=token_storage,json=tokenStorage,proto3" json:"token_storage,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastUsedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DockerProfile) Reset() {
	*x = DockerProfile{}
	mi := &file_v1_docker_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DockerProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockerProfile) ProtoMessage() {}

func (x *DockerProfile) ProtoReflect() protoreflect.Message {
	mi := &file_v1_docker_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockerProfile.ProtoReflect.Descriptor instead.
func (*DockerProfile) Descriptor() ([]byte, []int) {
	return file_v1_docker_profile_proto_rawDescGZIP(), []int{0}
}

func (x *DockerProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DockerProfile) GetRegistry() string {
	if x != nil {
		return x.Registry
	}
	return ""
}

func (x *DockerProfile) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *DockerProfile) GetEncryptedToken() []byte {
	if x != nil {
		return x.EncryptedToken
	}
	return nil
}

func (x *DockerProfile) GetTokenStorage() string {
	if x != nil {
		return x.TokenStorage
	}
	return ""
}

func (x *DockerProfile) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DockerProfile) GetLastUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

// SaveDockerProfile RPC messages
type SaveDockerProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *DockerProfile         `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveDockerProfileRequest) Reset() {
	*x = SaveDockerProfileRequest{}
	mi := &file_v1_docker_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveDockerProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveDockerProfileRequest) ProtoMessage() {}

func (x *SaveDockerProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_docker_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveDockerProfileRequest.ProtoReflect.Descriptor instead.
func (*SaveDockerProfileRequest) Descriptor() ([]byte, []int) {
	return file_v1_docker_profile_proto_rawDescGZIP(), []int{1}
}

func (x *SaveDockerProfileRequest) GetProfile() *DockerProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type SaveDockerProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveDockerProfileResponse) Reset() {
	*x = SaveDockerProfileResponse{}
	mi := &file_v1_docker_profile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveDockerProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveDockerProfileResponse) ProtoMessage() {}

func (x *SaveDockerProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_docker_profile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveDockerProfileResponse.ProtoReflect.Descriptor instead.
func (*SaveDockerProfileResponse) Descriptor() ([]byte, []int) {
	return file_v1_docker_profile_proto_rawDescGZIP(), []int{2}
}

func (x *SaveDockerProfileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// GetDockerProfile RPC messages
type GetDockerProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDockerProfileRequest) Reset() {
	*x = GetDockerProfileRequest{}
	mi := &file_v1_docker_profile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDockerProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDockerProfileRequest) ProtoMessage() {}

func (x *GetDockerProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_docker_profile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDockerProfileRequest.ProtoReflect.Descriptor instead.
func (*GetDockerProfileRequest) Descriptor() ([]byte, []int) {
	return file_v1_docker_profile_proto_rawDescGZIP(), []int{3}
}

func (x *GetDockerProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetDockerProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *DockerProfile         `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDockerProfileResponse) Reset() {
	*x = GetDockerProfileResponse{}
	mi := &file_v1_docker_profile_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDockerProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDockerProfileResponse) ProtoMessage() {}

func (x *GetDockerProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_docker_profile_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDockerProfileResponse.ProtoReflect.Descriptor instead.
func (*GetDockerProfileResponse) Descriptor() ([]byte, []int) {
	return file_v1_docker_profile_proto_rawDescGZIP(), []int{4}
}

func (x *GetDockerProfileResponse) GetProfile() *DockerProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

// ListDockerProfiles RPC messages
type ListDockerProfilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDockerProfilesRequest) Reset() {
	*x = ListDockerProfilesRequest{}
	mi := &file_v1_docker_profile_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDockerProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDockerProfilesRequest) ProtoMessage() {}

func (x *ListDockerProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_docker_profile_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDockerProfilesRequest.ProtoReflect.Descriptor instead.
func (*ListDockerProfilesRequest) Descriptor() ([]byte, []int) {
	return file_v1_docker_profile_proto_rawDescGZIP(), []int{5}
}

type ListDockerProfilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profiles      []*DockerProfile       `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDockerProfilesResponse) Reset() {
	*x = ListDockerProfilesResponse{}
	mi := &file_v1_docker_profile_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDockerProfilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDockerProfilesResponse) ProtoMessage() {}

func (x *ListDockerProfilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_docker_profile_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDockerProfilesResponse.ProtoReflect.Descriptor instead.
func (*ListDockerProfilesResponse) Descriptor() ([]byte, []int) {
	return file_v1_docker_profile_proto_rawDescGZIP(), []int{6}
}

func (x *ListDockerProfilesResponse) GetProfiles() []*DockerProfile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

// DeleteDockerProfile RPC messages
type DeleteDockerProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDockerProfileRequest) Reset() {
	*x = DeleteDockerProfileRequest{}
	mi := &file_v1_docker_profile_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDockerProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDockerProfileRequest) ProtoMessage() {}

func (x *DeleteDockerProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_docker_profile_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDockerProfileRequest.ProtoReflect.Descriptor instead.
func (*DeleteDockerProfileRequest) Descriptor() ([]byte, []int) {
	return file_v1_docker_profile_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteDockerProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteDockerProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDockerProfileResponse) Reset() {
	*x = DeleteDockerProfileResponse{}
	mi := &file_v1_docker_profile_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDockerProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDockerProfileResponse) ProtoMessage() {}

func (x *DeleteDockerProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_docker_profile_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDockerProfileResponse.ProtoReflect.Descriptor instead.
func (*DeleteDockerProfileResponse) Descriptor() ([]byte, []int) {
	return file_v1_docker_profile_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteDockerProfileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// DockerProfileExists RPC messages
type DockerProfileExistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DockerProfileExistsRequest) Reset() {
	*x = DockerProfileExistsRequest{}
	mi := &file_v1_docker_profile_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DockerProfileExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockerProfileExistsRequest) ProtoMessage() {}

func (x *DockerProfileExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_docker_profile_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockerProfileExistsRequest.ProtoReflect.Descriptor instead.
func (*DockerProfileExistsRequest) Descriptor() ([]byte, []int) {
	return file_v1_docker_profile_proto_rawDescGZIP(), []int{9}
}

func (x *DockerProfileExistsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DockerProfileExistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DockerProfileExistsResponse) Reset() {
	*x = DockerProfileExistsResponse{}
	mi := &file_v1_docker_profile_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DockerProfileExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockerProfileExistsResponse) ProtoMessage() {}

func (x *DockerProfileExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_docker_profile_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockerProfileExistsResponse.ProtoReflect.Descriptor instead.
func (*DockerProfileExistsResponse) Descriptor() ([]byte, []int) {
	return file_v1_docker_profile_proto_rawDescGZIP(), []int{10}
}

func (x *DockerProfileExistsResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

var File_v1_docker_profile_proto protoreflect.FileDescriptor

const file_v1_docker_profile_proto_rawDesc = "" +
	"\n" +
	"\x17v1/docker_profile.proto\x12\bclonr.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa2\x02\n" +
	"\rDockerProfile\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bregistry\x18\x02 \x01(\tR\bregistry\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12'\n" +
	"\x0fencrypted_token\x18\x04 \x01(\fR\x0eencryptedToken\x12#\n" +
	"\rtoken_storage\x18\x05 \x01(\tR\ftokenStorage\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12<\n" +
	"\flast_used_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUsedAt\"M\n" +
	"\x18SaveDockerProfileRequest\x121\n" +
	"\aprofile\x18\x01 \x01(\v2\x17.clonr.v1.DockerProfileR\aprofile\"5\n" +
	"\x19SaveDockerProfileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"-\n" +
	"\x17GetDockerProfileRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"M\n" +
	"\x18GetDockerProfileResponse\x121\n" +
	"\aprofile\x18\x01 \x01(\v2\x17.clonr.v1.DockerProfileR\aprofile\"\x1b\n" +
	"\x19ListDockerProfilesRequest\"Q\n" +
	"\x1aListDockerProfilesResponse\x123\n" +
	"\bprofiles\x18\x01 \x03(\v2\x17.clonr.v1.DockerProfileR\bprofiles\"0\n" +
	"\x1aDeleteDockerProfileRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"7\n" +
	"\x1bDeleteDockerProfileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"0\n" +
	"\x1aDockerProfileExistsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"5\n" +
	"\x1bDockerProfileExistsResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06existsB\x95\x01\n" +
	"\fcom.clonr.v1B\x12DockerProfileProtoP\x01Z0github.com/inovacc/clonr/internal/api/v1;clonrv1\xa2\x02\x03CXX\xaa\x02\bClonr.V1\xca\x02\bClonr\\V1\xe2\x02\x14Clonr\\V1\\GPBMetadata\xea\x02\tClonr::V1b\x06proto3"

var (
	file_v1_docker_profile_proto_rawDescOnce sync.Once
	file_v1_docker_profile_proto_rawDescData []byte
)

func file_v1_docker_profile_proto_rawDescGZIP() []byte {
	file_v1_docker_profile_proto_rawDescOnce.Do(func() {
		file_v1_docker_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_docker_profile_proto_rawDesc), len(file_v1_docker_profile_proto_rawDesc)))
	})
	return file_v1_docker_profile_proto_rawDescData
}

var file_v1_docker_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_v1_docker_profile_proto_goTypes = []any{
	(*DockerProfile)(nil),               // 0: clonr.v1.DockerProfile
	(*SaveDockerProfileRequest)(nil),    // 1: clonr.v1.SaveDockerProfileRequest
	(*SaveDockerProfileResponse)(nil),   // 2: clonr.v1.SaveDockerProfileResponse
	(*GetDockerProfileRequest)(nil),     // 3: clonr.v1.GetDockerProfileRequest
	(*GetDockerProfileResponse)(nil),    // 4: clonr.v1.GetDockerProfileResponse
	(*ListDockerProfilesRequest)(nil),   // 5: clonr.v1.ListDockerProfilesRequest
	(*ListDockerProfilesResponse)(nil),  // 6: clonr.v1.ListDockerProfilesResponse
	(*DeleteDockerProfileRequest)(nil),  // 7: clonr.v1.DeleteDockerProfileRequest
	(*DeleteDockerProfileResponse)(nil), // 8: clonr.v1.DeleteDockerProfileResponse
	(*DockerProfileExistsRequest)(nil),  // 9: clonr.v1.DockerProfileExistsRequest
	(*DockerProfileExistsResponse)(nil), // 10: clonr.v1.DockerProfileExistsResponse
	(*timestamppb.Timestamp)(nil),       // 11: google.protobuf.Timestamp
}
var file_v1_docker_profile_proto_depIdxs = []int32{
	11, // 0: clonr.v1.DockerProfile.created_at:type_name -> google.protobuf.Timestamp
	11, // 1: clonr.v1.DockerProfile.last_used_at:type_name -> google.protobuf.Timestamp
	0,  // 2: clonr.v1.SaveDockerProfileRequest.profile:type_name -> clonr.v1.DockerProfile
	0,  // 3: clonr.v1.GetDockerProfileResponse.profile:type_name -> clonr.v1.DockerProfile
	0,  // 4: clonr.v1.ListDockerProfilesResponse.profiles:type_name -> clonr.v1.DockerProfile
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_v1_docker_profile_proto_init() }
func file_v1_docker_profile_proto_init() {
	if File_v1_docker_profile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_docker_profile_proto_rawDesc), len(file_v1_docker_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_docker_profile_proto_goTypes,
		DependencyIndexes: file_v1_docker_profile_proto_depIdxs,
		MessageInfos:      file_v1_docker_profile_proto_msgTypes,
	}.Build()
	File_v1_docker_profile_proto = out.File
	file_v1_docker_profile_proto_goTypes = nil
	file_v1_docker_profile_proto_depIdxs = nil
}
