// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/profile.proto

package clonrv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Profile represents a GitHub authentication profile
type Profile struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Host           string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	User           string                 `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	TokenStorage   string                 `protobuf:"bytes,4,opt,name=token_storage,json=tokenStorage,proto3" json:"token_storage,omitempty"`
	Scopes         []string               `protobuf:"bytes,5,rep,name=scopes,proto3" json:"scopes,omitempty"`
	Active         bool                   `protobuf:"varint,6,opt,name=active,proto3" json:"active,omitempty"`
	EncryptedToken []byte                 `protobuf:"bytes,7,opt,name=encrypted_token,json=encryptedToken,proto3" json:"encrypted_token,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastUsedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	Workspace      string                 `protobuf:"bytes,10,opt,name=workspace,proto3" json:"workspace,omitempty"` // Associated workspace name
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_v1_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_v1_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_v1_profile_proto_rawDescGZIP(), []int{0}
}

func (x *Profile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Profile) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Profile) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Profile) GetTokenStorage() string {
	if x != nil {
		return x.TokenStorage
	}
	return ""
}

func (x *Profile) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *Profile) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Profile) GetEncryptedToken() []byte {
	if x != nil {
		return x.EncryptedToken
	}
	return nil
}

func (x *Profile) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Profile) GetLastUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

func (x *Profile) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

// SaveProfile RPC messages
type SaveProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *Profile               `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveProfileRequest) Reset() {
	*x = SaveProfileRequest{}
	mi := &file_v1_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveProfileRequest) ProtoMessage() {}

func (x *SaveProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveProfileRequest.ProtoReflect.Descriptor instead.
func (*SaveProfileRequest) Descriptor() ([]byte, []int) {
	return file_v1_profile_proto_rawDescGZIP(), []int{1}
}

func (x *SaveProfileRequest) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type SaveProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveProfileResponse) Reset() {
	*x = SaveProfileResponse{}
	mi := &file_v1_profile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveProfileResponse) ProtoMessage() {}

func (x *SaveProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_profile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveProfileResponse.ProtoReflect.Descriptor instead.
func (*SaveProfileResponse) Descriptor() ([]byte, []int) {
	return file_v1_profile_proto_rawDescGZIP(), []int{2}
}

func (x *SaveProfileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// GetProfile RPC messages
type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_v1_profile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_profile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_v1_profile_proto_rawDescGZIP(), []int{3}
}

func (x *GetProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *Profile               `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileResponse) Reset() {
	*x = GetProfileResponse{}
	mi := &file_v1_profile_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileResponse) ProtoMessage() {}

func (x *GetProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_profile_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileResponse.ProtoReflect.Descriptor instead.
func (*GetProfileResponse) Descriptor() ([]byte, []int) {
	return file_v1_profile_proto_rawDescGZIP(), []int{4}
}

func (x *GetProfileResponse) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

// GetActiveProfile RPC messages
type GetActiveProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveProfileRequest) Reset() {
	*x = GetActiveProfileRequest{}
	mi := &file_v1_profile_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveProfileRequest) ProtoMessage() {}

func (x *GetActiveProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_profile_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveProfileRequest.ProtoReflect.Descriptor instead.
func (*GetActiveProfileRequest) Descriptor() ([]byte, []int) {
	return file_v1_profile_proto_rawDescGZIP(), []int{5}
}

type GetActiveProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *Profile               `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveProfileResponse) Reset() {
	*x = GetActiveProfileResponse{}
	mi := &file_v1_profile_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveProfileResponse) ProtoMessage() {}

func (x *GetActiveProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_profile_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveProfileResponse.ProtoReflect.Descriptor instead.
func (*GetActiveProfileResponse) Descriptor() ([]byte, []int) {
	return file_v1_profile_proto_rawDescGZIP(), []int{6}
}

func (x *GetActiveProfileResponse) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

// SetActiveProfile RPC messages
type SetActiveProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetActiveProfileRequest) Reset() {
	*x = SetActiveProfileRequest{}
	mi := &file_v1_profile_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetActiveProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetActiveProfileRequest) ProtoMessage() {}

func (x *SetActiveProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_profile_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetActiveProfileRequest.ProtoReflect.Descriptor instead.
func (*SetActiveProfileRequest) Descriptor() ([]byte, []int) {
	return file_v1_profile_proto_rawDescGZIP(), []int{7}
}

func (x *SetActiveProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SetActiveProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetActiveProfileResponse) Reset() {
	*x = SetActiveProfileResponse{}
	mi := &file_v1_profile_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetActiveProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetActiveProfileResponse) ProtoMessage() {}

func (x *SetActiveProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_profile_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetActiveProfileResponse.ProtoReflect.Descriptor instead.
func (*SetActiveProfileResponse) Descriptor() ([]byte, []int) {
	return file_v1_profile_proto_rawDescGZIP(), []int{8}
}

func (x *SetActiveProfileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// ListProfiles RPC messages
type ListProfilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProfilesRequest) Reset() {
	*x = ListProfilesRequest{}
	mi := &file_v1_profile_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProfilesRequest) ProtoMessage() {}

func (x *ListProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_profile_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProfilesRequest.ProtoReflect.Descriptor instead.
func (*ListProfilesRequest) Descriptor() ([]byte, []int) {
	return file_v1_profile_proto_rawDescGZIP(), []int{9}
}

type ListProfilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profiles      []*Profile             `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProfilesResponse) Reset() {
	*x = ListProfilesResponse{}
	mi := &file_v1_profile_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProfilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProfilesResponse) ProtoMessage() {}

func (x *ListProfilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_profile_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProfilesResponse.ProtoReflect.Descriptor instead.
func (*ListProfilesResponse) Descriptor() ([]byte, []int) {
	return file_v1_profile_proto_rawDescGZIP(), []int{10}
}

func (x *ListProfilesResponse) GetProfiles() []*Profile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

// DeleteProfile RPC messages
type DeleteProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProfileRequest) Reset() {
	*x = DeleteProfileRequest{}
	mi := &file_v1_profile_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProfileRequest) ProtoMessage() {}

func (x *DeleteProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_profile_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProfileRequest.ProtoReflect.Descriptor instead.
func (*DeleteProfileRequest) Descriptor() ([]byte, []int) {
	return file_v1_profile_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProfileResponse) Reset() {
	*x = DeleteProfileResponse{}
	mi := &file_v1_profile_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProfileResponse) ProtoMessage() {}

func (x *DeleteProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_profile_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProfileResponse.ProtoReflect.Descriptor instead.
func (*DeleteProfileResponse) Descriptor() ([]byte, []int) {
	return file_v1_profile_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteProfileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// ProfileExists RPC messages
type ProfileExistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileExistsRequest) Reset() {
	*x = ProfileExistsRequest{}
	mi := &file_v1_profile_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileExistsRequest) ProtoMessage() {}

func (x *ProfileExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_profile_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileExistsRequest.ProtoReflect.Descriptor instead.
func (*ProfileExistsRequest) Descriptor() ([]byte, []int) {
	return file_v1_profile_proto_rawDescGZIP(), []int{13}
}

func (x *ProfileExistsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ProfileExistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileExistsResponse) Reset() {
	*x = ProfileExistsResponse{}
	mi := &file_v1_profile_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileExistsResponse) ProtoMessage() {}

func (x *ProfileExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_profile_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileExistsResponse.ProtoReflect.Descriptor instead.
func (*ProfileExistsResponse) Descriptor() ([]byte, []int) {
	return file_v1_profile_proto_rawDescGZIP(), []int{14}
}

func (x *ProfileExistsResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

var File_v1_profile_proto protoreflect.FileDescriptor

const file_v1_profile_proto_rawDesc = "" +
	"\n" +
	"\x10v1/profile.proto\x12\bclonr.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xda\x02\n" +
	"\aProfile\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\x12#\n" +
	"\rtoken_storage\x18\x04 \x01(\tR\ftokenStorage\x12\x16\n" +
	"\x06scopes\x18\x05 \x03(\tR\x06scopes\x12\x16\n" +
	"\x06active\x18\x06 \x01(\bR\x06active\x12'\n" +
	"\x0fencrypted_token\x18\a \x01(\fR\x0eencryptedToken\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12<\n" +
	"\flast_used_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUsedAt\x12\x1c\n" +
	"\tworkspace\x18\n" +
	" \x01(\tR\tworkspace\"A\n" +
	"\x12SaveProfileRequest\x12+\n" +
	"\aprofile\x18\x01 \x01(\v2\x11.clonr.v1.ProfileR\aprofile\"/\n" +
	"\x13SaveProfileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"'\n" +
	"\x11GetProfileRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"A\n" +
	"\x12GetProfileResponse\x12+\n" +
	"\aprofile\x18\x01 \x01(\v2\x11.clonr.v1.ProfileR\aprofile\"\x19\n" +
	"\x17GetActiveProfileRequest\"G\n" +
	"\x18GetActiveProfileResponse\x12+\n" +
	"\aprofile\x18\x01 \x01(\v2\x11.clonr.v1.ProfileR\aprofile\"-\n" +
	"\x17SetActiveProfileRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"4\n" +
	"\x18SetActiveProfileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x15\n" +
	"\x13ListProfilesRequest\"E\n" +
	"\x14ListProfilesResponse\x12-\n" +
	"\bprofiles\x18\x01 \x03(\v2\x11.clonr.v1.ProfileR\bprofiles\"*\n" +
	"\x14DeleteProfileRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"1\n" +
	"\x15DeleteProfileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"*\n" +
	"\x14ProfileExistsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"/\n" +
	"\x15ProfileExistsResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06existsB\x8f\x01\n" +
	"\fcom.clonr.v1B\fProfileProtoP\x01Z0github.com/inovacc/clonr/internal/api/v1;clonrv1\xa2\x02\x03CXX\xaa\x02\bClonr.V1\xca\x02\bClonr\\V1\xe2\x02\x14Clonr\\V1\\GPBMetadata\xea\x02\tClonr::V1b\x06proto3"

var (
	file_v1_profile_proto_rawDescOnce sync.Once
	file_v1_profile_proto_rawDescData []byte
)

func file_v1_profile_proto_rawDescGZIP() []byte {
	file_v1_profile_proto_rawDescOnce.Do(func() {
		file_v1_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_profile_proto_rawDesc), len(file_v1_profile_proto_rawDesc)))
	})
	return file_v1_profile_proto_rawDescData
}

var file_v1_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_v1_profile_proto_goTypes = []any{
	(*Profile)(nil),                  // 0: clonr.v1.Profile
	(*SaveProfileRequest)(nil),       // 1: clonr.v1.SaveProfileRequest
	(*SaveProfileResponse)(nil),      // 2: clonr.v1.SaveProfileResponse
	(*GetProfileRequest)(nil),        // 3: clonr.v1.GetProfileRequest
	(*GetProfileResponse)(nil),       // 4: clonr.v1.GetProfileResponse
	(*GetActiveProfileRequest)(nil),  // 5: clonr.v1.GetActiveProfileRequest
	(*GetActiveProfileResponse)(nil), // 6: clonr.v1.GetActiveProfileResponse
	(*SetActiveProfileRequest)(nil),  // 7: clonr.v1.SetActiveProfileRequest
	(*SetActiveProfileResponse)(nil), // 8: clonr.v1.SetActiveProfileResponse
	(*ListProfilesRequest)(nil),      // 9: clonr.v1.ListProfilesRequest
	(*ListProfilesResponse)(nil),     // 10: clonr.v1.ListProfilesResponse
	(*DeleteProfileRequest)(nil),     // 11: clonr.v1.DeleteProfileRequest
	(*DeleteProfileResponse)(nil),    // 12: clonr.v1.DeleteProfileResponse
	(*ProfileExistsRequest)(nil),     // 13: clonr.v1.ProfileExistsRequest
	(*ProfileExistsResponse)(nil),    // 14: clonr.v1.ProfileExistsResponse
	(*timestamppb.Timestamp)(nil),    // 15: google.protobuf.Timestamp
}
var file_v1_profile_proto_depIdxs = []int32{
	15, // 0: clonr.v1.Profile.created_at:type_name -> google.protobuf.Timestamp
	15, // 1: clonr.v1.Profile.last_used_at:type_name -> google.protobuf.Timestamp
	0,  // 2: clonr.v1.SaveProfileRequest.profile:type_name -> clonr.v1.Profile
	0,  // 3: clonr.v1.GetProfileResponse.profile:type_name -> clonr.v1.Profile
	0,  // 4: clonr.v1.GetActiveProfileResponse.profile:type_name -> clonr.v1.Profile
	0,  // 5: clonr.v1.ListProfilesResponse.profiles:type_name -> clonr.v1.Profile
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_v1_profile_proto_init() }
func file_v1_profile_proto_init() {
	if File_v1_profile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_profile_proto_rawDesc), len(file_v1_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_profile_proto_goTypes,
		DependencyIndexes: file_v1_profile_proto_depIdxs,
		MessageInfos:      file_v1_profile_proto_msgTypes,
	}.Build()
	File_v1_profile_proto = out.File
	file_v1_profile_proto_goTypes = nil
	file_v1_profile_proto_depIdxs = nil
}
