// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/standalone.proto

package clonrv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AuthenticateRequest is sent by the destination to authenticate with the source.
type AuthenticateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`             // Base58-encoded API key from standalone key
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`       // Unique ID of the destination instance
	ClientName    string                 `protobuf:"bytes,3,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"` // Human-readable name of the destination
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateRequest) Reset() {
	*x = AuthenticateRequest{}
	mi := &file_v1_standalone_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateRequest) ProtoMessage() {}

func (x *AuthenticateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_standalone_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return file_v1_standalone_proto_rawDescGZIP(), []int{0}
}

func (x *AuthenticateRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *AuthenticateRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *AuthenticateRequest) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

// AuthenticateResponse contains the session token for subsequent requests.
type AuthenticateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	SessionToken  string                 `protobuf:"bytes,2,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"` // JWT or similar session token
	ExpiresAt     int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`         // Unix timestamp when token expires
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`                                   // Error message if success is false
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateResponse) Reset() {
	*x = AuthenticateResponse{}
	mi := &file_v1_standalone_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateResponse) ProtoMessage() {}

func (x *AuthenticateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_standalone_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateResponse.ProtoReflect.Descriptor instead.
func (*AuthenticateResponse) Descriptor() ([]byte, []int) {
	return file_v1_standalone_proto_rawDescGZIP(), []int{1}
}

func (x *AuthenticateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AuthenticateResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *AuthenticateResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *AuthenticateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// RefreshTokenRequest is used to refresh an expiring session.
type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"` // The refresh token from standalone key
	SessionToken  string                 `protobuf:"bytes,2,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"` // Current session token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_v1_standalone_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_standalone_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_v1_standalone_proto_rawDescGZIP(), []int{2}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshTokenRequest) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

// RefreshTokenResponse contains the new session token.
type RefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	SessionToken  string                 `protobuf:"bytes,2,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_v1_standalone_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_standalone_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_v1_standalone_proto_rawDescGZIP(), []int{3}
}

func (x *RefreshTokenResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RefreshTokenResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *RefreshTokenResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *RefreshTokenResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// PingResponse provides basic connectivity info.
type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	ServerTime    int64                  `protobuf:"varint,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"` // Unix timestamp
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`                          // Server version
	Capabilities  []string               `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`                // Supported capabilities
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_v1_standalone_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_standalone_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_v1_standalone_proto_rawDescGZIP(), []int{4}
}

func (x *PingResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *PingResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *PingResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PingResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// GetStatusRequest retrieves sync status.
type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionToken  string                 `protobuf:"bytes,1,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_v1_standalone_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_standalone_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_v1_standalone_proto_rawDescGZIP(), []int{5}
}

func (x *GetStatusRequest) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

// GetStatusResponse provides current sync status.
type GetStatusResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	InstanceId        string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	StandaloneEnabled bool                   `protobuf:"varint,2,opt,name=standalone_enabled,json=standaloneEnabled,proto3" json:"standalone_enabled,omitempty"`
	LastSync          int64                  `protobuf:"varint,3,opt,name=last_sync,json=lastSync,proto3" json:"last_sync,omitempty"` // Unix timestamp of last sync
	Stats             *SyncStats             `protobuf:"bytes,4,opt,name=stats,proto3" json:"stats,omitempty"`
	Clients           []*ConnectedClient     `protobuf:"bytes,5,rep,name=clients,proto3" json:"clients,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_v1_standalone_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_standalone_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_v1_standalone_proto_rawDescGZIP(), []int{6}
}

func (x *GetStatusResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *GetStatusResponse) GetStandaloneEnabled() bool {
	if x != nil {
		return x.StandaloneEnabled
	}
	return false
}

func (x *GetStatusResponse) GetLastSync() int64 {
	if x != nil {
		return x.LastSync
	}
	return 0
}

func (x *GetStatusResponse) GetStats() *SyncStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *GetStatusResponse) GetClients() []*ConnectedClient {
	if x != nil {
		return x.Clients
	}
	return nil
}

// SyncStats tracks sync statistics.
type SyncStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profiles      int32                  `protobuf:"varint,1,opt,name=profiles,proto3" json:"profiles,omitempty"`
	Workspaces    int32                  `protobuf:"varint,2,opt,name=workspaces,proto3" json:"workspaces,omitempty"`
	Repos         int32                  `protobuf:"varint,3,opt,name=repos,proto3" json:"repos,omitempty"`
	Config        bool                   `protobuf:"varint,4,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncStats) Reset() {
	*x = SyncStats{}
	mi := &file_v1_standalone_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncStats) ProtoMessage() {}

func (x *SyncStats) ProtoReflect() protoreflect.Message {
	mi := &file_v1_standalone_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncStats.ProtoReflect.Descriptor instead.
func (*SyncStats) Descriptor() ([]byte, []int) {
	return file_v1_standalone_proto_rawDescGZIP(), []int{7}
}

func (x *SyncStats) GetProfiles() int32 {
	if x != nil {
		return x.Profiles
	}
	return 0
}

func (x *SyncStats) GetWorkspaces() int32 {
	if x != nil {
		return x.Workspaces
	}
	return 0
}

func (x *SyncStats) GetRepos() int32 {
	if x != nil {
		return x.Repos
	}
	return 0
}

func (x *SyncStats) GetConfig() bool {
	if x != nil {
		return x.Config
	}
	return false
}

// ConnectedClient represents a connected destination instance.
type ConnectedClient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IpAddress     string                 `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	ConnectedAt   int64                  `protobuf:"varint,4,opt,name=connected_at,json=connectedAt,proto3" json:"connected_at,omitempty"`
	LastSeen      int64                  `protobuf:"varint,5,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	SyncCount     int32                  `protobuf:"varint,6,opt,name=sync_count,json=syncCount,proto3" json:"sync_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectedClient) Reset() {
	*x = ConnectedClient{}
	mi := &file_v1_standalone_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectedClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectedClient) ProtoMessage() {}

func (x *ConnectedClient) ProtoReflect() protoreflect.Message {
	mi := &file_v1_standalone_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectedClient.ProtoReflect.Descriptor instead.
func (*ConnectedClient) Descriptor() ([]byte, []int) {
	return file_v1_standalone_proto_rawDescGZIP(), []int{8}
}

func (x *ConnectedClient) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConnectedClient) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConnectedClient) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *ConnectedClient) GetConnectedAt() int64 {
	if x != nil {
		return x.ConnectedAt
	}
	return 0
}

func (x *ConnectedClient) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

func (x *ConnectedClient) GetSyncCount() int32 {
	if x != nil {
		return x.SyncCount
	}
	return 0
}

// SyncRequest is the base request for sync operations.
type SyncRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionToken   string                 `protobuf:"bytes,1,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	SinceTimestamp int64                  `protobuf:"varint,2,opt,name=since_timestamp,json=sinceTimestamp,proto3" json:"since_timestamp,omitempty"` // For incremental sync (0 = full sync)
	ItemTypes      []string               `protobuf:"bytes,3,rep,name=item_types,json=itemTypes,proto3" json:"item_types,omitempty"`                 // Filter: ["profiles", "workspaces", "repos", "config"]
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_v1_standalone_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_standalone_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_v1_standalone_proto_rawDescGZIP(), []int{9}
}

func (x *SyncRequest) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *SyncRequest) GetSinceTimestamp() int64 {
	if x != nil {
		return x.SinceTimestamp
	}
	return 0
}

func (x *SyncRequest) GetItemTypes() []string {
	if x != nil {
		return x.ItemTypes
	}
	return nil
}

// EncryptedData represents a single encrypted item.
type EncryptedData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                            // Item identifier
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`                                        // "profile", "workspace", "repo", "config"
	EncryptedData []byte                 `protobuf:"bytes,3,opt,name=encrypted_data,json=encryptedData,proto3" json:"encrypted_data,omitempty"` // AES-256-GCM encrypted JSON
	Nonce         []byte                 `protobuf:"bytes,4,opt,name=nonce,proto3" json:"nonce,omitempty"`                                      // GCM nonce
	UpdatedAt     int64                  `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`            // Unix timestamp of last update
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptedData) Reset() {
	*x = EncryptedData{}
	mi := &file_v1_standalone_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedData) ProtoMessage() {}

func (x *EncryptedData) ProtoReflect() protoreflect.Message {
	mi := &file_v1_standalone_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedData.ProtoReflect.Descriptor instead.
func (*EncryptedData) Descriptor() ([]byte, []int) {
	return file_v1_standalone_proto_rawDescGZIP(), []int{10}
}

func (x *EncryptedData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EncryptedData) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EncryptedData) GetEncryptedData() []byte {
	if x != nil {
		return x.EncryptedData
	}
	return nil
}

func (x *EncryptedData) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *EncryptedData) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// SyncChunk is used for streaming full sync data.
type SyncChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "profile", "workspace", "repo", "config"
	EncryptedData []byte                 `protobuf:"bytes,2,opt,name=encrypted_data,json=encryptedData,proto3" json:"encrypted_data,omitempty"`
	Nonce         []byte                 `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Sequence      int32                  `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"` // Chunk sequence number
	Total         int32                  `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty"`       // Total chunks expected
	Id            string                 `protobuf:"bytes,6,opt,name=id,proto3" json:"id,omitempty"`              // Item identifier
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncChunk) Reset() {
	*x = SyncChunk{}
	mi := &file_v1_standalone_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncChunk) ProtoMessage() {}

func (x *SyncChunk) ProtoReflect() protoreflect.Message {
	mi := &file_v1_standalone_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncChunk.ProtoReflect.Descriptor instead.
func (*SyncChunk) Descriptor() ([]byte, []int) {
	return file_v1_standalone_proto_rawDescGZIP(), []int{11}
}

func (x *SyncChunk) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SyncChunk) GetEncryptedData() []byte {
	if x != nil {
		return x.EncryptedData
	}
	return nil
}

func (x *SyncChunk) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *SyncChunk) GetSequence() int32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *SyncChunk) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SyncChunk) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// StandaloneKey represents the key shared between instances.
// This is not transmitted over gRPC but used for initial setup.
type StandaloneKey struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Version           int32                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	InstanceId        string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Host              string                 `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Port              int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	ApiKey            string                 `protobuf:"bytes,5,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`                                    // Base58-encoded
	RefreshToken      string                 `protobuf:"bytes,6,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`                  // Base58-encoded
	EncryptionKeyHint string                 `protobuf:"bytes,7,opt,name=encryption_key_hint,json=encryptionKeyHint,proto3" json:"encryption_key_hint,omitempty"` // For verification
	ExpiresAt         int64                  `protobuf:"varint,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`                          // Unix timestamp
	CreatedAt         int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                          // Unix timestamp
	Capabilities      []string               `protobuf:"bytes,10,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StandaloneKey) Reset() {
	*x = StandaloneKey{}
	mi := &file_v1_standalone_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StandaloneKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StandaloneKey) ProtoMessage() {}

func (x *StandaloneKey) ProtoReflect() protoreflect.Message {
	mi := &file_v1_standalone_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StandaloneKey.ProtoReflect.Descriptor instead.
func (*StandaloneKey) Descriptor() ([]byte, []int) {
	return file_v1_standalone_proto_rawDescGZIP(), []int{12}
}

func (x *StandaloneKey) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *StandaloneKey) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *StandaloneKey) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *StandaloneKey) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *StandaloneKey) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *StandaloneKey) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *StandaloneKey) GetEncryptionKeyHint() string {
	if x != nil {
		return x.EncryptionKeyHint
	}
	return ""
}

func (x *StandaloneKey) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *StandaloneKey) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *StandaloneKey) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// StandaloneConfig represents the source instance configuration.
type StandaloneConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	InstanceId    string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	ApiKeyHash    []byte                 `protobuf:"bytes,4,opt,name=api_key_hash,json=apiKeyHash,proto3" json:"api_key_hash,omitempty"`
	RefreshToken  []byte                 `protobuf:"bytes,5,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	Salt          []byte                 `protobuf:"bytes,6,opt,name=salt,proto3" json:"salt,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Capabilities  []string               `protobuf:"bytes,9,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StandaloneConfig) Reset() {
	*x = StandaloneConfig{}
	mi := &file_v1_standalone_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StandaloneConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StandaloneConfig) ProtoMessage() {}

func (x *StandaloneConfig) ProtoReflect() protoreflect.Message {
	mi := &file_v1_standalone_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StandaloneConfig.ProtoReflect.Descriptor instead.
func (*StandaloneConfig) Descriptor() ([]byte, []int) {
	return file_v1_standalone_proto_rawDescGZIP(), []int{13}
}

func (x *StandaloneConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *StandaloneConfig) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *StandaloneConfig) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *StandaloneConfig) GetApiKeyHash() []byte {
	if x != nil {
		return x.ApiKeyHash
	}
	return nil
}

func (x *StandaloneConfig) GetRefreshToken() []byte {
	if x != nil {
		return x.RefreshToken
	}
	return nil
}

func (x *StandaloneConfig) GetSalt() []byte {
	if x != nil {
		return x.Salt
	}
	return nil
}

func (x *StandaloneConfig) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *StandaloneConfig) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *StandaloneConfig) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// StandaloneConnection represents a connection at the destination.
type StandaloneConnection struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Name                  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	InstanceId            string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Host                  string                 `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Port                  int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	ApiKeyEncrypted       []byte                 `protobuf:"bytes,5,opt,name=api_key_encrypted,json=apiKeyEncrypted,proto3" json:"api_key_encrypted,omitempty"`
	RefreshTokenEncrypted []byte                 `protobuf:"bytes,6,opt,name=refresh_token_encrypted,json=refreshTokenEncrypted,proto3" json:"refresh_token_encrypted,omitempty"`
	LocalPasswordHash     []byte                 `protobuf:"bytes,7,opt,name=local_password_hash,json=localPasswordHash,proto3" json:"local_password_hash,omitempty"`
	LocalSalt             []byte                 `protobuf:"bytes,8,opt,name=local_salt,json=localSalt,proto3" json:"local_salt,omitempty"`
	LastSync              int64                  `protobuf:"varint,9,opt,name=last_sync,json=lastSync,proto3" json:"last_sync,omitempty"`
	SyncStatus            string                 `protobuf:"bytes,10,opt,name=sync_status,json=syncStatus,proto3" json:"sync_status,omitempty"`
	SyncedItems           *SyncStats             `protobuf:"bytes,11,opt,name=synced_items,json=syncedItems,proto3" json:"synced_items,omitempty"`
	CreatedAt             int64                  `protobuf:"varint,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt             int64                  `protobuf:"varint,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *StandaloneConnection) Reset() {
	*x = StandaloneConnection{}
	mi := &file_v1_standalone_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StandaloneConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StandaloneConnection) ProtoMessage() {}

func (x *StandaloneConnection) ProtoReflect() protoreflect.Message {
	mi := &file_v1_standalone_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StandaloneConnection.ProtoReflect.Descriptor instead.
func (*StandaloneConnection) Descriptor() ([]byte, []int) {
	return file_v1_standalone_proto_rawDescGZIP(), []int{14}
}

func (x *StandaloneConnection) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StandaloneConnection) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *StandaloneConnection) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *StandaloneConnection) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *StandaloneConnection) GetApiKeyEncrypted() []byte {
	if x != nil {
		return x.ApiKeyEncrypted
	}
	return nil
}

func (x *StandaloneConnection) GetRefreshTokenEncrypted() []byte {
	if x != nil {
		return x.RefreshTokenEncrypted
	}
	return nil
}

func (x *StandaloneConnection) GetLocalPasswordHash() []byte {
	if x != nil {
		return x.LocalPasswordHash
	}
	return nil
}

func (x *StandaloneConnection) GetLocalSalt() []byte {
	if x != nil {
		return x.LocalSalt
	}
	return nil
}

func (x *StandaloneConnection) GetLastSync() int64 {
	if x != nil {
		return x.LastSync
	}
	return 0
}

func (x *StandaloneConnection) GetSyncStatus() string {
	if x != nil {
		return x.SyncStatus
	}
	return ""
}

func (x *StandaloneConnection) GetSyncedItems() *SyncStats {
	if x != nil {
		return x.SyncedItems
	}
	return nil
}

func (x *StandaloneConnection) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *StandaloneConnection) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

var File_v1_standalone_proto protoreflect.FileDescriptor

const file_v1_standalone_proto_rawDesc = "" +
	"\n" +
	"\x13v1/standalone.proto\x12\bclonr.v1\x1a\x0fv1/common.proto\x1a\x10v1/profile.proto\x1a\x12v1/workspace.proto\x1a\x0fv1/config.proto\"l\n" +
	"\x13AuthenticateRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x1f\n" +
	"\vclient_name\x18\x03 \x01(\tR\n" +
	"clientName\"\x8a\x01\n" +
	"\x14AuthenticateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rsession_token\x18\x02 \x01(\tR\fsessionToken\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"_\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\x12#\n" +
	"\rsession_token\x18\x02 \x01(\tR\fsessionToken\"\x8a\x01\n" +
	"\x14RefreshTokenResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rsession_token\x18\x02 \x01(\tR\fsessionToken\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\x8e\x01\n" +
	"\fPingResponse\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x1f\n" +
	"\vserver_time\x18\x02 \x01(\x03R\n" +
	"serverTime\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\"7\n" +
	"\x10GetStatusRequest\x12#\n" +
	"\rsession_token\x18\x01 \x01(\tR\fsessionToken\"\xe0\x01\n" +
	"\x11GetStatusResponse\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12-\n" +
	"\x12standalone_enabled\x18\x02 \x01(\bR\x11standaloneEnabled\x12\x1b\n" +
	"\tlast_sync\x18\x03 \x01(\x03R\blastSync\x12)\n" +
	"\x05stats\x18\x04 \x01(\v2\x13.clonr.v1.SyncStatsR\x05stats\x123\n" +
	"\aclients\x18\x05 \x03(\v2\x19.clonr.v1.ConnectedClientR\aclients\"u\n" +
	"\tSyncStats\x12\x1a\n" +
	"\bprofiles\x18\x01 \x01(\x05R\bprofiles\x12\x1e\n" +
	"\n" +
	"workspaces\x18\x02 \x01(\x05R\n" +
	"workspaces\x12\x14\n" +
	"\x05repos\x18\x03 \x01(\x05R\x05repos\x12\x16\n" +
	"\x06config\x18\x04 \x01(\bR\x06config\"\xb3\x01\n" +
	"\x0fConnectedClient\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\x12!\n" +
	"\fconnected_at\x18\x04 \x01(\x03R\vconnectedAt\x12\x1b\n" +
	"\tlast_seen\x18\x05 \x01(\x03R\blastSeen\x12\x1d\n" +
	"\n" +
	"sync_count\x18\x06 \x01(\x05R\tsyncCount\"z\n" +
	"\vSyncRequest\x12#\n" +
	"\rsession_token\x18\x01 \x01(\tR\fsessionToken\x12'\n" +
	"\x0fsince_timestamp\x18\x02 \x01(\x03R\x0esinceTimestamp\x12\x1d\n" +
	"\n" +
	"item_types\x18\x03 \x03(\tR\titemTypes\"\x8f\x01\n" +
	"\rEncryptedData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12%\n" +
	"\x0eencrypted_data\x18\x03 \x01(\fR\rencryptedData\x12\x14\n" +
	"\x05nonce\x18\x04 \x01(\fR\x05nonce\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\x03R\tupdatedAt\"\x9e\x01\n" +
	"\tSyncChunk\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12%\n" +
	"\x0eencrypted_data\x18\x02 \x01(\fR\rencryptedData\x12\x14\n" +
	"\x05nonce\x18\x03 \x01(\fR\x05nonce\x12\x1a\n" +
	"\bsequence\x18\x04 \x01(\x05R\bsequence\x12\x14\n" +
	"\x05total\x18\x05 \x01(\x05R\x05total\x12\x0e\n" +
	"\x02id\x18\x06 \x01(\tR\x02id\"\xc2\x02\n" +
	"\rStandaloneKey\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversion\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x12\x17\n" +
	"\aapi_key\x18\x05 \x01(\tR\x06apiKey\x12#\n" +
	"\rrefresh_token\x18\x06 \x01(\tR\frefreshToken\x12.\n" +
	"\x13encryption_key_hint\x18\a \x01(\tR\x11encryptionKeyHint\x12\x1d\n" +
	"\n" +
	"expires_at\x18\b \x01(\x03R\texpiresAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\x12\"\n" +
	"\fcapabilities\x18\n" +
	" \x03(\tR\fcapabilities\"\x9e\x02\n" +
	"\x10StandaloneConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12 \n" +
	"\fapi_key_hash\x18\x04 \x01(\fR\n" +
	"apiKeyHash\x12#\n" +
	"\rrefresh_token\x18\x05 \x01(\fR\frefreshToken\x12\x12\n" +
	"\x04salt\x18\x06 \x01(\fR\x04salt\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\b \x01(\x03R\texpiresAt\x12\"\n" +
	"\fcapabilities\x18\t \x03(\tR\fcapabilities\"\xda\x03\n" +
	"\x14StandaloneConnection\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x12*\n" +
	"\x11api_key_encrypted\x18\x05 \x01(\fR\x0fapiKeyEncrypted\x126\n" +
	"\x17refresh_token_encrypted\x18\x06 \x01(\fR\x15refreshTokenEncrypted\x12.\n" +
	"\x13local_password_hash\x18\a \x01(\fR\x11localPasswordHash\x12\x1d\n" +
	"\n" +
	"local_salt\x18\b \x01(\fR\tlocalSalt\x12\x1b\n" +
	"\tlast_sync\x18\t \x01(\x03R\blastSync\x12\x1f\n" +
	"\vsync_status\x18\n" +
	" \x01(\tR\n" +
	"syncStatus\x126\n" +
	"\fsynced_items\x18\v \x01(\v2\x13.clonr.v1.SyncStatsR\vsyncedItems\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\r \x01(\x03R\tupdatedAt2\xe5\x04\n" +
	"\x11StandaloneService\x12M\n" +
	"\fAuthenticate\x12\x1d.clonr.v1.AuthenticateRequest\x1a\x1e.clonr.v1.AuthenticateResponse\x12M\n" +
	"\fRefreshToken\x12\x1d.clonr.v1.RefreshTokenRequest\x1a\x1e.clonr.v1.RefreshTokenResponse\x12/\n" +
	"\x04Ping\x12\x0f.clonr.v1.Empty\x1a\x16.clonr.v1.PingResponse\x12D\n" +
	"\tGetStatus\x12\x1a.clonr.v1.GetStatusRequest\x1a\x1b.clonr.v1.GetStatusResponse\x12@\n" +
	"\fSyncProfiles\x12\x15.clonr.v1.SyncRequest\x1a\x17.clonr.v1.EncryptedData0\x01\x12B\n" +
	"\x0eSyncWorkspaces\x12\x15.clonr.v1.SyncRequest\x1a\x17.clonr.v1.EncryptedData0\x01\x12=\n" +
	"\tSyncRepos\x12\x15.clonr.v1.SyncRequest\x1a\x17.clonr.v1.EncryptedData0\x01\x12<\n" +
	"\n" +
	"SyncConfig\x12\x15.clonr.v1.SyncRequest\x1a\x17.clonr.v1.EncryptedData\x128\n" +
	"\bFullSync\x12\x15.clonr.v1.SyncRequest\x1a\x13.clonr.v1.SyncChunk0\x01B\x92\x01\n" +
	"\fcom.clonr.v1B\x0fStandaloneProtoP\x01Z0github.com/inovacc/clonr/internal/api/v1;clonrv1\xa2\x02\x03CXX\xaa\x02\bClonr.V1\xca\x02\bClonr\\V1\xe2\x02\x14Clonr\\V1\\GPBMetadata\xea\x02\tClonr::V1b\x06proto3"

var (
	file_v1_standalone_proto_rawDescOnce sync.Once
	file_v1_standalone_proto_rawDescData []byte
)

func file_v1_standalone_proto_rawDescGZIP() []byte {
	file_v1_standalone_proto_rawDescOnce.Do(func() {
		file_v1_standalone_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_standalone_proto_rawDesc), len(file_v1_standalone_proto_rawDesc)))
	})
	return file_v1_standalone_proto_rawDescData
}

var file_v1_standalone_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_v1_standalone_proto_goTypes = []any{
	(*AuthenticateRequest)(nil),  // 0: clonr.v1.AuthenticateRequest
	(*AuthenticateResponse)(nil), // 1: clonr.v1.AuthenticateResponse
	(*RefreshTokenRequest)(nil),  // 2: clonr.v1.RefreshTokenRequest
	(*RefreshTokenResponse)(nil), // 3: clonr.v1.RefreshTokenResponse
	(*PingResponse)(nil),         // 4: clonr.v1.PingResponse
	(*GetStatusRequest)(nil),     // 5: clonr.v1.GetStatusRequest
	(*GetStatusResponse)(nil),    // 6: clonr.v1.GetStatusResponse
	(*SyncStats)(nil),            // 7: clonr.v1.SyncStats
	(*ConnectedClient)(nil),      // 8: clonr.v1.ConnectedClient
	(*SyncRequest)(nil),          // 9: clonr.v1.SyncRequest
	(*EncryptedData)(nil),        // 10: clonr.v1.EncryptedData
	(*SyncChunk)(nil),            // 11: clonr.v1.SyncChunk
	(*StandaloneKey)(nil),        // 12: clonr.v1.StandaloneKey
	(*StandaloneConfig)(nil),     // 13: clonr.v1.StandaloneConfig
	(*StandaloneConnection)(nil), // 14: clonr.v1.StandaloneConnection
	(*Empty)(nil),                // 15: clonr.v1.Empty
}
var file_v1_standalone_proto_depIdxs = []int32{
	7,  // 0: clonr.v1.GetStatusResponse.stats:type_name -> clonr.v1.SyncStats
	8,  // 1: clonr.v1.GetStatusResponse.clients:type_name -> clonr.v1.ConnectedClient
	7,  // 2: clonr.v1.StandaloneConnection.synced_items:type_name -> clonr.v1.SyncStats
	0,  // 3: clonr.v1.StandaloneService.Authenticate:input_type -> clonr.v1.AuthenticateRequest
	2,  // 4: clonr.v1.StandaloneService.RefreshToken:input_type -> clonr.v1.RefreshTokenRequest
	15, // 5: clonr.v1.StandaloneService.Ping:input_type -> clonr.v1.Empty
	5,  // 6: clonr.v1.StandaloneService.GetStatus:input_type -> clonr.v1.GetStatusRequest
	9,  // 7: clonr.v1.StandaloneService.SyncProfiles:input_type -> clonr.v1.SyncRequest
	9,  // 8: clonr.v1.StandaloneService.SyncWorkspaces:input_type -> clonr.v1.SyncRequest
	9,  // 9: clonr.v1.StandaloneService.SyncRepos:input_type -> clonr.v1.SyncRequest
	9,  // 10: clonr.v1.StandaloneService.SyncConfig:input_type -> clonr.v1.SyncRequest
	9,  // 11: clonr.v1.StandaloneService.FullSync:input_type -> clonr.v1.SyncRequest
	1,  // 12: clonr.v1.StandaloneService.Authenticate:output_type -> clonr.v1.AuthenticateResponse
	3,  // 13: clonr.v1.StandaloneService.RefreshToken:output_type -> clonr.v1.RefreshTokenResponse
	4,  // 14: clonr.v1.StandaloneService.Ping:output_type -> clonr.v1.PingResponse
	6,  // 15: clonr.v1.StandaloneService.GetStatus:output_type -> clonr.v1.GetStatusResponse
	10, // 16: clonr.v1.StandaloneService.SyncProfiles:output_type -> clonr.v1.EncryptedData
	10, // 17: clonr.v1.StandaloneService.SyncWorkspaces:output_type -> clonr.v1.EncryptedData
	10, // 18: clonr.v1.StandaloneService.SyncRepos:output_type -> clonr.v1.EncryptedData
	10, // 19: clonr.v1.StandaloneService.SyncConfig:output_type -> clonr.v1.EncryptedData
	11, // 20: clonr.v1.StandaloneService.FullSync:output_type -> clonr.v1.SyncChunk
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_v1_standalone_proto_init() }
func file_v1_standalone_proto_init() {
	if File_v1_standalone_proto != nil {
		return
	}
	file_v1_common_proto_init()
	file_v1_profile_proto_init()
	file_v1_workspace_proto_init()
	file_v1_config_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_standalone_proto_rawDesc), len(file_v1_standalone_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_standalone_proto_goTypes,
		DependencyIndexes: file_v1_standalone_proto_depIdxs,
		MessageInfos:      file_v1_standalone_proto_msgTypes,
	}.Build()
	File_v1_standalone_proto = out.File
	file_v1_standalone_proto_goTypes = nil
	file_v1_standalone_proto_depIdxs = nil
}
