// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: v1/standalone.proto

package clonrv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StandaloneService_Authenticate_FullMethodName   = "/clonr.v1.StandaloneService/Authenticate"
	StandaloneService_RefreshToken_FullMethodName   = "/clonr.v1.StandaloneService/RefreshToken"
	StandaloneService_Ping_FullMethodName           = "/clonr.v1.StandaloneService/Ping"
	StandaloneService_GetStatus_FullMethodName      = "/clonr.v1.StandaloneService/GetStatus"
	StandaloneService_SyncProfiles_FullMethodName   = "/clonr.v1.StandaloneService/SyncProfiles"
	StandaloneService_SyncWorkspaces_FullMethodName = "/clonr.v1.StandaloneService/SyncWorkspaces"
	StandaloneService_SyncRepos_FullMethodName      = "/clonr.v1.StandaloneService/SyncRepos"
	StandaloneService_SyncConfig_FullMethodName     = "/clonr.v1.StandaloneService/SyncConfig"
	StandaloneService_FullSync_FullMethodName       = "/clonr.v1.StandaloneService/FullSync"
)

// StandaloneServiceClient is the client API for StandaloneService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// StandaloneService provides instance synchronization capabilities.
// This service is exposed on a separate port (default 50052) when
// standalone mode is enabled.
type StandaloneServiceClient interface {
	// Authentication
	Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error)
	RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error)
	// Status
	Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PingResponse, error)
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	// Sync operations - streaming for large datasets
	SyncProfiles(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EncryptedData], error)
	SyncWorkspaces(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EncryptedData], error)
	SyncRepos(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EncryptedData], error)
	SyncConfig(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*EncryptedData, error)
	// Full sync - all data in one stream
	FullSync(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SyncChunk], error)
}

type standaloneServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStandaloneServiceClient(cc grpc.ClientConnInterface) StandaloneServiceClient {
	return &standaloneServiceClient{cc}
}

func (c *standaloneServiceClient) Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthenticateResponse)
	err := c.cc.Invoke(ctx, StandaloneService_Authenticate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *standaloneServiceClient) RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshTokenResponse)
	err := c.cc.Invoke(ctx, StandaloneService_RefreshToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *standaloneServiceClient) Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, StandaloneService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *standaloneServiceClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, StandaloneService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *standaloneServiceClient) SyncProfiles(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EncryptedData], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StandaloneService_ServiceDesc.Streams[0], StandaloneService_SyncProfiles_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SyncRequest, EncryptedData]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StandaloneService_SyncProfilesClient = grpc.ServerStreamingClient[EncryptedData]

func (c *standaloneServiceClient) SyncWorkspaces(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EncryptedData], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StandaloneService_ServiceDesc.Streams[1], StandaloneService_SyncWorkspaces_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SyncRequest, EncryptedData]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StandaloneService_SyncWorkspacesClient = grpc.ServerStreamingClient[EncryptedData]

func (c *standaloneServiceClient) SyncRepos(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EncryptedData], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StandaloneService_ServiceDesc.Streams[2], StandaloneService_SyncRepos_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SyncRequest, EncryptedData]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StandaloneService_SyncReposClient = grpc.ServerStreamingClient[EncryptedData]

func (c *standaloneServiceClient) SyncConfig(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*EncryptedData, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EncryptedData)
	err := c.cc.Invoke(ctx, StandaloneService_SyncConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *standaloneServiceClient) FullSync(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SyncChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StandaloneService_ServiceDesc.Streams[3], StandaloneService_FullSync_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SyncRequest, SyncChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StandaloneService_FullSyncClient = grpc.ServerStreamingClient[SyncChunk]

// StandaloneServiceServer is the server API for StandaloneService service.
// All implementations must embed UnimplementedStandaloneServiceServer
// for forward compatibility.
//
// StandaloneService provides instance synchronization capabilities.
// This service is exposed on a separate port (default 50052) when
// standalone mode is enabled.
type StandaloneServiceServer interface {
	// Authentication
	Authenticate(context.Context, *AuthenticateRequest) (*AuthenticateResponse, error)
	RefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error)
	// Status
	Ping(context.Context, *Empty) (*PingResponse, error)
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	// Sync operations - streaming for large datasets
	SyncProfiles(*SyncRequest, grpc.ServerStreamingServer[EncryptedData]) error
	SyncWorkspaces(*SyncRequest, grpc.ServerStreamingServer[EncryptedData]) error
	SyncRepos(*SyncRequest, grpc.ServerStreamingServer[EncryptedData]) error
	SyncConfig(context.Context, *SyncRequest) (*EncryptedData, error)
	// Full sync - all data in one stream
	FullSync(*SyncRequest, grpc.ServerStreamingServer[SyncChunk]) error
	mustEmbedUnimplementedStandaloneServiceServer()
}

// UnimplementedStandaloneServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStandaloneServiceServer struct{}

func (UnimplementedStandaloneServiceServer) Authenticate(context.Context, *AuthenticateRequest) (*AuthenticateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Authenticate not implemented")
}
func (UnimplementedStandaloneServiceServer) RefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshToken not implemented")
}
func (UnimplementedStandaloneServiceServer) Ping(context.Context, *Empty) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedStandaloneServiceServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedStandaloneServiceServer) SyncProfiles(*SyncRequest, grpc.ServerStreamingServer[EncryptedData]) error {
	return status.Error(codes.Unimplemented, "method SyncProfiles not implemented")
}
func (UnimplementedStandaloneServiceServer) SyncWorkspaces(*SyncRequest, grpc.ServerStreamingServer[EncryptedData]) error {
	return status.Error(codes.Unimplemented, "method SyncWorkspaces not implemented")
}
func (UnimplementedStandaloneServiceServer) SyncRepos(*SyncRequest, grpc.ServerStreamingServer[EncryptedData]) error {
	return status.Error(codes.Unimplemented, "method SyncRepos not implemented")
}
func (UnimplementedStandaloneServiceServer) SyncConfig(context.Context, *SyncRequest) (*EncryptedData, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncConfig not implemented")
}
func (UnimplementedStandaloneServiceServer) FullSync(*SyncRequest, grpc.ServerStreamingServer[SyncChunk]) error {
	return status.Error(codes.Unimplemented, "method FullSync not implemented")
}
func (UnimplementedStandaloneServiceServer) mustEmbedUnimplementedStandaloneServiceServer() {}
func (UnimplementedStandaloneServiceServer) testEmbeddedByValue()                           {}

// UnsafeStandaloneServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StandaloneServiceServer will
// result in compilation errors.
type UnsafeStandaloneServiceServer interface {
	mustEmbedUnimplementedStandaloneServiceServer()
}

func RegisterStandaloneServiceServer(s grpc.ServiceRegistrar, srv StandaloneServiceServer) {
	// If the following call panics, it indicates UnimplementedStandaloneServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StandaloneService_ServiceDesc, srv)
}

func _StandaloneService_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StandaloneServiceServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StandaloneService_Authenticate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StandaloneServiceServer).Authenticate(ctx, req.(*AuthenticateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StandaloneService_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StandaloneServiceServer).RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StandaloneService_RefreshToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StandaloneServiceServer).RefreshToken(ctx, req.(*RefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StandaloneService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StandaloneServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StandaloneService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StandaloneServiceServer).Ping(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _StandaloneService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StandaloneServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StandaloneService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StandaloneServiceServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StandaloneService_SyncProfiles_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SyncRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StandaloneServiceServer).SyncProfiles(m, &grpc.GenericServerStream[SyncRequest, EncryptedData]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StandaloneService_SyncProfilesServer = grpc.ServerStreamingServer[EncryptedData]

func _StandaloneService_SyncWorkspaces_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SyncRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StandaloneServiceServer).SyncWorkspaces(m, &grpc.GenericServerStream[SyncRequest, EncryptedData]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StandaloneService_SyncWorkspacesServer = grpc.ServerStreamingServer[EncryptedData]

func _StandaloneService_SyncRepos_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SyncRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StandaloneServiceServer).SyncRepos(m, &grpc.GenericServerStream[SyncRequest, EncryptedData]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StandaloneService_SyncReposServer = grpc.ServerStreamingServer[EncryptedData]

func _StandaloneService_SyncConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StandaloneServiceServer).SyncConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StandaloneService_SyncConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StandaloneServiceServer).SyncConfig(ctx, req.(*SyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StandaloneService_FullSync_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SyncRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StandaloneServiceServer).FullSync(m, &grpc.GenericServerStream[SyncRequest, SyncChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StandaloneService_FullSyncServer = grpc.ServerStreamingServer[SyncChunk]

// StandaloneService_ServiceDesc is the grpc.ServiceDesc for StandaloneService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StandaloneService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clonr.v1.StandaloneService",
	HandlerType: (*StandaloneServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authenticate",
			Handler:    _StandaloneService_Authenticate_Handler,
		},
		{
			MethodName: "RefreshToken",
			Handler:    _StandaloneService_RefreshToken_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _StandaloneService_Ping_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _StandaloneService_GetStatus_Handler,
		},
		{
			MethodName: "SyncConfig",
			Handler:    _StandaloneService_SyncConfig_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SyncProfiles",
			Handler:       _StandaloneService_SyncProfiles_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SyncWorkspaces",
			Handler:       _StandaloneService_SyncWorkspaces_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SyncRepos",
			Handler:       _StandaloneService_SyncRepos_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "FullSync",
			Handler:       _StandaloneService_FullSync_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "v1/standalone.proto",
}
