// Package standalone provides instance synchronization capabilities for clonr.
// It enables secure data sharing between clonr instances across machines.
package standalone

import (
	"time"
)

// Version constants
const (
	KeyVersion = 1
)

// StandaloneKey represents the key generated by a source instance.
// This is shared with destination instances to establish a connection.
type StandaloneKey struct {
	Version           int       `json:"version"`
	InstanceID        string    `json:"instance_id"`
	Host              string    `json:"host"`
	Port              int       `json:"port"`
	APIKey            string    `json:"api_key"`             // Base58-encoded
	RefreshToken      string    `json:"refresh_token"`       // Base58-encoded
	EncryptionKeyHint string    `json:"encryption_key_hint"` // First 4 chars of key hash for verification
	ExpiresAt         time.Time `json:"expires_at"`
	CreatedAt         time.Time `json:"created_at"`
	Capabilities      []string  `json:"capabilities"` // ["profiles", "workspaces", "repos", "config"]
}

// StandaloneConfig represents the source instance's standalone mode configuration.
type StandaloneConfig struct {
	Enabled      bool      `json:"enabled"`
	IsServer     bool      `json:"is_server"`       // True if this instance is a server (accepts connections)
	InstanceID   string    `json:"instance_id"`
	Port         int       `json:"port"`
	APIKeyHash   []byte    `json:"api_key_hash"`    // Argon2 hash for verification
	RefreshToken []byte    `json:"refresh_token"`   // Encrypted refresh token
	Salt         []byte    `json:"salt"`            // Salt for key derivation
	CreatedAt    time.Time `json:"created_at"`
	ExpiresAt    time.Time `json:"expires_at"`
	Capabilities []string  `json:"capabilities"`
}

// StandaloneConnection represents a connection stored at the destination instance.
type StandaloneConnection struct {
	Name                  string    `json:"name"`
	InstanceID            string    `json:"instance_id"`
	Host                  string    `json:"host"`
	Port                  int       `json:"port"`
	APIKeyEncrypted       []byte    `json:"api_key_encrypted"`
	RefreshTokenEncrypted []byte    `json:"refresh_token_encrypted"`
	LocalPasswordHash     []byte    `json:"local_password_hash"` // Argon2 hash for verification
	LocalSalt             []byte    `json:"local_salt"`          // Salt for local encryption
	LastSync              time.Time `json:"last_sync"`
	SyncStatus            string    `json:"sync_status"` // "connected", "disconnected", "error"
	SyncedItems           SyncStats `json:"synced_items"`
	CreatedAt             time.Time `json:"created_at"`
	UpdatedAt             time.Time `json:"updated_at"`
}

// SyncStats tracks what has been synchronized.
type SyncStats struct {
	Profiles   int  `json:"profiles"`
	Workspaces int  `json:"workspaces"`
	Repos      int  `json:"repos"`
	Config     bool `json:"config"`
}

// SyncedProfile represents a profile synced from a standalone instance.
type SyncedProfile struct {
	SourceInstance    string    `json:"source_instance"`
	SourceProfileName string    `json:"source_profile_name"`
	EncryptedData     []byte    `json:"encrypted_data"`
	EncryptionMethod  string    `json:"encryption_method"` // "AES-256-GCM"
	SyncedAt          time.Time `json:"synced_at"`
	Decrypted         bool      `json:"decrypted"`
}

// SyncedWorkspace represents a workspace synced from a standalone instance.
type SyncedWorkspace struct {
	SourceInstance      string    `json:"source_instance"`
	SourceWorkspaceName string    `json:"source_workspace_name"`
	EncryptedData       []byte    `json:"encrypted_data"`
	EncryptionMethod    string    `json:"encryption_method"`
	SyncedAt            time.Time `json:"synced_at"`
	Decrypted           bool      `json:"decrypted"`
}

// ConnectionStatus represents the current status of a standalone connection.
type ConnectionStatus struct {
	Name       string    `json:"name"`
	InstanceID string    `json:"instance_id"`
	Host       string    `json:"host"`
	Port       int       `json:"port"`
	Status     string    `json:"status"` // "connected", "disconnected", "error"
	LastSync   time.Time `json:"last_sync"`
	LastError  string    `json:"last_error,omitempty"`
	Latency    int64     `json:"latency_ms,omitempty"`
}

// Client represents a connected client on the source instance.
type Client struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	IPAddress   string    `json:"ip_address"`
	ConnectedAt time.Time `json:"connected_at"`
	LastSeen    time.Time `json:"last_seen"`
	SyncCount   int       `json:"sync_count"`
}

// Capability constants
const (
	CapabilityProfiles   = "profiles"
	CapabilityWorkspaces = "workspaces"
	CapabilityRepos      = "repos"
	CapabilityConfig     = "config"
)

// DefaultCapabilities returns the default set of sync capabilities.
func DefaultCapabilities() []string {
	return []string{
		CapabilityProfiles,
		CapabilityWorkspaces,
		CapabilityRepos,
		CapabilityConfig,
	}
}

// SyncStatus constants
const (
	StatusConnected    = "connected"
	StatusDisconnected = "disconnected"
	StatusError        = "error"
	StatusSyncing      = "syncing"
)

// DefaultPort for standalone sync service
const DefaultPort = 50052

// DefaultExpirationDays for standalone keys
const DefaultExpirationDays = 30
