// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: config.sql

package sqlc

import (
	"context"
)

const getConfig = `-- name: GetConfig :one
SELECT id, default_clone_dir, editor, terminal, monitor_interval, server_port, custom_editors, updated_at, key_rotation_days FROM config WHERE id = 1
`

func (q *Queries) GetConfig(ctx context.Context) (Config, error) {
	row := q.db.QueryRowContext(ctx, getConfig)
	var i Config
	err := row.Scan(
		&i.ID,
		&i.DefaultCloneDir,
		&i.Editor,
		&i.Terminal,
		&i.MonitorInterval,
		&i.ServerPort,
		&i.CustomEditors,
		&i.UpdatedAt,
		&i.KeyRotationDays,
	)
	return i, err
}

const updateConfig = `-- name: UpdateConfig :exec
UPDATE config SET
    default_clone_dir = ?,
    editor = ?,
    terminal = ?,
    monitor_interval = ?,
    server_port = ?,
    custom_editors = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = 1
`

type UpdateConfigParams struct {
	DefaultCloneDir *string `json:"default_clone_dir"`
	Editor          *string `json:"editor"`
	Terminal        *string `json:"terminal"`
	MonitorInterval *int64  `json:"monitor_interval"`
	ServerPort      *int64  `json:"server_port"`
	CustomEditors   *string `json:"custom_editors"`
}

func (q *Queries) UpdateConfig(ctx context.Context, arg UpdateConfigParams) error {
	_, err := q.db.ExecContext(ctx, updateConfig,
		arg.DefaultCloneDir,
		arg.Editor,
		arg.Terminal,
		arg.MonitorInterval,
		arg.ServerPort,
		arg.CustomEditors,
	)
	return err
}

const updateConfigCloneDir = `-- name: UpdateConfigCloneDir :exec
UPDATE config SET default_clone_dir = ?, updated_at = CURRENT_TIMESTAMP WHERE id = 1
`

func (q *Queries) UpdateConfigCloneDir(ctx context.Context, defaultCloneDir *string) error {
	_, err := q.db.ExecContext(ctx, updateConfigCloneDir, defaultCloneDir)
	return err
}

const updateConfigEditor = `-- name: UpdateConfigEditor :exec
UPDATE config SET editor = ?, updated_at = CURRENT_TIMESTAMP WHERE id = 1
`

func (q *Queries) UpdateConfigEditor(ctx context.Context, editor *string) error {
	_, err := q.db.ExecContext(ctx, updateConfigEditor, editor)
	return err
}

const updateConfigServerPort = `-- name: UpdateConfigServerPort :exec
UPDATE config SET server_port = ?, updated_at = CURRENT_TIMESTAMP WHERE id = 1
`

func (q *Queries) UpdateConfigServerPort(ctx context.Context, serverPort *int64) error {
	_, err := q.db.ExecContext(ctx, updateConfigServerPort, serverPort)
	return err
}
