// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: docker_profiles.sql

package sqlc

import (
	"context"
)

const deleteDockerProfile = `-- name: DeleteDockerProfile :exec
DELETE FROM docker_profiles WHERE name = ?
`

func (q *Queries) DeleteDockerProfile(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteDockerProfile, name)
	return err
}

const dockerProfileExists = `-- name: DockerProfileExists :one
SELECT COUNT(*) FROM docker_profiles WHERE name = ?
`

func (q *Queries) DockerProfileExists(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, dockerProfileExists, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getDockerProfile = `-- name: GetDockerProfile :one
SELECT
    id,
    name,
    registry,
    username,
    encrypted_token,
    token_storage,
    created_at,
    last_used_at
FROM docker_profiles
WHERE name = ?
`

func (q *Queries) GetDockerProfile(ctx context.Context, name string) (DockerProfile, error) {
	row := q.db.QueryRowContext(ctx, getDockerProfile, name)
	var i DockerProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Registry,
		&i.Username,
		&i.EncryptedToken,
		&i.TokenStorage,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const insertDockerProfile = `-- name: InsertDockerProfile :execlastid

INSERT INTO docker_profiles (name, registry, username, encrypted_token, token_storage)
VALUES (?, ?, ?, ?, ?)
`

type InsertDockerProfileParams struct {
	Name           string  `json:"name"`
	Registry       *string `json:"registry"`
	Username       string  `json:"username"`
	EncryptedToken []byte  `json:"encrypted_token"`
	TokenStorage   *string `json:"token_storage"`
}

// Docker profile queries
func (q *Queries) InsertDockerProfile(ctx context.Context, arg InsertDockerProfileParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertDockerProfile,
		arg.Name,
		arg.Registry,
		arg.Username,
		arg.EncryptedToken,
		arg.TokenStorage,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const listDockerProfiles = `-- name: ListDockerProfiles :many
SELECT
    id,
    name,
    registry,
    username,
    encrypted_token,
    token_storage,
    created_at,
    last_used_at
FROM docker_profiles
ORDER BY name
`

func (q *Queries) ListDockerProfiles(ctx context.Context) ([]DockerProfile, error) {
	rows, err := q.db.QueryContext(ctx, listDockerProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DockerProfile{}
	for rows.Next() {
		var i DockerProfile
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Registry,
			&i.Username,
			&i.EncryptedToken,
			&i.TokenStorage,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDockerProfile = `-- name: UpdateDockerProfile :exec
UPDATE docker_profiles
SET
    registry = ?,
    username = ?,
    encrypted_token = ?,
    token_storage = ?,
    last_used_at = CURRENT_TIMESTAMP
WHERE name = ?
`

type UpdateDockerProfileParams struct {
	Registry       *string `json:"registry"`
	Username       string  `json:"username"`
	EncryptedToken []byte  `json:"encrypted_token"`
	TokenStorage   *string `json:"token_storage"`
	Name           string  `json:"name"`
}

func (q *Queries) UpdateDockerProfile(ctx context.Context, arg UpdateDockerProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateDockerProfile,
		arg.Registry,
		arg.Username,
		arg.EncryptedToken,
		arg.TokenStorage,
		arg.Name,
	)
	return err
}

const updateDockerProfileLastUsed = `-- name: UpdateDockerProfileLastUsed :exec
UPDATE docker_profiles
SET last_used_at = CURRENT_TIMESTAMP
WHERE name = ?
`

func (q *Queries) UpdateDockerProfileLastUsed(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, updateDockerProfileLastUsed, name)
	return err
}
