// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"
)

type Config struct {
	ID              int64     `json:"id"`
	DefaultCloneDir *string   `json:"default_clone_dir"`
	Editor          *string   `json:"editor"`
	Terminal        *string   `json:"terminal"`
	MonitorInterval *int64    `json:"monitor_interval"`
	ServerPort      *int64    `json:"server_port"`
	CustomEditors   *string   `json:"custom_editors"`
	UpdatedAt       time.Time `json:"updated_at"`
	KeyRotationDays *int64    `json:"key_rotation_days"`
}

type DockerProfile struct {
	ID             int64     `json:"id"`
	Name           string    `json:"name"`
	Registry       *string   `json:"registry"`
	Username       string    `json:"username"`
	EncryptedToken []byte    `json:"encrypted_token"`
	TokenStorage   *string   `json:"token_storage"`
	CreatedAt      time.Time `json:"created_at"`
	LastUsedAt     time.Time `json:"last_used_at"`
}

type PendingRegistration struct {
	ClientID       string    `json:"client_id"`
	ClientName     string    `json:"client_name"`
	MachineInfo    *string   `json:"machine_info"`
	State          *string   `json:"state"`
	ChallengeToken *string   `json:"challenge_token"`
	ChallengeAt    time.Time `json:"challenge_at"`
	InitiatedAt    time.Time `json:"initiated_at"`
	CompletedAt    time.Time `json:"completed_at"`
}

type Profile struct {
	ID             int64     `json:"id"`
	Name           string    `json:"name"`
	Host           *string   `json:"host"`
	Username       *string   `json:"username"`
	TokenStorage   *string   `json:"token_storage"`
	Scopes         *string   `json:"scopes"`
	IsDefault      *int64    `json:"is_default"`
	EncryptedToken []byte    `json:"encrypted_token"`
	Workspace      *string   `json:"workspace"`
	NotifyChannels *string   `json:"notify_channels"`
	CreatedAt      time.Time `json:"created_at"`
	LastUsedAt     time.Time `json:"last_used_at"`
}

type RegisteredClient struct {
	ClientID          string    `json:"client_id"`
	ClientName        string    `json:"client_name"`
	MachineInfo       *string   `json:"machine_info"`
	EncryptionKeyHash []byte    `json:"encryption_key_hash"`
	EncryptionSalt    []byte    `json:"encryption_salt"`
	KeyHint           *string   `json:"key_hint"`
	Status            *string   `json:"status"`
	SyncCount         *int64    `json:"sync_count"`
	LastIp            *string   `json:"last_ip"`
	RegisteredAt      time.Time `json:"registered_at"`
	LastSeenAt        time.Time `json:"last_seen_at"`
}

type Repository struct {
	ID          int64     `json:"id"`
	Uid         string    `json:"uid"`
	Url         string    `json:"url"`
	Path        string    `json:"path"`
	Workspace   *string   `json:"workspace"`
	Favorite    *int64    `json:"favorite"`
	ClonedAt    time.Time `json:"cloned_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	LastChecked time.Time `json:"last_checked"`
}

type SchemaMigration struct {
	Version     int64      `json:"version"`
	AppliedAt   *time.Time `json:"applied_at"`
	Description *string    `json:"description"`
}

type SealedKey struct {
	ID           int64     `json:"id"`
	SealedData   []byte    `json:"sealed_data"`
	Version      *int64    `json:"version"`
	KeyType      *string   `json:"key_type"`
	Metadata     *string   `json:"metadata"`
	CreatedAt    time.Time `json:"created_at"`
	RotatedAt    time.Time `json:"rotated_at"`
	LastAccessed time.Time `json:"last_accessed"`
}

type ServerEncryptionConfig struct {
	ID           int64     `json:"id"`
	Enabled      *int64    `json:"enabled"`
	KeyHash      []byte    `json:"key_hash"`
	Salt         []byte    `json:"salt"`
	KeyHint      *string   `json:"key_hint"`
	ConfiguredAt time.Time `json:"configured_at"`
}

type StandaloneClient struct {
	ID          string     `json:"id"`
	Name        string     `json:"name"`
	MachineInfo *string    `json:"machine_info"`
	ConnectedAt *time.Time `json:"connected_at"`
	LastSync    time.Time  `json:"last_sync"`
}

type StandaloneConfig struct {
	ID           int64     `json:"id"`
	Enabled      *int64    `json:"enabled"`
	IsServer     *int64    `json:"is_server"`
	InstanceID   *string   `json:"instance_id"`
	Port         *int64    `json:"port"`
	ApiKeyHash   []byte    `json:"api_key_hash"`
	RefreshToken []byte    `json:"refresh_token"`
	Salt         []byte    `json:"salt"`
	Capabilities *string   `json:"capabilities"`
	CreatedAt    time.Time `json:"created_at"`
	ExpiresAt    time.Time `json:"expires_at"`
}

type StandaloneConnection struct {
	ID                    int64     `json:"id"`
	Name                  string    `json:"name"`
	InstanceID            *string   `json:"instance_id"`
	Host                  string    `json:"host"`
	Port                  *int64    `json:"port"`
	ApiKeyEncrypted       []byte    `json:"api_key_encrypted"`
	RefreshTokenEncrypted []byte    `json:"refresh_token_encrypted"`
	LocalPasswordHash     []byte    `json:"local_password_hash"`
	LocalSalt             []byte    `json:"local_salt"`
	SyncStatus            *string   `json:"sync_status"`
	SyncedItems           *string   `json:"synced_items"`
	LastSync              time.Time `json:"last_sync"`
	CreatedAt             time.Time `json:"created_at"`
	UpdatedAt             time.Time `json:"updated_at"`
}

type SyncedDatum struct {
	ID             string    `json:"id"`
	ConnectionName string    `json:"connection_name"`
	InstanceID     *string   `json:"instance_id"`
	DataType       string    `json:"data_type"`
	Name           string    `json:"name"`
	EncryptedData  []byte    `json:"encrypted_data"`
	Nonce          []byte    `json:"nonce"`
	State          *string   `json:"state"`
	Checksum       *string   `json:"checksum"`
	SyncedAt       time.Time `json:"synced_at"`
	DecryptedAt    time.Time `json:"decrypted_at"`
}

type Workspace struct {
	ID          int64     `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	Path        *string   `json:"path"`
	IsActive    *int64    `json:"is_active"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}
