// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profiles.sql

package sqlc

import (
	"context"
)

const clearActiveProfile = `-- name: ClearActiveProfile :exec
UPDATE profiles SET is_default = 0
`

func (q *Queries) ClearActiveProfile(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearActiveProfile)
	return err
}

const deleteProfile = `-- name: DeleteProfile :exec
DELETE FROM profiles WHERE name = ?
`

func (q *Queries) DeleteProfile(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteProfile, name)
	return err
}

const getActiveProfile = `-- name: GetActiveProfile :one
SELECT id, name, host, username, token_storage, scopes, is_default, encrypted_token, workspace, notify_channels, created_at, last_used_at FROM profiles WHERE is_default = 1 LIMIT 1
`

func (q *Queries) GetActiveProfile(ctx context.Context) (Profile, error) {
	row := q.db.QueryRowContext(ctx, getActiveProfile)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Host,
		&i.Username,
		&i.TokenStorage,
		&i.Scopes,
		&i.IsDefault,
		&i.EncryptedToken,
		&i.Workspace,
		&i.NotifyChannels,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getProfile = `-- name: GetProfile :one
SELECT id, name, host, username, token_storage, scopes, is_default, encrypted_token, workspace, notify_channels, created_at, last_used_at FROM profiles WHERE name = ? LIMIT 1
`

func (q *Queries) GetProfile(ctx context.Context, name string) (Profile, error) {
	row := q.db.QueryRowContext(ctx, getProfile, name)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Host,
		&i.Username,
		&i.TokenStorage,
		&i.Scopes,
		&i.IsDefault,
		&i.EncryptedToken,
		&i.Workspace,
		&i.NotifyChannels,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const insertProfile = `-- name: InsertProfile :one
INSERT INTO profiles (
    name, host, username, token_storage, scopes, is_default,
    encrypted_token, workspace, notify_channels, created_at, last_used_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, NULL)
RETURNING id, name, host, username, token_storage, scopes, is_default, encrypted_token, workspace, notify_channels, created_at, last_used_at
`

type InsertProfileParams struct {
	Name           string  `json:"name"`
	Host           *string `json:"host"`
	Username       *string `json:"username"`
	TokenStorage   *string `json:"token_storage"`
	Scopes         *string `json:"scopes"`
	IsDefault      *int64  `json:"is_default"`
	EncryptedToken []byte  `json:"encrypted_token"`
	Workspace      *string `json:"workspace"`
	NotifyChannels *string `json:"notify_channels"`
}

func (q *Queries) InsertProfile(ctx context.Context, arg InsertProfileParams) (Profile, error) {
	row := q.db.QueryRowContext(ctx, insertProfile,
		arg.Name,
		arg.Host,
		arg.Username,
		arg.TokenStorage,
		arg.Scopes,
		arg.IsDefault,
		arg.EncryptedToken,
		arg.Workspace,
		arg.NotifyChannels,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Host,
		&i.Username,
		&i.TokenStorage,
		&i.Scopes,
		&i.IsDefault,
		&i.EncryptedToken,
		&i.Workspace,
		&i.NotifyChannels,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const listProfiles = `-- name: ListProfiles :many
SELECT id, name, host, username, token_storage, scopes, is_default, encrypted_token, workspace, notify_channels, created_at, last_used_at FROM profiles ORDER BY name ASC
`

func (q *Queries) ListProfiles(ctx context.Context) ([]Profile, error) {
	rows, err := q.db.QueryContext(ctx, listProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Profile{}
	for rows.Next() {
		var i Profile
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Host,
			&i.Username,
			&i.TokenStorage,
			&i.Scopes,
			&i.IsDefault,
			&i.EncryptedToken,
			&i.Workspace,
			&i.NotifyChannels,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const profileExists = `-- name: ProfileExists :one
SELECT EXISTS(SELECT 1 FROM profiles WHERE name = ?) AS exists_flag
`

func (q *Queries) ProfileExists(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, profileExists, name)
	var exists_flag int64
	err := row.Scan(&exists_flag)
	return exists_flag, err
}

const setActiveProfile = `-- name: SetActiveProfile :exec
UPDATE profiles SET is_default = CASE WHEN name = ? THEN 1 ELSE 0 END
`

func (q *Queries) SetActiveProfile(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, setActiveProfile, name)
	return err
}

const updateProfile = `-- name: UpdateProfile :exec
UPDATE profiles SET
    host = ?,
    username = ?,
    token_storage = ?,
    scopes = ?,
    encrypted_token = ?,
    workspace = ?,
    notify_channels = ?
WHERE name = ?
`

type UpdateProfileParams struct {
	Host           *string `json:"host"`
	Username       *string `json:"username"`
	TokenStorage   *string `json:"token_storage"`
	Scopes         *string `json:"scopes"`
	EncryptedToken []byte  `json:"encrypted_token"`
	Workspace      *string `json:"workspace"`
	NotifyChannels *string `json:"notify_channels"`
	Name           string  `json:"name"`
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateProfile,
		arg.Host,
		arg.Username,
		arg.TokenStorage,
		arg.Scopes,
		arg.EncryptedToken,
		arg.Workspace,
		arg.NotifyChannels,
		arg.Name,
	)
	return err
}

const updateProfileLastUsed = `-- name: UpdateProfileLastUsed :exec
UPDATE profiles SET last_used_at = CURRENT_TIMESTAMP WHERE name = ?
`

func (q *Queries) UpdateProfileLastUsed(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, updateProfileLastUsed, name)
	return err
}

const updateProfileNotifyChannels = `-- name: UpdateProfileNotifyChannels :exec
UPDATE profiles SET notify_channels = ? WHERE name = ?
`

type UpdateProfileNotifyChannelsParams struct {
	NotifyChannels *string `json:"notify_channels"`
	Name           string  `json:"name"`
}

func (q *Queries) UpdateProfileNotifyChannels(ctx context.Context, arg UpdateProfileNotifyChannelsParams) error {
	_, err := q.db.ExecContext(ctx, updateProfileNotifyChannels, arg.NotifyChannels, arg.Name)
	return err
}
