// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sealed_keys.sql

package sqlc

import (
	"context"
	"time"
)

const deleteSealedKey = `-- name: DeleteSealedKey :exec
DELETE FROM sealed_keys WHERE id = 1
`

func (q *Queries) DeleteSealedKey(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteSealedKey)
	return err
}

const getSealedKey = `-- name: GetSealedKey :one

SELECT
    sealed_data,
    version,
    key_type,
    metadata,
    created_at,
    rotated_at,
    last_accessed
FROM sealed_keys
WHERE id = 1
`

type GetSealedKeyRow struct {
	SealedData   []byte    `json:"sealed_data"`
	Version      *int64    `json:"version"`
	KeyType      *string   `json:"key_type"`
	Metadata     *string   `json:"metadata"`
	CreatedAt    time.Time `json:"created_at"`
	RotatedAt    time.Time `json:"rotated_at"`
	LastAccessed time.Time `json:"last_accessed"`
}

// Sealed key queries
func (q *Queries) GetSealedKey(ctx context.Context) (GetSealedKeyRow, error) {
	row := q.db.QueryRowContext(ctx, getSealedKey)
	var i GetSealedKeyRow
	err := row.Scan(
		&i.SealedData,
		&i.Version,
		&i.KeyType,
		&i.Metadata,
		&i.CreatedAt,
		&i.RotatedAt,
		&i.LastAccessed,
	)
	return i, err
}

const insertSealedKey = `-- name: InsertSealedKey :exec
INSERT INTO sealed_keys (id, sealed_data, version, key_type, metadata, created_at, rotated_at, last_accessed)
VALUES (1, ?, ?, ?, ?, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP)
ON CONFLICT(id) DO UPDATE SET
    sealed_data = excluded.sealed_data,
    version = excluded.version,
    key_type = excluded.key_type,
    metadata = excluded.metadata,
    rotated_at = CASE WHEN sealed_keys.sealed_data != excluded.sealed_data THEN CURRENT_TIMESTAMP ELSE sealed_keys.rotated_at END,
    last_accessed = CURRENT_TIMESTAMP
`

type InsertSealedKeyParams struct {
	SealedData []byte  `json:"sealed_data"`
	Version    *int64  `json:"version"`
	KeyType    *string `json:"key_type"`
	Metadata   *string `json:"metadata"`
}

func (q *Queries) InsertSealedKey(ctx context.Context, arg InsertSealedKeyParams) error {
	_, err := q.db.ExecContext(ctx, insertSealedKey,
		arg.SealedData,
		arg.Version,
		arg.KeyType,
		arg.Metadata,
	)
	return err
}

const sealedKeyExists = `-- name: SealedKeyExists :one
SELECT COUNT(*) FROM sealed_keys WHERE id = 1
`

func (q *Queries) SealedKeyExists(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, sealedKeyExists)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateSealedKeyAccess = `-- name: UpdateSealedKeyAccess :exec
UPDATE sealed_keys
SET last_accessed = CURRENT_TIMESTAMP
WHERE id = 1
`

func (q *Queries) UpdateSealedKeyAccess(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, updateSealedKeyAccess)
	return err
}
