// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: slack.sql

package sqlc

import (
	"context"
)

const deleteSlackConfig = `-- name: DeleteSlackConfig :exec
DELETE FROM slack_config WHERE id = 1
`

func (q *Queries) DeleteSlackConfig(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteSlackConfig)
	return err
}

const disableSlackNotifications = `-- name: DisableSlackNotifications :exec
UPDATE slack_config SET enabled = 0, updated_at = CURRENT_TIMESTAMP WHERE id = 1
`

func (q *Queries) DisableSlackNotifications(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, disableSlackNotifications)
	return err
}

const enableSlackNotifications = `-- name: EnableSlackNotifications :exec
UPDATE slack_config SET enabled = 1, updated_at = CURRENT_TIMESTAMP WHERE id = 1
`

func (q *Queries) EnableSlackNotifications(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, enableSlackNotifications)
	return err
}

const getSlackConfig = `-- name: GetSlackConfig :one
SELECT id, enabled, workspace_id, workspace_name, encrypted_webhook_url, encrypted_bot_token, default_channel, bot_enabled, events, created_at, updated_at FROM slack_config WHERE id = 1 LIMIT 1
`

func (q *Queries) GetSlackConfig(ctx context.Context) (SlackConfig, error) {
	row := q.db.QueryRowContext(ctx, getSlackConfig)
	var i SlackConfig
	err := row.Scan(
		&i.ID,
		&i.Enabled,
		&i.WorkspaceID,
		&i.WorkspaceName,
		&i.EncryptedWebhookUrl,
		&i.EncryptedBotToken,
		&i.DefaultChannel,
		&i.BotEnabled,
		&i.Events,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSlackConfig = `-- name: InsertSlackConfig :one
INSERT INTO slack_config (
    id, enabled, workspace_id, workspace_name, encrypted_webhook_url,
    encrypted_bot_token, default_channel, bot_enabled, events, created_at, updated_at
) VALUES (1, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, enabled, workspace_id, workspace_name, encrypted_webhook_url, encrypted_bot_token, default_channel, bot_enabled, events, created_at, updated_at
`

type InsertSlackConfigParams struct {
	Enabled             *int64  `json:"enabled"`
	WorkspaceID         *string `json:"workspace_id"`
	WorkspaceName       *string `json:"workspace_name"`
	EncryptedWebhookUrl []byte  `json:"encrypted_webhook_url"`
	EncryptedBotToken   []byte  `json:"encrypted_bot_token"`
	DefaultChannel      *string `json:"default_channel"`
	BotEnabled          *int64  `json:"bot_enabled"`
	Events              *string `json:"events"`
}

func (q *Queries) InsertSlackConfig(ctx context.Context, arg InsertSlackConfigParams) (SlackConfig, error) {
	row := q.db.QueryRowContext(ctx, insertSlackConfig,
		arg.Enabled,
		arg.WorkspaceID,
		arg.WorkspaceName,
		arg.EncryptedWebhookUrl,
		arg.EncryptedBotToken,
		arg.DefaultChannel,
		arg.BotEnabled,
		arg.Events,
	)
	var i SlackConfig
	err := row.Scan(
		&i.ID,
		&i.Enabled,
		&i.WorkspaceID,
		&i.WorkspaceName,
		&i.EncryptedWebhookUrl,
		&i.EncryptedBotToken,
		&i.DefaultChannel,
		&i.BotEnabled,
		&i.Events,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const slackConfigExists = `-- name: SlackConfigExists :one
SELECT EXISTS(SELECT 1 FROM slack_config WHERE id = 1) AS exists_flag
`

func (q *Queries) SlackConfigExists(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, slackConfigExists)
	var exists_flag int64
	err := row.Scan(&exists_flag)
	return exists_flag, err
}

const updateSlackConfig = `-- name: UpdateSlackConfig :exec
UPDATE slack_config SET
    enabled = ?,
    workspace_id = ?,
    workspace_name = ?,
    encrypted_webhook_url = ?,
    encrypted_bot_token = ?,
    default_channel = ?,
    bot_enabled = ?,
    events = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = 1
`

type UpdateSlackConfigParams struct {
	Enabled             *int64  `json:"enabled"`
	WorkspaceID         *string `json:"workspace_id"`
	WorkspaceName       *string `json:"workspace_name"`
	EncryptedWebhookUrl []byte  `json:"encrypted_webhook_url"`
	EncryptedBotToken   []byte  `json:"encrypted_bot_token"`
	DefaultChannel      *string `json:"default_channel"`
	BotEnabled          *int64  `json:"bot_enabled"`
	Events              *string `json:"events"`
}

func (q *Queries) UpdateSlackConfig(ctx context.Context, arg UpdateSlackConfigParams) error {
	_, err := q.db.ExecContext(ctx, updateSlackConfig,
		arg.Enabled,
		arg.WorkspaceID,
		arg.WorkspaceName,
		arg.EncryptedWebhookUrl,
		arg.EncryptedBotToken,
		arg.DefaultChannel,
		arg.BotEnabled,
		arg.Events,
	)
	return err
}
