// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: standalone.sql

package sqlc

import (
	"context"
	"time"
)

const deleteServerEncryptionConfig = `-- name: DeleteServerEncryptionConfig :exec
DELETE FROM server_encryption_config WHERE id = 1
`

func (q *Queries) DeleteServerEncryptionConfig(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteServerEncryptionConfig)
	return err
}

const deleteStandaloneClient = `-- name: DeleteStandaloneClient :exec
DELETE FROM standalone_clients WHERE id = ?
`

func (q *Queries) DeleteStandaloneClient(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteStandaloneClient, id)
	return err
}

const deleteStandaloneConfig = `-- name: DeleteStandaloneConfig :exec
DELETE FROM standalone_config WHERE id = 1
`

func (q *Queries) DeleteStandaloneConfig(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteStandaloneConfig)
	return err
}

const deleteStandaloneConnection = `-- name: DeleteStandaloneConnection :exec
DELETE FROM standalone_connections WHERE name = ?
`

func (q *Queries) DeleteStandaloneConnection(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteStandaloneConnection, name)
	return err
}

const getServerEncryptionConfig = `-- name: GetServerEncryptionConfig :one
SELECT id, enabled, key_hash, salt, key_hint, configured_at FROM server_encryption_config WHERE id = 1
`

// Server Encryption Config
func (q *Queries) GetServerEncryptionConfig(ctx context.Context) (ServerEncryptionConfig, error) {
	row := q.db.QueryRowContext(ctx, getServerEncryptionConfig)
	var i ServerEncryptionConfig
	err := row.Scan(
		&i.ID,
		&i.Enabled,
		&i.KeyHash,
		&i.Salt,
		&i.KeyHint,
		&i.ConfiguredAt,
	)
	return i, err
}

const getStandaloneClient = `-- name: GetStandaloneClient :one
SELECT id, name, machine_info, connected_at, last_sync FROM standalone_clients WHERE id = ? LIMIT 1
`

// Standalone Clients (server mode)
func (q *Queries) GetStandaloneClient(ctx context.Context, id string) (StandaloneClient, error) {
	row := q.db.QueryRowContext(ctx, getStandaloneClient, id)
	var i StandaloneClient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MachineInfo,
		&i.ConnectedAt,
		&i.LastSync,
	)
	return i, err
}

const getStandaloneConfig = `-- name: GetStandaloneConfig :one
SELECT id, enabled, is_server, instance_id, port, api_key_hash, refresh_token, salt, capabilities, created_at, expires_at FROM standalone_config WHERE id = 1
`

// Standalone Config
func (q *Queries) GetStandaloneConfig(ctx context.Context) (StandaloneConfig, error) {
	row := q.db.QueryRowContext(ctx, getStandaloneConfig)
	var i StandaloneConfig
	err := row.Scan(
		&i.ID,
		&i.Enabled,
		&i.IsServer,
		&i.InstanceID,
		&i.Port,
		&i.ApiKeyHash,
		&i.RefreshToken,
		&i.Salt,
		&i.Capabilities,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getStandaloneConnection = `-- name: GetStandaloneConnection :one
SELECT id, name, instance_id, host, port, api_key_encrypted, refresh_token_encrypted, local_password_hash, local_salt, sync_status, synced_items, last_sync, created_at, updated_at FROM standalone_connections WHERE name = ? LIMIT 1
`

// Standalone Connections (client mode)
func (q *Queries) GetStandaloneConnection(ctx context.Context, name string) (StandaloneConnection, error) {
	row := q.db.QueryRowContext(ctx, getStandaloneConnection, name)
	var i StandaloneConnection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InstanceID,
		&i.Host,
		&i.Port,
		&i.ApiKeyEncrypted,
		&i.RefreshTokenEncrypted,
		&i.LocalPasswordHash,
		&i.LocalSalt,
		&i.SyncStatus,
		&i.SyncedItems,
		&i.LastSync,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertStandaloneClient = `-- name: InsertStandaloneClient :exec
INSERT INTO standalone_clients (id, name, machine_info, connected_at, last_sync)
VALUES (?, ?, ?, CURRENT_TIMESTAMP, NULL)
ON CONFLICT(id) DO UPDATE SET
    name = excluded.name,
    machine_info = excluded.machine_info,
    last_sync = excluded.last_sync
`

type InsertStandaloneClientParams struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	MachineInfo *string `json:"machine_info"`
}

func (q *Queries) InsertStandaloneClient(ctx context.Context, arg InsertStandaloneClientParams) error {
	_, err := q.db.ExecContext(ctx, insertStandaloneClient, arg.ID, arg.Name, arg.MachineInfo)
	return err
}

const insertStandaloneConnection = `-- name: InsertStandaloneConnection :one
INSERT INTO standalone_connections (
    name, instance_id, host, port, api_key_encrypted, refresh_token_encrypted,
    local_password_hash, local_salt, sync_status, synced_items, last_sync, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, name, instance_id, host, port, api_key_encrypted, refresh_token_encrypted, local_password_hash, local_salt, sync_status, synced_items, last_sync, created_at, updated_at
`

type InsertStandaloneConnectionParams struct {
	Name                  string    `json:"name"`
	InstanceID            *string   `json:"instance_id"`
	Host                  string    `json:"host"`
	Port                  *int64    `json:"port"`
	ApiKeyEncrypted       []byte    `json:"api_key_encrypted"`
	RefreshTokenEncrypted []byte    `json:"refresh_token_encrypted"`
	LocalPasswordHash     []byte    `json:"local_password_hash"`
	LocalSalt             []byte    `json:"local_salt"`
	SyncStatus            *string   `json:"sync_status"`
	SyncedItems           *string   `json:"synced_items"`
	LastSync              time.Time `json:"last_sync"`
}

func (q *Queries) InsertStandaloneConnection(ctx context.Context, arg InsertStandaloneConnectionParams) (StandaloneConnection, error) {
	row := q.db.QueryRowContext(ctx, insertStandaloneConnection,
		arg.Name,
		arg.InstanceID,
		arg.Host,
		arg.Port,
		arg.ApiKeyEncrypted,
		arg.RefreshTokenEncrypted,
		arg.LocalPasswordHash,
		arg.LocalSalt,
		arg.SyncStatus,
		arg.SyncedItems,
		arg.LastSync,
	)
	var i StandaloneConnection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InstanceID,
		&i.Host,
		&i.Port,
		&i.ApiKeyEncrypted,
		&i.RefreshTokenEncrypted,
		&i.LocalPasswordHash,
		&i.LocalSalt,
		&i.SyncStatus,
		&i.SyncedItems,
		&i.LastSync,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStandaloneClients = `-- name: ListStandaloneClients :many
SELECT id, name, machine_info, connected_at, last_sync FROM standalone_clients ORDER BY connected_at DESC
`

func (q *Queries) ListStandaloneClients(ctx context.Context) ([]StandaloneClient, error) {
	rows, err := q.db.QueryContext(ctx, listStandaloneClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StandaloneClient{}
	for rows.Next() {
		var i StandaloneClient
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MachineInfo,
			&i.ConnectedAt,
			&i.LastSync,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStandaloneConnections = `-- name: ListStandaloneConnections :many
SELECT id, name, instance_id, host, port, api_key_encrypted, refresh_token_encrypted, local_password_hash, local_salt, sync_status, synced_items, last_sync, created_at, updated_at FROM standalone_connections ORDER BY name ASC
`

func (q *Queries) ListStandaloneConnections(ctx context.Context) ([]StandaloneConnection, error) {
	rows, err := q.db.QueryContext(ctx, listStandaloneConnections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StandaloneConnection{}
	for rows.Next() {
		var i StandaloneConnection
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.InstanceID,
			&i.Host,
			&i.Port,
			&i.ApiKeyEncrypted,
			&i.RefreshTokenEncrypted,
			&i.LocalPasswordHash,
			&i.LocalSalt,
			&i.SyncStatus,
			&i.SyncedItems,
			&i.LastSync,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStandaloneClientLastSync = `-- name: UpdateStandaloneClientLastSync :exec
UPDATE standalone_clients SET last_sync = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) UpdateStandaloneClientLastSync(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateStandaloneClientLastSync, id)
	return err
}

const updateStandaloneConnection = `-- name: UpdateStandaloneConnection :exec
UPDATE standalone_connections SET
    instance_id = ?,
    host = ?,
    port = ?,
    api_key_encrypted = ?,
    refresh_token_encrypted = ?,
    local_password_hash = ?,
    local_salt = ?,
    sync_status = ?,
    synced_items = ?,
    last_sync = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE name = ?
`

type UpdateStandaloneConnectionParams struct {
	InstanceID            *string   `json:"instance_id"`
	Host                  string    `json:"host"`
	Port                  *int64    `json:"port"`
	ApiKeyEncrypted       []byte    `json:"api_key_encrypted"`
	RefreshTokenEncrypted []byte    `json:"refresh_token_encrypted"`
	LocalPasswordHash     []byte    `json:"local_password_hash"`
	LocalSalt             []byte    `json:"local_salt"`
	SyncStatus            *string   `json:"sync_status"`
	SyncedItems           *string   `json:"synced_items"`
	LastSync              time.Time `json:"last_sync"`
	Name                  string    `json:"name"`
}

func (q *Queries) UpdateStandaloneConnection(ctx context.Context, arg UpdateStandaloneConnectionParams) error {
	_, err := q.db.ExecContext(ctx, updateStandaloneConnection,
		arg.InstanceID,
		arg.Host,
		arg.Port,
		arg.ApiKeyEncrypted,
		arg.RefreshTokenEncrypted,
		arg.LocalPasswordHash,
		arg.LocalSalt,
		arg.SyncStatus,
		arg.SyncedItems,
		arg.LastSync,
		arg.Name,
	)
	return err
}

const updateStandaloneConnectionStatus = `-- name: UpdateStandaloneConnectionStatus :exec
UPDATE standalone_connections SET
    sync_status = ?,
    last_sync = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE name = ?
`

type UpdateStandaloneConnectionStatusParams struct {
	SyncStatus *string `json:"sync_status"`
	Name       string  `json:"name"`
}

func (q *Queries) UpdateStandaloneConnectionStatus(ctx context.Context, arg UpdateStandaloneConnectionStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateStandaloneConnectionStatus, arg.SyncStatus, arg.Name)
	return err
}

const upsertServerEncryptionConfig = `-- name: UpsertServerEncryptionConfig :exec
INSERT INTO server_encryption_config (id, enabled, key_hash, salt, key_hint, configured_at)
VALUES (1, ?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(id) DO UPDATE SET
    enabled = excluded.enabled,
    key_hash = excluded.key_hash,
    salt = excluded.salt,
    key_hint = excluded.key_hint,
    configured_at = excluded.configured_at
`

type UpsertServerEncryptionConfigParams struct {
	Enabled *int64  `json:"enabled"`
	KeyHash []byte  `json:"key_hash"`
	Salt    []byte  `json:"salt"`
	KeyHint *string `json:"key_hint"`
}

func (q *Queries) UpsertServerEncryptionConfig(ctx context.Context, arg UpsertServerEncryptionConfigParams) error {
	_, err := q.db.ExecContext(ctx, upsertServerEncryptionConfig,
		arg.Enabled,
		arg.KeyHash,
		arg.Salt,
		arg.KeyHint,
	)
	return err
}

const upsertStandaloneConfig = `-- name: UpsertStandaloneConfig :exec
INSERT INTO standalone_config (id, enabled, is_server, instance_id, port, api_key_hash, refresh_token, salt, capabilities, created_at, expires_at)
VALUES (1, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, ?)
ON CONFLICT(id) DO UPDATE SET
    enabled = excluded.enabled,
    is_server = excluded.is_server,
    instance_id = excluded.instance_id,
    port = excluded.port,
    api_key_hash = excluded.api_key_hash,
    refresh_token = excluded.refresh_token,
    salt = excluded.salt,
    capabilities = excluded.capabilities,
    expires_at = excluded.expires_at
`

type UpsertStandaloneConfigParams struct {
	Enabled      *int64    `json:"enabled"`
	IsServer     *int64    `json:"is_server"`
	InstanceID   *string   `json:"instance_id"`
	Port         *int64    `json:"port"`
	ApiKeyHash   []byte    `json:"api_key_hash"`
	RefreshToken []byte    `json:"refresh_token"`
	Salt         []byte    `json:"salt"`
	Capabilities *string   `json:"capabilities"`
	ExpiresAt    time.Time `json:"expires_at"`
}

func (q *Queries) UpsertStandaloneConfig(ctx context.Context, arg UpsertStandaloneConfigParams) error {
	_, err := q.db.ExecContext(ctx, upsertStandaloneConfig,
		arg.Enabled,
		arg.IsServer,
		arg.InstanceID,
		arg.Port,
		arg.ApiKeyHash,
		arg.RefreshToken,
		arg.Salt,
		arg.Capabilities,
		arg.ExpiresAt,
	)
	return err
}
