// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspaces.sql

package sqlc

import (
	"context"
)

const clearActiveWorkspace = `-- name: ClearActiveWorkspace :exec
UPDATE workspaces SET is_active = 0
`

func (q *Queries) ClearActiveWorkspace(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearActiveWorkspace)
	return err
}

const deleteWorkspace = `-- name: DeleteWorkspace :exec
DELETE FROM workspaces WHERE name = ?
`

func (q *Queries) DeleteWorkspace(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteWorkspace, name)
	return err
}

const getActiveWorkspace = `-- name: GetActiveWorkspace :one
SELECT id, name, description, path, is_active, created_at, updated_at FROM workspaces WHERE is_active = 1 LIMIT 1
`

func (q *Queries) GetActiveWorkspace(ctx context.Context) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getActiveWorkspace)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Path,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, name, description, path, is_active, created_at, updated_at FROM workspaces WHERE name = ? LIMIT 1
`

func (q *Queries) GetWorkspace(ctx context.Context, name string) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspace, name)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Path,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertWorkspace = `-- name: InsertWorkspace :one
INSERT INTO workspaces (name, description, path, is_active, created_at, updated_at)
VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, name, description, path, is_active, created_at, updated_at
`

type InsertWorkspaceParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
	Path        *string `json:"path"`
	IsActive    *int64  `json:"is_active"`
}

func (q *Queries) InsertWorkspace(ctx context.Context, arg InsertWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, insertWorkspace,
		arg.Name,
		arg.Description,
		arg.Path,
		arg.IsActive,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Path,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkspaces = `-- name: ListWorkspaces :many
SELECT id, name, description, path, is_active, created_at, updated_at FROM workspaces ORDER BY name ASC
`

func (q *Queries) ListWorkspaces(ctx context.Context) ([]Workspace, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Path,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setActiveWorkspace = `-- name: SetActiveWorkspace :exec
UPDATE workspaces SET is_active = CASE WHEN name = ? THEN 1 ELSE 0 END
`

func (q *Queries) SetActiveWorkspace(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, setActiveWorkspace, name)
	return err
}

const updateWorkspace = `-- name: UpdateWorkspace :exec
UPDATE workspaces SET
    description = ?,
    path = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE name = ?
`

type UpdateWorkspaceParams struct {
	Description *string `json:"description"`
	Path        *string `json:"path"`
	Name        string  `json:"name"`
}

func (q *Queries) UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) error {
	_, err := q.db.ExecContext(ctx, updateWorkspace, arg.Description, arg.Path, arg.Name)
	return err
}

const workspaceExists = `-- name: WorkspaceExists :one
SELECT EXISTS(SELECT 1 FROM workspaces WHERE name = ?) AS exists_flag
`

func (q *Queries) WorkspaceExists(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, workspaceExists, name)
	var exists_flag int64
	err := row.Scan(&exists_flag)
	return exists_flag, err
}
