// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: v1/clonr.proto

package clonrv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClonrService_Ping_FullMethodName                  = "/clonr.v1.ClonrService/Ping"
	ClonrService_SaveRepo_FullMethodName              = "/clonr.v1.ClonrService/SaveRepo"
	ClonrService_RepoExistsByURL_FullMethodName       = "/clonr.v1.ClonrService/RepoExistsByURL"
	ClonrService_RepoExistsByPath_FullMethodName      = "/clonr.v1.ClonrService/RepoExistsByPath"
	ClonrService_InsertRepoIfNotExists_FullMethodName = "/clonr.v1.ClonrService/InsertRepoIfNotExists"
	ClonrService_GetAllRepos_FullMethodName           = "/clonr.v1.ClonrService/GetAllRepos"
	ClonrService_GetRepos_FullMethodName              = "/clonr.v1.ClonrService/GetRepos"
	ClonrService_SetFavoriteByURL_FullMethodName      = "/clonr.v1.ClonrService/SetFavoriteByURL"
	ClonrService_UpdateRepoTimestamp_FullMethodName   = "/clonr.v1.ClonrService/UpdateRepoTimestamp"
	ClonrService_RemoveRepoByURL_FullMethodName       = "/clonr.v1.ClonrService/RemoveRepoByURL"
	ClonrService_GetConfig_FullMethodName             = "/clonr.v1.ClonrService/GetConfig"
	ClonrService_SaveConfig_FullMethodName            = "/clonr.v1.ClonrService/SaveConfig"
	ClonrService_SaveProfile_FullMethodName           = "/clonr.v1.ClonrService/SaveProfile"
	ClonrService_GetProfile_FullMethodName            = "/clonr.v1.ClonrService/GetProfile"
	ClonrService_GetActiveProfile_FullMethodName      = "/clonr.v1.ClonrService/GetActiveProfile"
	ClonrService_SetActiveProfile_FullMethodName      = "/clonr.v1.ClonrService/SetActiveProfile"
	ClonrService_ListProfiles_FullMethodName          = "/clonr.v1.ClonrService/ListProfiles"
	ClonrService_DeleteProfile_FullMethodName         = "/clonr.v1.ClonrService/DeleteProfile"
	ClonrService_ProfileExists_FullMethodName         = "/clonr.v1.ClonrService/ProfileExists"
)

// ClonrServiceClient is the client API for ClonrService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ClonrService defines all database operations for Clonr
type ClonrServiceClient interface {
	// Health check - corresponds to Ping()
	Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	// Repository operations
	SaveRepo(ctx context.Context, in *SaveRepoRequest, opts ...grpc.CallOption) (*SaveRepoResponse, error)
	RepoExistsByURL(ctx context.Context, in *RepoExistsByURLRequest, opts ...grpc.CallOption) (*RepoExistsByURLResponse, error)
	RepoExistsByPath(ctx context.Context, in *RepoExistsByPathRequest, opts ...grpc.CallOption) (*RepoExistsByPathResponse, error)
	InsertRepoIfNotExists(ctx context.Context, in *InsertRepoIfNotExistsRequest, opts ...grpc.CallOption) (*InsertRepoIfNotExistsResponse, error)
	GetAllRepos(ctx context.Context, in *GetAllReposRequest, opts ...grpc.CallOption) (*GetAllReposResponse, error)
	GetRepos(ctx context.Context, in *GetReposRequest, opts ...grpc.CallOption) (*GetReposResponse, error)
	SetFavoriteByURL(ctx context.Context, in *SetFavoriteRequest, opts ...grpc.CallOption) (*SetFavoriteResponse, error)
	UpdateRepoTimestamp(ctx context.Context, in *UpdateRepoTimestampRequest, opts ...grpc.CallOption) (*UpdateRepoTimestampResponse, error)
	RemoveRepoByURL(ctx context.Context, in *RemoveRepoByURLRequest, opts ...grpc.CallOption) (*RemoveRepoByURLResponse, error)
	// Configuration operations
	GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error)
	SaveConfig(ctx context.Context, in *SaveConfigRequest, opts ...grpc.CallOption) (*SaveConfigResponse, error)
	// Profile operations
	SaveProfile(ctx context.Context, in *SaveProfileRequest, opts ...grpc.CallOption) (*SaveProfileResponse, error)
	GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*GetProfileResponse, error)
	GetActiveProfile(ctx context.Context, in *GetActiveProfileRequest, opts ...grpc.CallOption) (*GetActiveProfileResponse, error)
	SetActiveProfile(ctx context.Context, in *SetActiveProfileRequest, opts ...grpc.CallOption) (*SetActiveProfileResponse, error)
	ListProfiles(ctx context.Context, in *ListProfilesRequest, opts ...grpc.CallOption) (*ListProfilesResponse, error)
	DeleteProfile(ctx context.Context, in *DeleteProfileRequest, opts ...grpc.CallOption) (*DeleteProfileResponse, error)
	ProfileExists(ctx context.Context, in *ProfileExistsRequest, opts ...grpc.CallOption) (*ProfileExistsResponse, error)
}

type clonrServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClonrServiceClient(cc grpc.ClientConnInterface) ClonrServiceClient {
	return &clonrServiceClient{cc}
}

func (c *clonrServiceClient) Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ClonrService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clonrServiceClient) SaveRepo(ctx context.Context, in *SaveRepoRequest, opts ...grpc.CallOption) (*SaveRepoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveRepoResponse)
	err := c.cc.Invoke(ctx, ClonrService_SaveRepo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clonrServiceClient) RepoExistsByURL(ctx context.Context, in *RepoExistsByURLRequest, opts ...grpc.CallOption) (*RepoExistsByURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepoExistsByURLResponse)
	err := c.cc.Invoke(ctx, ClonrService_RepoExistsByURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clonrServiceClient) RepoExistsByPath(ctx context.Context, in *RepoExistsByPathRequest, opts ...grpc.CallOption) (*RepoExistsByPathResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepoExistsByPathResponse)
	err := c.cc.Invoke(ctx, ClonrService_RepoExistsByPath_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clonrServiceClient) InsertRepoIfNotExists(ctx context.Context, in *InsertRepoIfNotExistsRequest, opts ...grpc.CallOption) (*InsertRepoIfNotExistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InsertRepoIfNotExistsResponse)
	err := c.cc.Invoke(ctx, ClonrService_InsertRepoIfNotExists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clonrServiceClient) GetAllRepos(ctx context.Context, in *GetAllReposRequest, opts ...grpc.CallOption) (*GetAllReposResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllReposResponse)
	err := c.cc.Invoke(ctx, ClonrService_GetAllRepos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clonrServiceClient) GetRepos(ctx context.Context, in *GetReposRequest, opts ...grpc.CallOption) (*GetReposResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReposResponse)
	err := c.cc.Invoke(ctx, ClonrService_GetRepos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clonrServiceClient) SetFavoriteByURL(ctx context.Context, in *SetFavoriteRequest, opts ...grpc.CallOption) (*SetFavoriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetFavoriteResponse)
	err := c.cc.Invoke(ctx, ClonrService_SetFavoriteByURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clonrServiceClient) UpdateRepoTimestamp(ctx context.Context, in *UpdateRepoTimestampRequest, opts ...grpc.CallOption) (*UpdateRepoTimestampResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRepoTimestampResponse)
	err := c.cc.Invoke(ctx, ClonrService_UpdateRepoTimestamp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clonrServiceClient) RemoveRepoByURL(ctx context.Context, in *RemoveRepoByURLRequest, opts ...grpc.CallOption) (*RemoveRepoByURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveRepoByURLResponse)
	err := c.cc.Invoke(ctx, ClonrService_RemoveRepoByURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clonrServiceClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConfigResponse)
	err := c.cc.Invoke(ctx, ClonrService_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clonrServiceClient) SaveConfig(ctx context.Context, in *SaveConfigRequest, opts ...grpc.CallOption) (*SaveConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveConfigResponse)
	err := c.cc.Invoke(ctx, ClonrService_SaveConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clonrServiceClient) SaveProfile(ctx context.Context, in *SaveProfileRequest, opts ...grpc.CallOption) (*SaveProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveProfileResponse)
	err := c.cc.Invoke(ctx, ClonrService_SaveProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clonrServiceClient) GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*GetProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProfileResponse)
	err := c.cc.Invoke(ctx, ClonrService_GetProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clonrServiceClient) GetActiveProfile(ctx context.Context, in *GetActiveProfileRequest, opts ...grpc.CallOption) (*GetActiveProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetActiveProfileResponse)
	err := c.cc.Invoke(ctx, ClonrService_GetActiveProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clonrServiceClient) SetActiveProfile(ctx context.Context, in *SetActiveProfileRequest, opts ...grpc.CallOption) (*SetActiveProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetActiveProfileResponse)
	err := c.cc.Invoke(ctx, ClonrService_SetActiveProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clonrServiceClient) ListProfiles(ctx context.Context, in *ListProfilesRequest, opts ...grpc.CallOption) (*ListProfilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProfilesResponse)
	err := c.cc.Invoke(ctx, ClonrService_ListProfiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clonrServiceClient) DeleteProfile(ctx context.Context, in *DeleteProfileRequest, opts ...grpc.CallOption) (*DeleteProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteProfileResponse)
	err := c.cc.Invoke(ctx, ClonrService_DeleteProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clonrServiceClient) ProfileExists(ctx context.Context, in *ProfileExistsRequest, opts ...grpc.CallOption) (*ProfileExistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProfileExistsResponse)
	err := c.cc.Invoke(ctx, ClonrService_ProfileExists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClonrServiceServer is the server API for ClonrService service.
// All implementations must embed UnimplementedClonrServiceServer
// for forward compatibility.
//
// ClonrService defines all database operations for Clonr
type ClonrServiceServer interface {
	// Health check - corresponds to Ping()
	Ping(context.Context, *Empty) (*Empty, error)
	// Repository operations
	SaveRepo(context.Context, *SaveRepoRequest) (*SaveRepoResponse, error)
	RepoExistsByURL(context.Context, *RepoExistsByURLRequest) (*RepoExistsByURLResponse, error)
	RepoExistsByPath(context.Context, *RepoExistsByPathRequest) (*RepoExistsByPathResponse, error)
	InsertRepoIfNotExists(context.Context, *InsertRepoIfNotExistsRequest) (*InsertRepoIfNotExistsResponse, error)
	GetAllRepos(context.Context, *GetAllReposRequest) (*GetAllReposResponse, error)
	GetRepos(context.Context, *GetReposRequest) (*GetReposResponse, error)
	SetFavoriteByURL(context.Context, *SetFavoriteRequest) (*SetFavoriteResponse, error)
	UpdateRepoTimestamp(context.Context, *UpdateRepoTimestampRequest) (*UpdateRepoTimestampResponse, error)
	RemoveRepoByURL(context.Context, *RemoveRepoByURLRequest) (*RemoveRepoByURLResponse, error)
	// Configuration operations
	GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error)
	SaveConfig(context.Context, *SaveConfigRequest) (*SaveConfigResponse, error)
	// Profile operations
	SaveProfile(context.Context, *SaveProfileRequest) (*SaveProfileResponse, error)
	GetProfile(context.Context, *GetProfileRequest) (*GetProfileResponse, error)
	GetActiveProfile(context.Context, *GetActiveProfileRequest) (*GetActiveProfileResponse, error)
	SetActiveProfile(context.Context, *SetActiveProfileRequest) (*SetActiveProfileResponse, error)
	ListProfiles(context.Context, *ListProfilesRequest) (*ListProfilesResponse, error)
	DeleteProfile(context.Context, *DeleteProfileRequest) (*DeleteProfileResponse, error)
	ProfileExists(context.Context, *ProfileExistsRequest) (*ProfileExistsResponse, error)
	mustEmbedUnimplementedClonrServiceServer()
}

// UnimplementedClonrServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClonrServiceServer struct{}

func (UnimplementedClonrServiceServer) Ping(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedClonrServiceServer) SaveRepo(context.Context, *SaveRepoRequest) (*SaveRepoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveRepo not implemented")
}
func (UnimplementedClonrServiceServer) RepoExistsByURL(context.Context, *RepoExistsByURLRequest) (*RepoExistsByURLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RepoExistsByURL not implemented")
}
func (UnimplementedClonrServiceServer) RepoExistsByPath(context.Context, *RepoExistsByPathRequest) (*RepoExistsByPathResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RepoExistsByPath not implemented")
}
func (UnimplementedClonrServiceServer) InsertRepoIfNotExists(context.Context, *InsertRepoIfNotExistsRequest) (*InsertRepoIfNotExistsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InsertRepoIfNotExists not implemented")
}
func (UnimplementedClonrServiceServer) GetAllRepos(context.Context, *GetAllReposRequest) (*GetAllReposResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllRepos not implemented")
}
func (UnimplementedClonrServiceServer) GetRepos(context.Context, *GetReposRequest) (*GetReposResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRepos not implemented")
}
func (UnimplementedClonrServiceServer) SetFavoriteByURL(context.Context, *SetFavoriteRequest) (*SetFavoriteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetFavoriteByURL not implemented")
}
func (UnimplementedClonrServiceServer) UpdateRepoTimestamp(context.Context, *UpdateRepoTimestampRequest) (*UpdateRepoTimestampResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRepoTimestamp not implemented")
}
func (UnimplementedClonrServiceServer) RemoveRepoByURL(context.Context, *RemoveRepoByURLRequest) (*RemoveRepoByURLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveRepoByURL not implemented")
}
func (UnimplementedClonrServiceServer) GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedClonrServiceServer) SaveConfig(context.Context, *SaveConfigRequest) (*SaveConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveConfig not implemented")
}
func (UnimplementedClonrServiceServer) SaveProfile(context.Context, *SaveProfileRequest) (*SaveProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveProfile not implemented")
}
func (UnimplementedClonrServiceServer) GetProfile(context.Context, *GetProfileRequest) (*GetProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProfile not implemented")
}
func (UnimplementedClonrServiceServer) GetActiveProfile(context.Context, *GetActiveProfileRequest) (*GetActiveProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActiveProfile not implemented")
}
func (UnimplementedClonrServiceServer) SetActiveProfile(context.Context, *SetActiveProfileRequest) (*SetActiveProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetActiveProfile not implemented")
}
func (UnimplementedClonrServiceServer) ListProfiles(context.Context, *ListProfilesRequest) (*ListProfilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProfiles not implemented")
}
func (UnimplementedClonrServiceServer) DeleteProfile(context.Context, *DeleteProfileRequest) (*DeleteProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteProfile not implemented")
}
func (UnimplementedClonrServiceServer) ProfileExists(context.Context, *ProfileExistsRequest) (*ProfileExistsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProfileExists not implemented")
}
func (UnimplementedClonrServiceServer) mustEmbedUnimplementedClonrServiceServer() {}
func (UnimplementedClonrServiceServer) testEmbeddedByValue()                      {}

// UnsafeClonrServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClonrServiceServer will
// result in compilation errors.
type UnsafeClonrServiceServer interface {
	mustEmbedUnimplementedClonrServiceServer()
}

func RegisterClonrServiceServer(s grpc.ServiceRegistrar, srv ClonrServiceServer) {
	// If the following call panics, it indicates UnimplementedClonrServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClonrService_ServiceDesc, srv)
}

func _ClonrService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClonrServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClonrService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClonrServiceServer).Ping(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClonrService_SaveRepo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveRepoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClonrServiceServer).SaveRepo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClonrService_SaveRepo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClonrServiceServer).SaveRepo(ctx, req.(*SaveRepoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClonrService_RepoExistsByURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepoExistsByURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClonrServiceServer).RepoExistsByURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClonrService_RepoExistsByURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClonrServiceServer).RepoExistsByURL(ctx, req.(*RepoExistsByURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClonrService_RepoExistsByPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepoExistsByPathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClonrServiceServer).RepoExistsByPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClonrService_RepoExistsByPath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClonrServiceServer).RepoExistsByPath(ctx, req.(*RepoExistsByPathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClonrService_InsertRepoIfNotExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertRepoIfNotExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClonrServiceServer).InsertRepoIfNotExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClonrService_InsertRepoIfNotExists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClonrServiceServer).InsertRepoIfNotExists(ctx, req.(*InsertRepoIfNotExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClonrService_GetAllRepos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllReposRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClonrServiceServer).GetAllRepos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClonrService_GetAllRepos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClonrServiceServer).GetAllRepos(ctx, req.(*GetAllReposRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClonrService_GetRepos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReposRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClonrServiceServer).GetRepos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClonrService_GetRepos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClonrServiceServer).GetRepos(ctx, req.(*GetReposRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClonrService_SetFavoriteByURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetFavoriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClonrServiceServer).SetFavoriteByURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClonrService_SetFavoriteByURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClonrServiceServer).SetFavoriteByURL(ctx, req.(*SetFavoriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClonrService_UpdateRepoTimestamp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRepoTimestampRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClonrServiceServer).UpdateRepoTimestamp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClonrService_UpdateRepoTimestamp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClonrServiceServer).UpdateRepoTimestamp(ctx, req.(*UpdateRepoTimestampRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClonrService_RemoveRepoByURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRepoByURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClonrServiceServer).RemoveRepoByURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClonrService_RemoveRepoByURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClonrServiceServer).RemoveRepoByURL(ctx, req.(*RemoveRepoByURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClonrService_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClonrServiceServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClonrService_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClonrServiceServer).GetConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClonrService_SaveConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClonrServiceServer).SaveConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClonrService_SaveConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClonrServiceServer).SaveConfig(ctx, req.(*SaveConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClonrService_SaveProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClonrServiceServer).SaveProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClonrService_SaveProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClonrServiceServer).SaveProfile(ctx, req.(*SaveProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClonrService_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClonrServiceServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClonrService_GetProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClonrServiceServer).GetProfile(ctx, req.(*GetProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClonrService_GetActiveProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActiveProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClonrServiceServer).GetActiveProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClonrService_GetActiveProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClonrServiceServer).GetActiveProfile(ctx, req.(*GetActiveProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClonrService_SetActiveProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetActiveProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClonrServiceServer).SetActiveProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClonrService_SetActiveProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClonrServiceServer).SetActiveProfile(ctx, req.(*SetActiveProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClonrService_ListProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProfilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClonrServiceServer).ListProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClonrService_ListProfiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClonrServiceServer).ListProfiles(ctx, req.(*ListProfilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClonrService_DeleteProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClonrServiceServer).DeleteProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClonrService_DeleteProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClonrServiceServer).DeleteProfile(ctx, req.(*DeleteProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClonrService_ProfileExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClonrServiceServer).ProfileExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClonrService_ProfileExists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClonrServiceServer).ProfileExists(ctx, req.(*ProfileExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClonrService_ServiceDesc is the grpc.ServiceDesc for ClonrService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClonrService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clonr.v1.ClonrService",
	HandlerType: (*ClonrServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _ClonrService_Ping_Handler,
		},
		{
			MethodName: "SaveRepo",
			Handler:    _ClonrService_SaveRepo_Handler,
		},
		{
			MethodName: "RepoExistsByURL",
			Handler:    _ClonrService_RepoExistsByURL_Handler,
		},
		{
			MethodName: "RepoExistsByPath",
			Handler:    _ClonrService_RepoExistsByPath_Handler,
		},
		{
			MethodName: "InsertRepoIfNotExists",
			Handler:    _ClonrService_InsertRepoIfNotExists_Handler,
		},
		{
			MethodName: "GetAllRepos",
			Handler:    _ClonrService_GetAllRepos_Handler,
		},
		{
			MethodName: "GetRepos",
			Handler:    _ClonrService_GetRepos_Handler,
		},
		{
			MethodName: "SetFavoriteByURL",
			Handler:    _ClonrService_SetFavoriteByURL_Handler,
		},
		{
			MethodName: "UpdateRepoTimestamp",
			Handler:    _ClonrService_UpdateRepoTimestamp_Handler,
		},
		{
			MethodName: "RemoveRepoByURL",
			Handler:    _ClonrService_RemoveRepoByURL_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _ClonrService_GetConfig_Handler,
		},
		{
			MethodName: "SaveConfig",
			Handler:    _ClonrService_SaveConfig_Handler,
		},
		{
			MethodName: "SaveProfile",
			Handler:    _ClonrService_SaveProfile_Handler,
		},
		{
			MethodName: "GetProfile",
			Handler:    _ClonrService_GetProfile_Handler,
		},
		{
			MethodName: "GetActiveProfile",
			Handler:    _ClonrService_GetActiveProfile_Handler,
		},
		{
			MethodName: "SetActiveProfile",
			Handler:    _ClonrService_SetActiveProfile_Handler,
		},
		{
			MethodName: "ListProfiles",
			Handler:    _ClonrService_ListProfiles_Handler,
		},
		{
			MethodName: "DeleteProfile",
			Handler:    _ClonrService_DeleteProfile_Handler,
		},
		{
			MethodName: "ProfileExists",
			Handler:    _ClonrService_ProfileExists_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/clonr.proto",
}
