// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/v1/clonr.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_v1_clonr_proto protoreflect.FileDescriptor

const file_proto_v1_clonr_proto_rawDesc = "" +
	"\n" +
	"\x14proto/v1/clonr.proto\x12\bclonr.v1\x1a\x15proto/v1/common.proto\x1a\x19proto/v1/repository.proto\x1a\x15proto/v1/config.proto2\xc3\a\n" +
	"\fClonrService\x12(\n" +
	"\x04Ping\x12\x0f.clonr.v1.Empty\x1a\x0f.clonr.v1.Empty\x12A\n" +
	"\bSaveRepo\x12\x19.clonr.v1.SaveRepoRequest\x1a\x1a.clonr.v1.SaveRepoResponse\x12V\n" +
	"\x0fRepoExistsByURL\x12 .clonr.v1.RepoExistsByURLRequest\x1a!.clonr.v1.RepoExistsByURLResponse\x12Y\n" +
	"\x10RepoExistsByPath\x12!.clonr.v1.RepoExistsByPathRequest\x1a\".clonr.v1.RepoExistsByPathResponse\x12h\n" +
	"\x15InsertRepoIfNotExists\x12&.clonr.v1.InsertRepoIfNotExistsRequest\x1a'.clonr.v1.InsertRepoIfNotExistsResponse\x12J\n" +
	"\vGetAllRepos\x12\x1c.clonr.v1.GetAllReposRequest\x1a\x1d.clonr.v1.GetAllReposResponse\x12A\n" +
	"\bGetRepos\x12\x19.clonr.v1.GetReposRequest\x1a\x1a.clonr.v1.GetReposResponse\x12O\n" +
	"\x10SetFavoriteByURL\x12\x1c.clonr.v1.SetFavoriteRequest\x1a\x1d.clonr.v1.SetFavoriteResponse\x12b\n" +
	"\x13UpdateRepoTimestamp\x12$.clonr.v1.UpdateRepoTimestampRequest\x1a%.clonr.v1.UpdateRepoTimestampResponse\x12V\n" +
	"\x0fRemoveRepoByURL\x12 .clonr.v1.RemoveRepoByURLRequest\x1a!.clonr.v1.RemoveRepoByURLResponse\x12D\n" +
	"\tGetConfig\x12\x1a.clonr.v1.GetConfigRequest\x1a\x1b.clonr.v1.GetConfigResponse\x12G\n" +
	"\n" +
	"SaveConfig\x12\x1b.clonr.v1.SaveConfigRequest\x1a\x1c.clonr.v1.SaveConfigResponseB%Z#github.com/inovacc/clonr/pkg/api/v1b\x06proto3"

var file_proto_v1_clonr_proto_goTypes = []any{
	(*Empty)(nil),                         // 0: clonr.v1.Empty
	(*SaveRepoRequest)(nil),               // 1: clonr.v1.SaveRepoRequest
	(*RepoExistsByURLRequest)(nil),        // 2: clonr.v1.RepoExistsByURLRequest
	(*RepoExistsByPathRequest)(nil),       // 3: clonr.v1.RepoExistsByPathRequest
	(*InsertRepoIfNotExistsRequest)(nil),  // 4: clonr.v1.InsertRepoIfNotExistsRequest
	(*GetAllReposRequest)(nil),            // 5: clonr.v1.GetAllReposRequest
	(*GetReposRequest)(nil),               // 6: clonr.v1.GetReposRequest
	(*SetFavoriteRequest)(nil),            // 7: clonr.v1.SetFavoriteRequest
	(*UpdateRepoTimestampRequest)(nil),    // 8: clonr.v1.UpdateRepoTimestampRequest
	(*RemoveRepoByURLRequest)(nil),        // 9: clonr.v1.RemoveRepoByURLRequest
	(*GetConfigRequest)(nil),              // 10: clonr.v1.GetConfigRequest
	(*SaveConfigRequest)(nil),             // 11: clonr.v1.SaveConfigRequest
	(*SaveRepoResponse)(nil),              // 12: clonr.v1.SaveRepoResponse
	(*RepoExistsByURLResponse)(nil),       // 13: clonr.v1.RepoExistsByURLResponse
	(*RepoExistsByPathResponse)(nil),      // 14: clonr.v1.RepoExistsByPathResponse
	(*InsertRepoIfNotExistsResponse)(nil), // 15: clonr.v1.InsertRepoIfNotExistsResponse
	(*GetAllReposResponse)(nil),           // 16: clonr.v1.GetAllReposResponse
	(*GetReposResponse)(nil),              // 17: clonr.v1.GetReposResponse
	(*SetFavoriteResponse)(nil),           // 18: clonr.v1.SetFavoriteResponse
	(*UpdateRepoTimestampResponse)(nil),   // 19: clonr.v1.UpdateRepoTimestampResponse
	(*RemoveRepoByURLResponse)(nil),       // 20: clonr.v1.RemoveRepoByURLResponse
	(*GetConfigResponse)(nil),             // 21: clonr.v1.GetConfigResponse
	(*SaveConfigResponse)(nil),            // 22: clonr.v1.SaveConfigResponse
}
var file_proto_v1_clonr_proto_depIdxs = []int32{
	0,  // 0: clonr.v1.ClonrService.Ping:input_type -> clonr.v1.Empty
	1,  // 1: clonr.v1.ClonrService.SaveRepo:input_type -> clonr.v1.SaveRepoRequest
	2,  // 2: clonr.v1.ClonrService.RepoExistsByURL:input_type -> clonr.v1.RepoExistsByURLRequest
	3,  // 3: clonr.v1.ClonrService.RepoExistsByPath:input_type -> clonr.v1.RepoExistsByPathRequest
	4,  // 4: clonr.v1.ClonrService.InsertRepoIfNotExists:input_type -> clonr.v1.InsertRepoIfNotExistsRequest
	5,  // 5: clonr.v1.ClonrService.GetAllRepos:input_type -> clonr.v1.GetAllReposRequest
	6,  // 6: clonr.v1.ClonrService.GetRepos:input_type -> clonr.v1.GetReposRequest
	7,  // 7: clonr.v1.ClonrService.SetFavoriteByURL:input_type -> clonr.v1.SetFavoriteRequest
	8,  // 8: clonr.v1.ClonrService.UpdateRepoTimestamp:input_type -> clonr.v1.UpdateRepoTimestampRequest
	9,  // 9: clonr.v1.ClonrService.RemoveRepoByURL:input_type -> clonr.v1.RemoveRepoByURLRequest
	10, // 10: clonr.v1.ClonrService.GetConfig:input_type -> clonr.v1.GetConfigRequest
	11, // 11: clonr.v1.ClonrService.SaveConfig:input_type -> clonr.v1.SaveConfigRequest
	0,  // 12: clonr.v1.ClonrService.Ping:output_type -> clonr.v1.Empty
	12, // 13: clonr.v1.ClonrService.SaveRepo:output_type -> clonr.v1.SaveRepoResponse
	13, // 14: clonr.v1.ClonrService.RepoExistsByURL:output_type -> clonr.v1.RepoExistsByURLResponse
	14, // 15: clonr.v1.ClonrService.RepoExistsByPath:output_type -> clonr.v1.RepoExistsByPathResponse
	15, // 16: clonr.v1.ClonrService.InsertRepoIfNotExists:output_type -> clonr.v1.InsertRepoIfNotExistsResponse
	16, // 17: clonr.v1.ClonrService.GetAllRepos:output_type -> clonr.v1.GetAllReposResponse
	17, // 18: clonr.v1.ClonrService.GetRepos:output_type -> clonr.v1.GetReposResponse
	18, // 19: clonr.v1.ClonrService.SetFavoriteByURL:output_type -> clonr.v1.SetFavoriteResponse
	19, // 20: clonr.v1.ClonrService.UpdateRepoTimestamp:output_type -> clonr.v1.UpdateRepoTimestampResponse
	20, // 21: clonr.v1.ClonrService.RemoveRepoByURL:output_type -> clonr.v1.RemoveRepoByURLResponse
	21, // 22: clonr.v1.ClonrService.GetConfig:output_type -> clonr.v1.GetConfigResponse
	22, // 23: clonr.v1.ClonrService.SaveConfig:output_type -> clonr.v1.SaveConfigResponse
	12, // [12:24] is the sub-list for method output_type
	0,  // [0:12] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto_v1_clonr_proto_init() }
func file_proto_v1_clonr_proto_init() {
	if File_proto_v1_clonr_proto != nil {
		return
	}
	file_proto_v1_common_proto_init()
	file_proto_v1_repository_proto_init()
	file_proto_v1_config_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_clonr_proto_rawDesc), len(file_proto_v1_clonr_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_clonr_proto_goTypes,
		DependencyIndexes: file_proto_v1_clonr_proto_depIdxs,
	}.Build()
	File_proto_v1_clonr_proto = out.File
	file_proto_v1_clonr_proto_goTypes = nil
	file_proto_v1_clonr_proto_depIdxs = nil
}
