// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/v1/repository.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Repository represents a managed Git repository
type Repository struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid           string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Favorite      bool                   `protobuf:"varint,5,opt,name=favorite,proto3" json:"favorite,omitempty"`
	ClonedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=cloned_at,json=clonedAt,proto3" json:"cloned_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	LastChecked   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=last_checked,json=lastChecked,proto3" json:"last_checked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Repository) Reset() {
	*x = Repository{}
	mi := &file_proto_v1_repository_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Repository) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Repository) ProtoMessage() {}

func (x *Repository) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_repository_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Repository.ProtoReflect.Descriptor instead.
func (*Repository) Descriptor() ([]byte, []int) {
	return file_proto_v1_repository_proto_rawDescGZIP(), []int{0}
}

func (x *Repository) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Repository) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Repository) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Repository) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Repository) GetFavorite() bool {
	if x != nil {
		return x.Favorite
	}
	return false
}

func (x *Repository) GetClonedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ClonedAt
	}
	return nil
}

func (x *Repository) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Repository) GetLastChecked() *timestamppb.Timestamp {
	if x != nil {
		return x.LastChecked
	}
	return nil
}

// SaveRepo RPC messages
type SaveRepoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveRepoRequest) Reset() {
	*x = SaveRepoRequest{}
	mi := &file_proto_v1_repository_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveRepoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveRepoRequest) ProtoMessage() {}

func (x *SaveRepoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_repository_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveRepoRequest.ProtoReflect.Descriptor instead.
func (*SaveRepoRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_repository_proto_rawDescGZIP(), []int{1}
}

func (x *SaveRepoRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *SaveRepoRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type SaveRepoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveRepoResponse) Reset() {
	*x = SaveRepoResponse{}
	mi := &file_proto_v1_repository_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveRepoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveRepoResponse) ProtoMessage() {}

func (x *SaveRepoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_repository_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveRepoResponse.ProtoReflect.Descriptor instead.
func (*SaveRepoResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_repository_proto_rawDescGZIP(), []int{2}
}

func (x *SaveRepoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// RepoExistsByURL RPC messages
type RepoExistsByURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepoExistsByURLRequest) Reset() {
	*x = RepoExistsByURLRequest{}
	mi := &file_proto_v1_repository_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepoExistsByURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepoExistsByURLRequest) ProtoMessage() {}

func (x *RepoExistsByURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_repository_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepoExistsByURLRequest.ProtoReflect.Descriptor instead.
func (*RepoExistsByURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_repository_proto_rawDescGZIP(), []int{3}
}

func (x *RepoExistsByURLRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type RepoExistsByURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepoExistsByURLResponse) Reset() {
	*x = RepoExistsByURLResponse{}
	mi := &file_proto_v1_repository_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepoExistsByURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepoExistsByURLResponse) ProtoMessage() {}

func (x *RepoExistsByURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_repository_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepoExistsByURLResponse.ProtoReflect.Descriptor instead.
func (*RepoExistsByURLResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_repository_proto_rawDescGZIP(), []int{4}
}

func (x *RepoExistsByURLResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

// RepoExistsByPath RPC messages
type RepoExistsByPathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepoExistsByPathRequest) Reset() {
	*x = RepoExistsByPathRequest{}
	mi := &file_proto_v1_repository_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepoExistsByPathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepoExistsByPathRequest) ProtoMessage() {}

func (x *RepoExistsByPathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_repository_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepoExistsByPathRequest.ProtoReflect.Descriptor instead.
func (*RepoExistsByPathRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_repository_proto_rawDescGZIP(), []int{5}
}

func (x *RepoExistsByPathRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type RepoExistsByPathResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepoExistsByPathResponse) Reset() {
	*x = RepoExistsByPathResponse{}
	mi := &file_proto_v1_repository_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepoExistsByPathResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepoExistsByPathResponse) ProtoMessage() {}

func (x *RepoExistsByPathResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_repository_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepoExistsByPathResponse.ProtoReflect.Descriptor instead.
func (*RepoExistsByPathResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_repository_proto_rawDescGZIP(), []int{6}
}

func (x *RepoExistsByPathResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

// InsertRepoIfNotExists RPC messages
type InsertRepoIfNotExistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertRepoIfNotExistsRequest) Reset() {
	*x = InsertRepoIfNotExistsRequest{}
	mi := &file_proto_v1_repository_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertRepoIfNotExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertRepoIfNotExistsRequest) ProtoMessage() {}

func (x *InsertRepoIfNotExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_repository_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertRepoIfNotExistsRequest.ProtoReflect.Descriptor instead.
func (*InsertRepoIfNotExistsRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_repository_proto_rawDescGZIP(), []int{7}
}

func (x *InsertRepoIfNotExistsRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *InsertRepoIfNotExistsRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type InsertRepoIfNotExistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inserted      bool                   `protobuf:"varint,1,opt,name=inserted,proto3" json:"inserted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertRepoIfNotExistsResponse) Reset() {
	*x = InsertRepoIfNotExistsResponse{}
	mi := &file_proto_v1_repository_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertRepoIfNotExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertRepoIfNotExistsResponse) ProtoMessage() {}

func (x *InsertRepoIfNotExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_repository_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertRepoIfNotExistsResponse.ProtoReflect.Descriptor instead.
func (*InsertRepoIfNotExistsResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_repository_proto_rawDescGZIP(), []int{8}
}

func (x *InsertRepoIfNotExistsResponse) GetInserted() bool {
	if x != nil {
		return x.Inserted
	}
	return false
}

// GetAllRepos RPC messages
type GetAllReposRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllReposRequest) Reset() {
	*x = GetAllReposRequest{}
	mi := &file_proto_v1_repository_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllReposRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllReposRequest) ProtoMessage() {}

func (x *GetAllReposRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_repository_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllReposRequest.ProtoReflect.Descriptor instead.
func (*GetAllReposRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_repository_proto_rawDescGZIP(), []int{9}
}

type GetAllReposResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repositories  []*Repository          `protobuf:"bytes,1,rep,name=repositories,proto3" json:"repositories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllReposResponse) Reset() {
	*x = GetAllReposResponse{}
	mi := &file_proto_v1_repository_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllReposResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllReposResponse) ProtoMessage() {}

func (x *GetAllReposResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_repository_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllReposResponse.ProtoReflect.Descriptor instead.
func (*GetAllReposResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_repository_proto_rawDescGZIP(), []int{10}
}

func (x *GetAllReposResponse) GetRepositories() []*Repository {
	if x != nil {
		return x.Repositories
	}
	return nil
}

// GetRepos RPC messages
type GetReposRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FavoritesOnly bool                   `protobuf:"varint,1,opt,name=favorites_only,json=favoritesOnly,proto3" json:"favorites_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReposRequest) Reset() {
	*x = GetReposRequest{}
	mi := &file_proto_v1_repository_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReposRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReposRequest) ProtoMessage() {}

func (x *GetReposRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_repository_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReposRequest.ProtoReflect.Descriptor instead.
func (*GetReposRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_repository_proto_rawDescGZIP(), []int{11}
}

func (x *GetReposRequest) GetFavoritesOnly() bool {
	if x != nil {
		return x.FavoritesOnly
	}
	return false
}

type GetReposResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repositories  []*Repository          `protobuf:"bytes,1,rep,name=repositories,proto3" json:"repositories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReposResponse) Reset() {
	*x = GetReposResponse{}
	mi := &file_proto_v1_repository_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReposResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReposResponse) ProtoMessage() {}

func (x *GetReposResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_repository_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReposResponse.ProtoReflect.Descriptor instead.
func (*GetReposResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_repository_proto_rawDescGZIP(), []int{12}
}

func (x *GetReposResponse) GetRepositories() []*Repository {
	if x != nil {
		return x.Repositories
	}
	return nil
}

// SetFavorite RPC messages
type SetFavoriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Favorite      bool                   `protobuf:"varint,2,opt,name=favorite,proto3" json:"favorite,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetFavoriteRequest) Reset() {
	*x = SetFavoriteRequest{}
	mi := &file_proto_v1_repository_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFavoriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFavoriteRequest) ProtoMessage() {}

func (x *SetFavoriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_repository_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFavoriteRequest.ProtoReflect.Descriptor instead.
func (*SetFavoriteRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_repository_proto_rawDescGZIP(), []int{13}
}

func (x *SetFavoriteRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *SetFavoriteRequest) GetFavorite() bool {
	if x != nil {
		return x.Favorite
	}
	return false
}

type SetFavoriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetFavoriteResponse) Reset() {
	*x = SetFavoriteResponse{}
	mi := &file_proto_v1_repository_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFavoriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFavoriteResponse) ProtoMessage() {}

func (x *SetFavoriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_repository_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFavoriteResponse.ProtoReflect.Descriptor instead.
func (*SetFavoriteResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_repository_proto_rawDescGZIP(), []int{14}
}

func (x *SetFavoriteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// UpdateRepoTimestamp RPC messages
type UpdateRepoTimestampRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRepoTimestampRequest) Reset() {
	*x = UpdateRepoTimestampRequest{}
	mi := &file_proto_v1_repository_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRepoTimestampRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRepoTimestampRequest) ProtoMessage() {}

func (x *UpdateRepoTimestampRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_repository_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRepoTimestampRequest.ProtoReflect.Descriptor instead.
func (*UpdateRepoTimestampRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_repository_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateRepoTimestampRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type UpdateRepoTimestampResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRepoTimestampResponse) Reset() {
	*x = UpdateRepoTimestampResponse{}
	mi := &file_proto_v1_repository_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRepoTimestampResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRepoTimestampResponse) ProtoMessage() {}

func (x *UpdateRepoTimestampResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_repository_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRepoTimestampResponse.ProtoReflect.Descriptor instead.
func (*UpdateRepoTimestampResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_repository_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateRepoTimestampResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// RemoveRepoByURL RPC messages
type RemoveRepoByURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRepoByURLRequest) Reset() {
	*x = RemoveRepoByURLRequest{}
	mi := &file_proto_v1_repository_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRepoByURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRepoByURLRequest) ProtoMessage() {}

func (x *RemoveRepoByURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_repository_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRepoByURLRequest.ProtoReflect.Descriptor instead.
func (*RemoveRepoByURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_repository_proto_rawDescGZIP(), []int{17}
}

func (x *RemoveRepoByURLRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type RemoveRepoByURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRepoByURLResponse) Reset() {
	*x = RemoveRepoByURLResponse{}
	mi := &file_proto_v1_repository_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRepoByURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRepoByURLResponse) ProtoMessage() {}

func (x *RemoveRepoByURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_repository_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRepoByURLResponse.ProtoReflect.Descriptor instead.
func (*RemoveRepoByURLResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_repository_proto_rawDescGZIP(), []int{18}
}

func (x *RemoveRepoByURLResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_v1_repository_proto protoreflect.FileDescriptor

const file_proto_v1_repository_proto_rawDesc = "" +
	"\n" +
	"\x19proto/v1/repository.proto\x12\bclonr.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa3\x02\n" +
	"\n" +
	"Repository\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x1a\n" +
	"\bfavorite\x18\x05 \x01(\bR\bfavorite\x127\n" +
	"\tcloned_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bclonedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12=\n" +
	"\flast_checked\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vlastChecked\"7\n" +
	"\x0fSaveRepoRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\",\n" +
	"\x10SaveRepoResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"*\n" +
	"\x16RepoExistsByURLRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"1\n" +
	"\x17RepoExistsByURLResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\"-\n" +
	"\x17RepoExistsByPathRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"2\n" +
	"\x18RepoExistsByPathResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\"D\n" +
	"\x1cInsertRepoIfNotExistsRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\";\n" +
	"\x1dInsertRepoIfNotExistsResponse\x12\x1a\n" +
	"\binserted\x18\x01 \x01(\bR\binserted\"\x14\n" +
	"\x12GetAllReposRequest\"O\n" +
	"\x13GetAllReposResponse\x128\n" +
	"\frepositories\x18\x01 \x03(\v2\x14.clonr.v1.RepositoryR\frepositories\"8\n" +
	"\x0fGetReposRequest\x12%\n" +
	"\x0efavorites_only\x18\x01 \x01(\bR\rfavoritesOnly\"L\n" +
	"\x10GetReposResponse\x128\n" +
	"\frepositories\x18\x01 \x03(\v2\x14.clonr.v1.RepositoryR\frepositories\"B\n" +
	"\x12SetFavoriteRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1a\n" +
	"\bfavorite\x18\x02 \x01(\bR\bfavorite\"/\n" +
	"\x13SetFavoriteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\".\n" +
	"\x1aUpdateRepoTimestampRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"7\n" +
	"\x1bUpdateRepoTimestampResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"*\n" +
	"\x16RemoveRepoByURLRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"3\n" +
	"\x17RemoveRepoByURLResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccessB%Z#github.com/inovacc/clonr/pkg/api/v1b\x06proto3"

var (
	file_proto_v1_repository_proto_rawDescOnce sync.Once
	file_proto_v1_repository_proto_rawDescData []byte
)

func file_proto_v1_repository_proto_rawDescGZIP() []byte {
	file_proto_v1_repository_proto_rawDescOnce.Do(func() {
		file_proto_v1_repository_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_repository_proto_rawDesc), len(file_proto_v1_repository_proto_rawDesc)))
	})
	return file_proto_v1_repository_proto_rawDescData
}

var file_proto_v1_repository_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_v1_repository_proto_goTypes = []any{
	(*Repository)(nil),                    // 0: clonr.v1.Repository
	(*SaveRepoRequest)(nil),               // 1: clonr.v1.SaveRepoRequest
	(*SaveRepoResponse)(nil),              // 2: clonr.v1.SaveRepoResponse
	(*RepoExistsByURLRequest)(nil),        // 3: clonr.v1.RepoExistsByURLRequest
	(*RepoExistsByURLResponse)(nil),       // 4: clonr.v1.RepoExistsByURLResponse
	(*RepoExistsByPathRequest)(nil),       // 5: clonr.v1.RepoExistsByPathRequest
	(*RepoExistsByPathResponse)(nil),      // 6: clonr.v1.RepoExistsByPathResponse
	(*InsertRepoIfNotExistsRequest)(nil),  // 7: clonr.v1.InsertRepoIfNotExistsRequest
	(*InsertRepoIfNotExistsResponse)(nil), // 8: clonr.v1.InsertRepoIfNotExistsResponse
	(*GetAllReposRequest)(nil),            // 9: clonr.v1.GetAllReposRequest
	(*GetAllReposResponse)(nil),           // 10: clonr.v1.GetAllReposResponse
	(*GetReposRequest)(nil),               // 11: clonr.v1.GetReposRequest
	(*GetReposResponse)(nil),              // 12: clonr.v1.GetReposResponse
	(*SetFavoriteRequest)(nil),            // 13: clonr.v1.SetFavoriteRequest
	(*SetFavoriteResponse)(nil),           // 14: clonr.v1.SetFavoriteResponse
	(*UpdateRepoTimestampRequest)(nil),    // 15: clonr.v1.UpdateRepoTimestampRequest
	(*UpdateRepoTimestampResponse)(nil),   // 16: clonr.v1.UpdateRepoTimestampResponse
	(*RemoveRepoByURLRequest)(nil),        // 17: clonr.v1.RemoveRepoByURLRequest
	(*RemoveRepoByURLResponse)(nil),       // 18: clonr.v1.RemoveRepoByURLResponse
	(*timestamppb.Timestamp)(nil),         // 19: google.protobuf.Timestamp
}
var file_proto_v1_repository_proto_depIdxs = []int32{
	19, // 0: clonr.v1.Repository.cloned_at:type_name -> google.protobuf.Timestamp
	19, // 1: clonr.v1.Repository.updated_at:type_name -> google.protobuf.Timestamp
	19, // 2: clonr.v1.Repository.last_checked:type_name -> google.protobuf.Timestamp
	0,  // 3: clonr.v1.GetAllReposResponse.repositories:type_name -> clonr.v1.Repository
	0,  // 4: clonr.v1.GetReposResponse.repositories:type_name -> clonr.v1.Repository
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_v1_repository_proto_init() }
func file_proto_v1_repository_proto_init() {
	if File_proto_v1_repository_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_repository_proto_rawDesc), len(file_proto_v1_repository_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_v1_repository_proto_goTypes,
		DependencyIndexes: file_proto_v1_repository_proto_depIdxs,
		MessageInfos:      file_proto_v1_repository_proto_msgTypes,
	}.Build()
	File_proto_v1_repository_proto = out.File
	file_proto_v1_repository_proto_goTypes = nil
	file_proto_v1_repository_proto_depIdxs = nil
}
