// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/workspace.proto

package clonrv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Workspace represents a logical grouping of repositories
type Workspace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Active        bool                   `protobuf:"varint,4,opt,name=active,proto3" json:"active,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workspace) Reset() {
	*x = Workspace{}
	mi := &file_v1_workspace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workspace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workspace) ProtoMessage() {}

func (x *Workspace) ProtoReflect() protoreflect.Message {
	mi := &file_v1_workspace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workspace.ProtoReflect.Descriptor instead.
func (*Workspace) Descriptor() ([]byte, []int) {
	return file_v1_workspace_proto_rawDescGZIP(), []int{0}
}

func (x *Workspace) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Workspace) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Workspace) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Workspace) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Workspace) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Workspace) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// SaveWorkspace RPC messages
type SaveWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspace     *Workspace             `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveWorkspaceRequest) Reset() {
	*x = SaveWorkspaceRequest{}
	mi := &file_v1_workspace_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveWorkspaceRequest) ProtoMessage() {}

func (x *SaveWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_workspace_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*SaveWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_v1_workspace_proto_rawDescGZIP(), []int{1}
}

func (x *SaveWorkspaceRequest) GetWorkspace() *Workspace {
	if x != nil {
		return x.Workspace
	}
	return nil
}

type SaveWorkspaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveWorkspaceResponse) Reset() {
	*x = SaveWorkspaceResponse{}
	mi := &file_v1_workspace_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveWorkspaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveWorkspaceResponse) ProtoMessage() {}

func (x *SaveWorkspaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_workspace_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveWorkspaceResponse.ProtoReflect.Descriptor instead.
func (*SaveWorkspaceResponse) Descriptor() ([]byte, []int) {
	return file_v1_workspace_proto_rawDescGZIP(), []int{2}
}

func (x *SaveWorkspaceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// GetWorkspace RPC messages
type GetWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkspaceRequest) Reset() {
	*x = GetWorkspaceRequest{}
	mi := &file_v1_workspace_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkspaceRequest) ProtoMessage() {}

func (x *GetWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_workspace_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*GetWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_v1_workspace_proto_rawDescGZIP(), []int{3}
}

func (x *GetWorkspaceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetWorkspaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspace     *Workspace             `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkspaceResponse) Reset() {
	*x = GetWorkspaceResponse{}
	mi := &file_v1_workspace_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkspaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkspaceResponse) ProtoMessage() {}

func (x *GetWorkspaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_workspace_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkspaceResponse.ProtoReflect.Descriptor instead.
func (*GetWorkspaceResponse) Descriptor() ([]byte, []int) {
	return file_v1_workspace_proto_rawDescGZIP(), []int{4}
}

func (x *GetWorkspaceResponse) GetWorkspace() *Workspace {
	if x != nil {
		return x.Workspace
	}
	return nil
}

// GetActiveWorkspace RPC messages
type GetActiveWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveWorkspaceRequest) Reset() {
	*x = GetActiveWorkspaceRequest{}
	mi := &file_v1_workspace_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveWorkspaceRequest) ProtoMessage() {}

func (x *GetActiveWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_workspace_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*GetActiveWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_v1_workspace_proto_rawDescGZIP(), []int{5}
}

type GetActiveWorkspaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspace     *Workspace             `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveWorkspaceResponse) Reset() {
	*x = GetActiveWorkspaceResponse{}
	mi := &file_v1_workspace_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveWorkspaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveWorkspaceResponse) ProtoMessage() {}

func (x *GetActiveWorkspaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_workspace_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveWorkspaceResponse.ProtoReflect.Descriptor instead.
func (*GetActiveWorkspaceResponse) Descriptor() ([]byte, []int) {
	return file_v1_workspace_proto_rawDescGZIP(), []int{6}
}

func (x *GetActiveWorkspaceResponse) GetWorkspace() *Workspace {
	if x != nil {
		return x.Workspace
	}
	return nil
}

// SetActiveWorkspace RPC messages
type SetActiveWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetActiveWorkspaceRequest) Reset() {
	*x = SetActiveWorkspaceRequest{}
	mi := &file_v1_workspace_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetActiveWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetActiveWorkspaceRequest) ProtoMessage() {}

func (x *SetActiveWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_workspace_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetActiveWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*SetActiveWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_v1_workspace_proto_rawDescGZIP(), []int{7}
}

func (x *SetActiveWorkspaceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SetActiveWorkspaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetActiveWorkspaceResponse) Reset() {
	*x = SetActiveWorkspaceResponse{}
	mi := &file_v1_workspace_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetActiveWorkspaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetActiveWorkspaceResponse) ProtoMessage() {}

func (x *SetActiveWorkspaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_workspace_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetActiveWorkspaceResponse.ProtoReflect.Descriptor instead.
func (*SetActiveWorkspaceResponse) Descriptor() ([]byte, []int) {
	return file_v1_workspace_proto_rawDescGZIP(), []int{8}
}

func (x *SetActiveWorkspaceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// ListWorkspaces RPC messages
type ListWorkspacesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkspacesRequest) Reset() {
	*x = ListWorkspacesRequest{}
	mi := &file_v1_workspace_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkspacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkspacesRequest) ProtoMessage() {}

func (x *ListWorkspacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_workspace_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkspacesRequest.ProtoReflect.Descriptor instead.
func (*ListWorkspacesRequest) Descriptor() ([]byte, []int) {
	return file_v1_workspace_proto_rawDescGZIP(), []int{9}
}

type ListWorkspacesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspaces    []*Workspace           `protobuf:"bytes,1,rep,name=workspaces,proto3" json:"workspaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkspacesResponse) Reset() {
	*x = ListWorkspacesResponse{}
	mi := &file_v1_workspace_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkspacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkspacesResponse) ProtoMessage() {}

func (x *ListWorkspacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_workspace_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkspacesResponse.ProtoReflect.Descriptor instead.
func (*ListWorkspacesResponse) Descriptor() ([]byte, []int) {
	return file_v1_workspace_proto_rawDescGZIP(), []int{10}
}

func (x *ListWorkspacesResponse) GetWorkspaces() []*Workspace {
	if x != nil {
		return x.Workspaces
	}
	return nil
}

// DeleteWorkspace RPC messages
type DeleteWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWorkspaceRequest) Reset() {
	*x = DeleteWorkspaceRequest{}
	mi := &file_v1_workspace_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkspaceRequest) ProtoMessage() {}

func (x *DeleteWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_workspace_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*DeleteWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_v1_workspace_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteWorkspaceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteWorkspaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWorkspaceResponse) Reset() {
	*x = DeleteWorkspaceResponse{}
	mi := &file_v1_workspace_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWorkspaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkspaceResponse) ProtoMessage() {}

func (x *DeleteWorkspaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_workspace_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkspaceResponse.ProtoReflect.Descriptor instead.
func (*DeleteWorkspaceResponse) Descriptor() ([]byte, []int) {
	return file_v1_workspace_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteWorkspaceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// WorkspaceExists RPC messages
type WorkspaceExistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceExistsRequest) Reset() {
	*x = WorkspaceExistsRequest{}
	mi := &file_v1_workspace_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceExistsRequest) ProtoMessage() {}

func (x *WorkspaceExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_workspace_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceExistsRequest.ProtoReflect.Descriptor instead.
func (*WorkspaceExistsRequest) Descriptor() ([]byte, []int) {
	return file_v1_workspace_proto_rawDescGZIP(), []int{13}
}

func (x *WorkspaceExistsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type WorkspaceExistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceExistsResponse) Reset() {
	*x = WorkspaceExistsResponse{}
	mi := &file_v1_workspace_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceExistsResponse) ProtoMessage() {}

func (x *WorkspaceExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_workspace_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceExistsResponse.ProtoReflect.Descriptor instead.
func (*WorkspaceExistsResponse) Descriptor() ([]byte, []int) {
	return file_v1_workspace_proto_rawDescGZIP(), []int{14}
}

func (x *WorkspaceExistsResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

// GetReposByWorkspace RPC messages
type GetReposByWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspace     string                 `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReposByWorkspaceRequest) Reset() {
	*x = GetReposByWorkspaceRequest{}
	mi := &file_v1_workspace_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReposByWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReposByWorkspaceRequest) ProtoMessage() {}

func (x *GetReposByWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_workspace_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReposByWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*GetReposByWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_v1_workspace_proto_rawDescGZIP(), []int{15}
}

func (x *GetReposByWorkspaceRequest) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

type GetReposByWorkspaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []string               `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReposByWorkspaceResponse) Reset() {
	*x = GetReposByWorkspaceResponse{}
	mi := &file_v1_workspace_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReposByWorkspaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReposByWorkspaceResponse) ProtoMessage() {}

func (x *GetReposByWorkspaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_workspace_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReposByWorkspaceResponse.ProtoReflect.Descriptor instead.
func (*GetReposByWorkspaceResponse) Descriptor() ([]byte, []int) {
	return file_v1_workspace_proto_rawDescGZIP(), []int{16}
}

func (x *GetReposByWorkspaceResponse) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

// UpdateRepoWorkspace RPC messages
type UpdateRepoWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Workspace     string                 `protobuf:"bytes,2,opt,name=workspace,proto3" json:"workspace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRepoWorkspaceRequest) Reset() {
	*x = UpdateRepoWorkspaceRequest{}
	mi := &file_v1_workspace_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRepoWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRepoWorkspaceRequest) ProtoMessage() {}

func (x *UpdateRepoWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_workspace_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRepoWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*UpdateRepoWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_v1_workspace_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateRepoWorkspaceRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UpdateRepoWorkspaceRequest) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

type UpdateRepoWorkspaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRepoWorkspaceResponse) Reset() {
	*x = UpdateRepoWorkspaceResponse{}
	mi := &file_v1_workspace_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRepoWorkspaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRepoWorkspaceResponse) ProtoMessage() {}

func (x *UpdateRepoWorkspaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_workspace_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRepoWorkspaceResponse.ProtoReflect.Descriptor instead.
func (*UpdateRepoWorkspaceResponse) Descriptor() ([]byte, []int) {
	return file_v1_workspace_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateRepoWorkspaceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_v1_workspace_proto protoreflect.FileDescriptor

const file_v1_workspace_proto_rawDesc = "" +
	"\n" +
	"\x12v1/workspace.proto\x12\bclonr.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe3\x01\n" +
	"\tWorkspace\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x16\n" +
	"\x06active\x18\x04 \x01(\bR\x06active\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"I\n" +
	"\x14SaveWorkspaceRequest\x121\n" +
	"\tworkspace\x18\x01 \x01(\v2\x13.clonr.v1.WorkspaceR\tworkspace\"1\n" +
	"\x15SaveWorkspaceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\")\n" +
	"\x13GetWorkspaceRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"I\n" +
	"\x14GetWorkspaceResponse\x121\n" +
	"\tworkspace\x18\x01 \x01(\v2\x13.clonr.v1.WorkspaceR\tworkspace\"\x1b\n" +
	"\x19GetActiveWorkspaceRequest\"O\n" +
	"\x1aGetActiveWorkspaceResponse\x121\n" +
	"\tworkspace\x18\x01 \x01(\v2\x13.clonr.v1.WorkspaceR\tworkspace\"/\n" +
	"\x19SetActiveWorkspaceRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"6\n" +
	"\x1aSetActiveWorkspaceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x17\n" +
	"\x15ListWorkspacesRequest\"M\n" +
	"\x16ListWorkspacesResponse\x123\n" +
	"\n" +
	"workspaces\x18\x01 \x03(\v2\x13.clonr.v1.WorkspaceR\n" +
	"workspaces\",\n" +
	"\x16DeleteWorkspaceRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"3\n" +
	"\x17DeleteWorkspaceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\",\n" +
	"\x16WorkspaceExistsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"1\n" +
	"\x17WorkspaceExistsResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\":\n" +
	"\x1aGetReposByWorkspaceRequest\x12\x1c\n" +
	"\tworkspace\x18\x01 \x01(\tR\tworkspace\"1\n" +
	"\x1bGetReposByWorkspaceResponse\x12\x12\n" +
	"\x04urls\x18\x01 \x03(\tR\x04urls\"L\n" +
	"\x1aUpdateRepoWorkspaceRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1c\n" +
	"\tworkspace\x18\x02 \x01(\tR\tworkspace\"7\n" +
	"\x1bUpdateRepoWorkspaceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccessB\x8c\x01\n" +
	"\fcom.clonr.v1B\x0eWorkspaceProtoP\x01Z+github.com/inovacc/clonr/pkg/api/v1;clonrv1\xa2\x02\x03CXX\xaa\x02\bClonr.V1\xca\x02\bClonr\\V1\xe2\x02\x14Clonr\\V1\\GPBMetadata\xea\x02\tClonr::V1b\x06proto3"

var (
	file_v1_workspace_proto_rawDescOnce sync.Once
	file_v1_workspace_proto_rawDescData []byte
)

func file_v1_workspace_proto_rawDescGZIP() []byte {
	file_v1_workspace_proto_rawDescOnce.Do(func() {
		file_v1_workspace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_workspace_proto_rawDesc), len(file_v1_workspace_proto_rawDesc)))
	})
	return file_v1_workspace_proto_rawDescData
}

var file_v1_workspace_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_v1_workspace_proto_goTypes = []any{
	(*Workspace)(nil),                   // 0: clonr.v1.Workspace
	(*SaveWorkspaceRequest)(nil),        // 1: clonr.v1.SaveWorkspaceRequest
	(*SaveWorkspaceResponse)(nil),       // 2: clonr.v1.SaveWorkspaceResponse
	(*GetWorkspaceRequest)(nil),         // 3: clonr.v1.GetWorkspaceRequest
	(*GetWorkspaceResponse)(nil),        // 4: clonr.v1.GetWorkspaceResponse
	(*GetActiveWorkspaceRequest)(nil),   // 5: clonr.v1.GetActiveWorkspaceRequest
	(*GetActiveWorkspaceResponse)(nil),  // 6: clonr.v1.GetActiveWorkspaceResponse
	(*SetActiveWorkspaceRequest)(nil),   // 7: clonr.v1.SetActiveWorkspaceRequest
	(*SetActiveWorkspaceResponse)(nil),  // 8: clonr.v1.SetActiveWorkspaceResponse
	(*ListWorkspacesRequest)(nil),       // 9: clonr.v1.ListWorkspacesRequest
	(*ListWorkspacesResponse)(nil),      // 10: clonr.v1.ListWorkspacesResponse
	(*DeleteWorkspaceRequest)(nil),      // 11: clonr.v1.DeleteWorkspaceRequest
	(*DeleteWorkspaceResponse)(nil),     // 12: clonr.v1.DeleteWorkspaceResponse
	(*WorkspaceExistsRequest)(nil),      // 13: clonr.v1.WorkspaceExistsRequest
	(*WorkspaceExistsResponse)(nil),     // 14: clonr.v1.WorkspaceExistsResponse
	(*GetReposByWorkspaceRequest)(nil),  // 15: clonr.v1.GetReposByWorkspaceRequest
	(*GetReposByWorkspaceResponse)(nil), // 16: clonr.v1.GetReposByWorkspaceResponse
	(*UpdateRepoWorkspaceRequest)(nil),  // 17: clonr.v1.UpdateRepoWorkspaceRequest
	(*UpdateRepoWorkspaceResponse)(nil), // 18: clonr.v1.UpdateRepoWorkspaceResponse
	(*timestamppb.Timestamp)(nil),       // 19: google.protobuf.Timestamp
}
var file_v1_workspace_proto_depIdxs = []int32{
	19, // 0: clonr.v1.Workspace.created_at:type_name -> google.protobuf.Timestamp
	19, // 1: clonr.v1.Workspace.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: clonr.v1.SaveWorkspaceRequest.workspace:type_name -> clonr.v1.Workspace
	0,  // 3: clonr.v1.GetWorkspaceResponse.workspace:type_name -> clonr.v1.Workspace
	0,  // 4: clonr.v1.GetActiveWorkspaceResponse.workspace:type_name -> clonr.v1.Workspace
	0,  // 5: clonr.v1.ListWorkspacesResponse.workspaces:type_name -> clonr.v1.Workspace
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_v1_workspace_proto_init() }
func file_v1_workspace_proto_init() {
	if File_v1_workspace_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_workspace_proto_rawDesc), len(file_v1_workspace_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_workspace_proto_goTypes,
		DependencyIndexes: file_v1_workspace_proto_depIdxs,
		MessageInfos:      file_v1_workspace_proto_msgTypes,
	}.Build()
	File_v1_workspace_proto = out.File
	file_v1_workspace_proto_goTypes = nil
	file_v1_workspace_proto_depIdxs = nil
}
