// Code generated by go generate; DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"

	"github.com/spf13/cobra"
)

var (
	jsonOutput bool
)

// Version information embedded at build time
const (
	// Version is the application version (from git tag or VERSION env)
	Version = "v0.1.0"

	// GitHash is the git commit hash
	GitHash = "de64456825c8e06c2719db46692516ccaaed093f"

	// BuildTime is when the binary was built
	BuildTime = "2025-12-30T02:23:10Z"

	// BuildHash is a unique hash for this build
	BuildHash = "64b3052785d919d22f324a1f7656d55500e8835f45f31d22d9bf1bfe2bae1bd8"

	// GoVersion is the Go version used to build
	GoVersion = "go1.25.5"

	// GOOS is the target operating system
	GOOS = "windows"

	// GOARCH is the target architecture
	GOARCH = "amd64"
)

// VersionInfo contains all version metadata.
type VersionInfo struct {
	GoVersion string `json:"go_version"`
	GoOS      string `json:"goos"`
	GoArch    string `json:"goarch"`
	Version   string `json:"version"`
	GitHash   string `json:"git_hash"`
	BuildTime string `json:"build_time"`
	BuildHash string `json:"build_hash"`
}

// versionCmd represents the version command.
var versionCmd = &cobra.Command{
	Use:   "version",
	Short: "Print version information",
	Long: `Display version information including:
	- Application version
	- Git commit hash
	- Build time
	- Build hash
	- Go version
	- OS/Architecture`,
	Run: runVersion,
}

func init() {
	rootCmd.AddCommand(versionCmd)
	versionCmd.Flags().BoolVarP(&jsonOutput, "json", "j", false, "Output version info as JSON")
}

func runVersion(cmd *cobra.Command, args []string) {
	if jsonOutput {
		fmt.Println(GetVersionJSON())
	} else {
		printVersion()
	}
}

// GetVersionInfo returns the version information.
func GetVersionInfo() *VersionInfo {
	return &VersionInfo{
		GoVersion: GoVersion,
		GoOS:      GOOS,
		GoArch:    GOARCH,
		Version:   Version,
		GitHash:   GitHash,
		BuildTime: BuildTime,
		BuildHash: BuildHash,
	}
}

// GetVersionJSON returns the version information as a JSON string.
func GetVersionJSON() string {
	data, err := json.MarshalIndent(GetVersionInfo(), "", "  ")
	if err != nil {
		return "{}"
	}

	return string(data)
}

func printVersion() {
	fmt.Printf("Version:    %s\n", Version)
	fmt.Printf("Git Hash:   %s\n", GitHash)
	fmt.Printf("Build Time: %s\n", BuildTime)
	fmt.Printf("Build Hash: %s\n", BuildHash)
	fmt.Printf("Go Version: %s\n", GoVersion)
	fmt.Printf("OS/Arch:    %s/%s\n", GOOS, GOARCH)
}
